<?php
// Title
$this->headTitle ()->prepend ( 'Search Skills' );
// Javascript
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/frontend/skills_search.js" );
// CSS
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/frontend/skills_search.css" );
// Partial file(side menu)
echo $this->partial ( 'partials/skills_menu.phtml' );
?>

 <!-- Content Right Left Ends -->
        
        <!-- Content Right Right Starts -->
       	  <div class="content-right-right">
        	<div class="job-application-outer">
        	 
        	  <div class="job-application-hdr1">
       	        <div class="job-application-hdr1lt">
           	        <h4>Search Skills</h4>
           	      </div>
        	  </div>
              
       
              <div class=" search-skills">
                <form action="/<?php echo PROJECT_NAME;?>skills/search-skills" method="get">
					<input type="text" name="search" value="<?php echo $this->search; ?>" placeholder="Enter Skill"> 
					<input type="submit" value="" name="search_btn" class="search-skills-icon">
				</form>
  	 
              </div>
              
              
            </div>
            <div class="white-outer2">
            <div class="skill-outer">
            <h4>Search Result</h4>
            	<!-- Col3 Starts -->
<?php 
	if( $this->paginator )
	{	
		if( $this->paginator->getTotalItemCount() )
		{		
?>	
		<div class="bsr-box">
		<div class="bookmark-search-right">	
		<div class="col3">
		<div class="fl text-grey3">
<?php 
				$query_str = "";
				foreach( $this->prms as $key=>$p )
				{
					if( $key == "controller" || $key == "action" || $key == "module" || $key == "list_len" )
					{
						continue;
					}
					$query_str .= $key."=".$p."&amp;";
				}
?>
				VIEWS 
				<a class="text-grey3-link" style="margin-left: 5px" href="<?php echo "/".PROJECT_NAME."skills/search-skills?".$query_str."list_len=20";?>">
					<?php echo $this->prms["list_len"] == 20 ? "<b>20</b>" : '20'?>
				</a> | 
				<a class="text-grey3-link" href="<?php echo "/".PROJECT_NAME."skills/search-skills?".$query_str."list_len=50";?>">
					<?php echo $this->prms["list_len"] == 50 ? "<b>50</b>" : '50'?>
				</a> | 
				<a class="text-grey3-link" href="<?php echo "/".PROJECT_NAME."skills/search-skills?".$query_str."list_len=100";?>">
					<?php echo $this->prms["list_len"] == 100 ? "<b>100</b>" : '100'?>
				</a> | 
				<a class="text-grey3-link" href="<?php echo "/".PROJECT_NAME."skills/search-skills?".$query_str."list_len=all";?>">
					<?php echo $this->prms["list_len"] == 'all' ? "<b>All</b>" : 'All'?>
				</a>
			</div>
			<div class="fr  text-grey3">
		<?php
				echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
		?>							
		</div>
		</div>
		</div>
		</div>
<?php
			}
		}
?>

  <?php 
  if($this->paginator)
  {
  			if( $this->paginator->getTotalItemCount() )
			 {	 
			 	
				?>
				
		<div class="skill-outer-data">
				<?php 
				 foreach ( $this->paginator->getCurrentItems() as $currentItem )
				{
					$ilook_user_id = $currentItem->getIlook_user_id();
					$skill = $currentItem->getSkill();
					$first_letter_of_skill = $skill[0]; 
					
					$checkIfSkillIsFollowed = \Extended\user_skills::checkIfSkillIsFollowed( $currentItem->getId(), Auth_UserAdapter::getIdentity()->getId() );
	
				?>
					<div class="skill-outer-col1">
					<div class="skill-outer-col1-lt"><img src="<?php echo Helper_common::getImageAccToAlphabet($first_letter_of_skill);?>" width="60" height="60" alt=""/></div>
					<div class="skill-outer-col1-mid">
<?php 					
					// check if user type is individual search for recruiter and search for individual
					// in case of recruiter user type
					if($this->user_type == 1 || $this->user_type == 2 || $this->user_type == 3  )
        			{
?>
					<h4><a class="" id="" href="/<?php echo PROJECT_NAME; ?>skills/skill-recruiters/skillId/<?php echo $currentItem->getId(); ?>/user/within_links"><?php echo $skill; ?></a></h4>
<?php 			
        			}
        			else
        			{
?>
        			<h4><a class="" id="" href="/<?php echo PROJECT_NAME; ?>skills/skill-individuals/skillId/<?php echo $currentItem->getId(); ?>/user/within_links"><?php echo $skill; ?></a></h4>
<?php         			
        			}
        		
?>
					</div>
					
					<div class="skill-outer-col1-rt">
					<?php if($checkIfSkillIsFollowed) {?>
					<div class="following">Following</div>
					<?php } else {?>
					<input value="Follow" class="btn-green skill_<?php echo $currentItem->getId(); ?>" type="button" onclick="followSomeSkill(<?php echo  $currentItem->getId();?>, <?php echo Auth_UserAdapter::getIdentity()->getId();?>, this );"/>
					<?php } ?>
					</div>
					
					</div>
				<?php 
				} 
		?>
		</div>
		
			<?php 	
			 }
			
			
  }
  else if (!empty($_REQUEST))
  {
  	?>
  
  	<div class="no-rec-msg text-grey3">
  	
  	<?php echo "No records found"; ?>
  	</div>
  
  	<?php
  }
  
?>	
            
           
             </div>   
    
    
    </div>

		
	