<?php
$this->headTitle()->prepend('Enquiry');
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/enquiry.js" );
/* Including CSS */

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/enquiry.css" );
?>
<style>
.sub-admin-form{ width:96%; float:left; margin:0; padding:0 2%;}
.sub-admin-form-lt{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-rt{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-lt label{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-lt span{ width:50%; float:left; margin:0; padding:0; min-height:60px;}
.sub-admin-form-rt label{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-rt span{ width:50%; float:left; margin:0; padding:0; min-height:60px;}
.sub-admin-btn-outer{    box-sizing: border-box;
    float: left;
    padding-left: 12%;
    padding-top: 20px;
    text-align: left;
    width: 100%;}
.sub-admin-btn-outer input[type="button"]{ width:auto; /* padding:5px 10px; */}



.enquiry-labelspan-outer span.inputfield {
    float: left;
    margin-left: 2%;
    padding-bottom: 15px;
    text-align: left;
    width: 68%;
}

.enquiry-labelspan-outer {
    color: #000;
    float: left;
    min-height: 35px;
    width: 100%;
}

div.content label {
    font-size: 12px;
    height: 28px;
    text-align: left;
    width: 7%;
}



@media only screen and (min-device-width:768px) and (max-device-width:1024px) {	
.sub-admin-form-lt{ width:100%;}
.sub-admin-form-rt{ width:100%; }
.sub-admin-form-lt label{ width:100%; }
.sub-admin-form-lt span{ width:100%;}
.sub-admin-form-lt span input{width:75%;}
.sub-admin-form-rt span input{width:75%;}
.sub-admin-form-rt label{ width:100%;}
.sub-admin-form-rt span{ width:100%;}

}
</style>
<?php 
	$enquiry_details = $this->enquiry_details;
	//Zend_Debug::dump($enquiry_details[0]->getIlookUser()); die;
?>
	<div id='heading'>
	     <h2><a href = '/<?php echo PROJECT_NAME?>admin/enquiry'>
	     Enquiry
	     </a> -> 
	Reply
	</h2>
	</div>
	<form name="reply-enquiry" id="reply-enquiry" method="POST" action="/<?php echo PROJECT_NAME; ?>admin/enquiry/reply/id/<?php echo $enquiry_details[0]->getId(); ?>" enctype="multipart/form-data" >
	<div class="content">
		<div class="enquiry-labelspan-outer">
			<label>Description</label>
			<span class="inputfield"><?php echo $enquiry_details[0]?$enquiry_details[0]->getBody():'';  ?></span>
			</div>
			<div class="enquiry-labelspan-outer">
			<label>Reply</label>
			
			<span style=" float: left; margin-left: 2%; width: 67%;"><textarea  id= "enquiry_reply_editor" name="reply" /></textarea></span>
			</div>
			
			<input type="hidden" id= "email_id" name="email_id"  value ="<?php echo  $enquiry_details[0]?$enquiry_details[0]->getEmail_id():''; ?>"/>
			<input type="hidden" id= "user_id" name="user_id"  value ="<?php echo  $enquiry_details[0]->getIlookUser()?$enquiry_details[0]->getIlookUser()->getId():''; ?>"/>
			<input type="hidden" id= "description" name="description" value ="<?php echo  $enquiry_details[0]?$enquiry_details[0]->getBody():''; ?>"/>
			</div>
		
	  <div class="sub-admin-btn-outer">
			<input value="Save" class="btn btn-large" type="submit"/>
			<a href="<?php echo PROJECT_URL."/".PROJECT_NAME."admin/enquiry" ?>" >
			<input value="Cancel" class="btn btn-large" id="sub-admins-cancel" type="button"/>
			</a>
	  </div>
	
</div>
</form>
