<?php
$this->headTitle()->prepend('Login');
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/login.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/admin/login.js");
?>

<form name="form1" action='/<?php echo PROJECT_NAME; ?>admin/authenticate/login' id="form1"  method="post"    >
	<div class="login-box-outer" >
		<div class="login-logo" >
			<img alt="iLook" src="<?php echo IMAGE_PATH;?>/logo.png">
	    </div>
		<div class="login-box">
	    	<div class="login-box-heading">ADMINISTRATOR LOGIN</div>
	    	
<?php
			$messages = new Zend_Session_Namespace ('admin_messages');
			if($messages->errorMsg)
			{	
			    echo "<div class='login-input error' id='error-msg' style = 'height : 14px; margin-top: 15px; color: #B94A48;'>";
		    	echo $messages->errorMsg;
		    	echo "</div>";
			}
			unset( $messages->errorMsg );
			if($messages->successMsg)
			{
				echo "<div class='login-input success' id='success-msg' style = 'height : 14px; margin-top: 15px;'>";
				echo $messages->successMsg;
				echo "</div>";
			}
?>
	    	<div class="input-prepend login-input" >
	    	
	          	<span class="add-on"><i class="icon-user"></i></span><input type="text" maxlength="255" placeholder="Email ID" name="email" id="email" value="">
	          	
	        </div>
	        <div class="input-prepend login-input1">
	          <span class="add-on"><i class="icon-lock"></i></span><input type="password"  maxlength="20" placeholder="Password" name="pwd" id="pwd">
	        </div>
	        <div class="button-outer">
	
	        <button type="submit" name="button" id="button" class="btn btn-large btn-default" title="Login">LOGIN</button>
					<a href="/<?php echo PROJECT_NAME;?>admin/recovery/password" title="Forgot Password">Forgot Password?</a>
					
	        </div>
	    </div>
	</div>
</form>