<?php
// Title
$this->headTitle ()->prepend ( 'Monster-Jobs' );
// Javascript
$this->headScript()->appendFile( PUBLIC_PATH."/js/jquery.form.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );
//$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/frontend/jobs_recommended.js" );
// CSS
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/frontend/monster_jobs.css" );
// Partial file(side menu)
echo $this->partial ( 'partials/jobs_menu.phtml' );

?>

<div class="content-right-right">

<!-- Bookmarks Header Starts -->
	<div style="padding-bottom:10px !important;" class="job-hdr">
     	<div class="job-hdr-top">
        	<h2>Monster Jobs US</h2>
		</div>
	</div>
<!-- Bookmarks Header Ends -->
<div id="jobslisting">
<div id="MonsterJobSearchResultPlaceHolderLn4AAA_e_e" class="xmns_distroph"></div>
<script type="text/javascript">
(function() {
  var oScript = document.createElement('script');
  oScript.type = 'text/javascript';
  oScript.async = true;
  oScript.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'publisher.monster.com/Services/WidgetHandler.ashx?WidgetID=EAAQnoABGw8XGPtQNfKfsHw66w--&Verb=Initialize';
  var oParent = document.getElementsByTagName('script')[0];
  oParent.parentNode.insertBefore(oScript, oParent);
})();
</script>
<a id="monsterBrowseLinkLn4AAA_e_e" target="_blank" class="monsterBrowseLink fnt4" href="http://jobsearch.monster.com/jobs/">View More Job Search Results</a>

</div>
