   <?php
// Title
$this->headTitle ()->prepend ( 'My applications' );
// Javascript
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/frontend/job_applications.js" );
// CSS
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/frontend/job_applications.css" );
// Partial file(side menu)
echo $this->partial ( 'partials/jobs_menu.phtml' );

?>
<style>
.job-content
{
	margin:0 0 2px 0 !important;
    padding: 0 !important;
    width: 99.8% !important;
}
.more-detail-application{
	bottom: 10px;
    position: absolute;
    right: 19px;
    width: auto;
}
.mail-grey-hdr-col1 {
    width: 99% !important;
}
</style>
<!-- Content Right Right Starts -->
<div class="content-right-right">
<!-- Bookmarks Header Starts -->
	<div style="padding-bottom:10px;" class="job-hdr">
		<div class="job-hdr-top">
			<h2>Job Applications</h2>
			<!-- <div class="need-help">
				<div class="need-help-text">
					<a href="javascript:;" class="text-grey3-link">Need Help?</a> 
					<img  width="20" height="20" align="absmiddle" src="<?php //echo IMAGE_PATH; ?>/help-icon.png">
				</div>
			</div>-->
		</div>
		
        <?php 
				if( $this->paginator )
				{	
					if( $this->paginator->getTotalItemCount() )
					{
?>				
					<div class="bookmarks-add-new">
						<div class="col3" style="float:left;">
							<div class="fr  text-grey3">
<?php
							echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
?>							
							</div>
						</div>
			        </div>
<?php
					}
				}
?>	
        
	</div>
<!-- Bookmarks Header Ends -->
<!--Mail-grey-hdr-col1 Starts --> 
<?php 
if( $this->paginator )
{

	$applied_jobs =  $this->applied_jobs['job'];
	if( $this->paginator->getTotalItemCount() )
	{
	foreach($this->paginator as $applied_jobs)
	{
		if($applied_jobs['job_image']!=null)
		{
			$imgPath = IMAGE_PATH.'/jobs/'.$applied_jobs['job_image'];
		}
		else
		{
			$imgPath= IMAGE_PATH.'/job_default_image.png';
		}
?>		
		<div class="job-application-single">
		<div class="mail-grey-hdr-col1 remove-bg-gray" id="job-content_<?php echo $applied_jobs['id'];?>">
			<div class = "applied_job_img">
				<a class=" text-purple-link" href="/<?php  echo PROJECT_NAME?>job/job-detail/job_id/<?php echo $applied_jobs['job_id'] ;?>">
					<div class="applied_job_img_inner">
						<img style="width:60px;" id= "job_img" src="<?php echo PUBLIC_PATH; ?>/Imagehandler/GenerateImage.php?image=<?php echo $imgPath;?>&h=60&w=60">
					</div>
				</a>	
			</div>
			<div class="mid">
				<h4 class="font-arial" style="cursor: default;">
					<a style="color:#6C518F !important;" class="job_listing_job_title text-purple-link" href="/<?php  echo PROJECT_NAME?>job/job-detail/job_id/<?php echo $applied_jobs['job_id'] ;?>">
						<?php echo $applied_jobs['job_title'];?>
					</a>
				</h4>
				<p class="job_listing_company_name">
					<?php echo $applied_jobs['company_name'];?>
				</p>
				<p class="job_listing_industry_location"><?php echo $applied_jobs['industry_name'];?>,  <?php if ($applied_jobs['city']){ echo $applied_jobs['city']; echo',';}?> <?php if($applied_jobs['state']){echo $applied_jobs['state']; echo',';}?><?php echo $applied_jobs['country'];?></p>
				<p class="job_listing_salary_exp">
				<?php 
				if ($applied_jobs['salaryRange'])
				{
					echo $applied_jobs['salaryRange'] ."|";
				}
				echo $applied_jobs['jobType'];?> 
<?php 
				if($applied_jobs['experienceLevel']!="")
				{ 
					echo "| ".$applied_jobs['experienceLevel'];
				}
?>
				</p>
			</div>	
			<div class="right">
				<div class="top">
				<div style="width:auto; margin:5px 0 0 0; padding:0;">
				Applied on
				</div>
				<?php echo $applied_jobs['applied_on_date'];?>
				</div>
				
			</div>
		<!-- 	<div class="more-detail-application">
				<a href="javascript:;" class=" text-purple-link more_details" id="more_details_<?php echo $applied_jobs['id'];?>" rel="<?php echo $applied_jobs['id'];?>"><img alt="image not found" src="<?php echo IMAGE_PATH; ?>/plus-purple.png" style="width: 9px; height: 8px; border-right-width: 3px; padding-right: 5px;">More Details
				</a>
			</div>
			-->
		</div>
	<!--Mail-grey-hdr-col1 Ends -->
		<div class=" job-content remove-bg-gray" style="padding: 0px; height: 0; margin-bottom: 0px; margin-left: 0px; ">
			<div class="apply-2-job text-purple bg-none">
				
				
			</div>
		</div>
		
	<!-- Applicant Col Starts -->
		<div class="job-content more_details job-content-border" id="more_details_<?php echo $applied_jobs['id'];?>"style="display:none; width:91.5% !important; padding:0 3.7% !important;">
			<div class="applicant-col1 text-grey2">
				<h3 class="sub-heading-arial-narrow" style="font-weight: bold;">job description </h3>
			</div>
		<!-- Applicant Col Ends -->
		<!-- Applicant Col Starts -->
			<div class="applicant-col1 text-grey2">
			<?php echo $applied_jobs['description'];?>
			</div>
		<!-- Applicant Col Ends -->
			<div class="bdr-grey">
			</div>
			<div class="job-detail-col1">
				<h4 class="sub-heading-arial-narrow" style="font-weight: bold;">Additional information</h4>
				<p>
					<label>Job Posted by</label>
					<span><?php echo $applied_jobs['job_posted_by'];?></span>
				</p>
				<p>
					<label>Posted</label>
					<span><?php echo $applied_jobs['time_of_post'];?></span>
				</p>
				<p>
					<label>Type of Work</label>
					<span><?php echo $applied_jobs['jobType'];?></span>
				</p>
				<?php 
					if($applied_jobs['experienceLevel']!=""){
				?>
				<p>
					<label>Experience</label>
					<span><?php echo $applied_jobs['experienceLevel'];?></span>
				</p>
		<?php 
					}
		?>
				<p>
					<label>Industries</label>
					<span><?php echo $applied_jobs['industry_name'];?></span>
				</p>
				<p>
					<label>Job Id</label>
					<span><?php echo $applied_jobs['job_id'];?></span>
				</p>
			</div>
			</div>
			<div class="new-border-space"></div>
			</div>
<?php 
		}
	}
}
else
{
	echo "<div class='mail-grey-hdr-col1-no-records' style='text-align:center;'>
	<div class='no_messages'>
				<div class='no_messages-img'><img src='".PUBLIC_PATH."/images/folder-empty.png'></div>
				<div class='no_messages-data'>This folder is empty</div>
			</div>
	</div>";
}
?>
</div>
<!-- Content Right Right Ends -->