<?php 
// Partial file(side menu)
echo $this->partial ( 'partials/jobs_menu.phtml' );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/frontend/received-application.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/short_profile.js" );

?>
<style type="text/css">
.manage-popup{
	width:145px;
	z-index: 1 !important;
}
.job-application-col1-mid{
	width:440px;
}
.noRecFound{
    border: 1px solid #A797BC;
    color: #A797BC;
    display: table-cell;
    float: left;
    height: 26px;
    margin: 0 2% 0;
    padding-top: 9px;
    text-align: center;
    width: 90%;
}
.manage-popup ul li a#invitation 
{
 	color: #48545e !important;
    display: block !important;
    padding: 4px 7px;
    text-decoration: none !important;
	margin:0px;
}
.manage-popup ul li a#invitation:hover
{
	color: #fff !important;
}
.quickview-outer {
    top: 51px;
}
.popupArrow{
	padding-left:108px;
}
</style>
<input type="hidden" name="jobId" id="jobId" value="<?php echo $this->jobDetail->getId();?>" />
<!-- Content Right Right Starts -->
<div class="content-right-right">
	<div class="job-application-outer">
		<div class="job-application-hdr1">
			<div class="job-application-hdr1lt">
				<h4>
<?php 			
				echo $this->jobDetail->getJob_title().",";
				if( $this->jobDetail->getCompany() )
				{
					echo " ".$this->jobDetail->getCompany()->getName().",";
				}
				echo " ".\Extended\job::getCityStateCountryOfAJob( $this->jobDetail->getId() );
?>
				</h4>
			</div>
			<?php 
			if( $this->paginator->getTotalItemCount() )
			{
			?>
				<div class="job-application-hdr1rt">
					<div class="fr  text-grey3">
<?php
						echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
?>							
					</div>
				</div>
			<?php 
			} 
			?>
		</div>
		<div class="job-application-hdr2">
			<div class="job-application-hdr2lt">
				<h4>
					<a class="selected" href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.'job/received-applications/id/'.$this->jobDetail->getId();?>" id="cntApplicant"><?php echo \Extended\job_applications::countApplicants($this->jobDetail->getId());?> Applications</a> | 
					<a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.'job/shortlisted-applications/id/'.$this->jobDetail->getId();?>" id="cntCandidate"><?php echo \Extended\job_applications::countCandidates($this->jobDetail->getId());?> Shortlisted</a> | 
					<a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.'job/job-detail/job_id/'.$this->jobDetail->getId().'/section/applications';?>">Job Detail</a>
				</h4>
			</div>
			<?php 
			if( $this->paginator->getTotalItemCount() )
			{
			?>
			<div class="job-application-hdr2rt">
				<a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.'job/received-applications/id/'.$this->jobDetail->getId().'/order/'.$this->orderby;?>">Sort by date in <?php echo $this->order;?></a> 

			</div>
			<?php 
			}
			?>
		</div>
	</div>
	<div class="white-outer2">
		<?php 
			if( $this->paginator->getTotalItemCount() )
			{
				
				foreach($this->paginator as $applicants){
					//Zend_Debug::dump($applicants); 
				?>
				<div class="job-application-col1 job-application-col1_<?php echo $applicants["ilookUser"]["id"];?>" style="position:relative;">
					<div class="job-application-col1-img" style="position:relative;">
<?php 
						
						//Added by hkau5 {parameter_json}
						$parameter_json = "{'user_id':".$applicants["ilookUser"]["id"]."}";
						
						//Showing default profile picture and no short profile when user is in blocked user list or user account is closed.
						if( $this->blocked_profiles && is_object($applicants["ilookUser"]['account_closed_on']))
						{
							$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3, false, $this->blocked_profiles );
							echo'<img src="'.$imgPath.'" alt="" />';
						}
						//If either blocked or account closed then no short profile view required as well as show default picture. 
						else if ($this->blocked_profiles || is_object($applicants["ilookUser"]['account_closed_on']))
						{
							//case1 => If User is in blocked list.
							if($this->blocked_profiles)
							{
								if( in_array($applicants["ilookUser"]["id"], $this->blocked_profiles ))
								{
									$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3, false, $this->blocked_profiles );
									echo'<img src="'.$imgPath.'" alt="" />';
								}
								else
								{
									$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3);
									echo'<a style="display:block;" href="javascript:;" id="'.$applicants["ilookUser"]["id"].'" onclick="getShortProfile(this,'.$parameter_json.')" disable-border="1">	';
									echo'<img src="'.$imgPath.'" alt="" />';
									echo'</a>';
								}
							}
							//Case 2 => If user's account is closed.
							else if(is_object($applicants["ilookUser"]['account_closed_on']))
							{
								$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3, false, $this->blocked_profiles );
								echo'<img src="'.$imgPath.'" alt="" />';
							}
							else 
							{
								$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3);
								echo'<a style="display:block;" href="javascript:;" id="'.$applicants["ilookUser"]["id"].'" onclick="getShortProfile(this,'.$parameter_json.')" disable-border="1">	';
								echo'<img src="'.$imgPath.'" alt="" />';
								echo'</a>';
							}
						}
						
						else
						{
							$imgPath = Helper_common::getUserProfessionalPhoto($applicants["ilookUser"]["id"], 3);
							echo'<a style="display:block;" href="javascript:;" id="'.$applicants["ilookUser"]["id"].'" onclick="getShortProfile(this,'.$parameter_json.')" disable-border="1">	';
							echo'<img src="'.$imgPath.'" alt="" />';
							echo'</a>';
						}	
						
						
						
							?>
							<!-- Short profile view popup starts -->
							<div id="view-outer_<?php echo $applicants["ilookUser"]["id"];?>" class="quickview-outer" popup-state="off" style="display:none;">
								<div class="popupArrow">
									<img width="36" height="22" src="<?php echo IMAGE_PATH;?>/arrow-purple2.png">
								</div>
								<div id="view_<?php echo $applicants["ilookUser"]["id"];?>" class="quickview"> </div>
							</div>
							<!-- Short profile view popup ends -->
						</div>
					<div class="job-application-col1-mid">
						<h4><?php echo $applicants["ilookUser"]["firstname"]." ".$applicants["ilookUser"]["lastname"]; ?></h4>
						<h5>
						<?php
							$user_prof_info = Helper_common::getUserProfessionalInfo( $applicants["ilookUser"]["id"] );
							if( $applicants["ilookUser"]["user_type"] == \Extended\ilook_user::USER_TYPE_EMPLOYED || $applicants["ilookUser"]["user_type"] == \Extended\ilook_user::USER_TYPE_JOB_SEEKER )
							{
								if( $user_prof_info )
								{
									echo $user_prof_info[0]." at ".$user_prof_info[1];
								}
							}
						?>
						</h5>
						<p>Email : <?php echo $applicants["ilookUser"]["email"];?></p>
						<p>Ph : <?php echo $applicants["ilookUser"]["phone"];?></p>
						<p>Description: <?php echo $applicants["applicant_msg"];?></p>
					</div>
		
					<div class="job-application-col1-rt">
						<div class="job-application-col1-rt-text"><?php echo $applicants['created_at']->format("M d, Y");?></div>
						<div class="job-application-col1-rt-btn-outer">
							<input value="Manage  v" type="button" class="manageOptions" />
							<div class="manage-popup" style="display:none;">
		                  		<ul>
		                    		<div class="arrow">
										<img width="18" height="11" src="<?php echo IMAGE_PATH;?>/arrow-up-blue2.png" alt="">
									</div>
		                    		<li>
		                    			<a target="_blank" href="<?php echo PUBLIC_PATH;?>/jobs/cv/<?php echo $applicants['cv_attached'];?>">Download CV</a>
		                    		</li>
			                        <?php 
			                        if($applicants['cover_letter_attached']!="")
			                        {
			                        ?>
			                        	<li><a target="_blank" href="<?php echo PUBLIC_PATH;?>/jobs/cover_letter/<?php echo $applicants['cover_letter_attached'];?>">Cover Letter</a></li>
			                        <?php 
			                        }
		                        	if($applicants['is_shortlist']==true)
		                        	{
		                        	?>
		                        	<li>
		                        		<a class="shortlisted" rel="<?php echo $applicants["ilookUser"]["id"];?>" id="shortlistStatus_<?php echo $applicants["ilookUser"]["id"];?>" href="javascript:;">Remove from Shortlist</a>
		                        	</li>
		                        	<?php 
		                        	}
		                        	else
		                        	{
		                        	?>
			                        <li>
			                        	<a class="shortlist" rel="<?php echo $applicants["ilookUser"]["id"];?>" id="shortlistStatus_<?php echo $applicants["ilookUser"]["id"];?>" href="javascript:;">Shortlist</a>
			                        </li>
		                        	<?php 		
		                        	}
		                        ?>
		                        <li><a class="deleteShortlist" rel="<?php echo $applicants["ilookUser"]["id"];?>" id="deleteShortlist_<?php echo $applicants["ilookUser"]["id"];?>" href="javascript:;">Delete</a></li>

		                    </ul>
		                  </div>
						</div>
					</div>
				</div>
				<?php 
				}
			}
			else
			{
				echo '<div class="noRecFound">No Applicant Found!</div>';
			}
		?>
	</div>
</div>
<!-- Content Right Right Ends -->