<?php
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/forgot_password.css" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/forgot_password.js" );
?>

<!-- Header Ends -->
<!-- Content Starts -->
<form id="forgotPwd" name="forgotPwd">
	<div class="bot-link-content">
		<div class="bot-link-content-data">
			<div class="create-pwd font-change" >
		   		<h3 class="font-change">Forgot Your login Details ?</h3>
		   		<h4 class="font-change">Enter your email address below and we will send you a link to change your password</h4>
				<div class="formbox-create-pwd font-change">
					<table>
						<tr>
							<td>
								<div class="fieldbox-emaiaddress font-change">
									<label>Email Address :</label>
									<div class="inputfieldbox-emailaddress font-change">
										<input name="emailForgot" id="emailForgot" maxlength="70" type="text" class="input-emailaddress" />
									</div>
								</div>
							</td>
							<td>
								<div id = "forgot_email_submit_div" >
									<input name="forgot_email_submit" id="forgot_email_submit" type="button" class="btn-save" value="SEND" style="padding-bottom: 3px; padding-top: 3px; height: 33px; margin-top: 18px;" />
								</div>
							</td>
							<td>
								<span id = "email_validate_image"></span>
							</td>
						</tr>
						<tr>
							<td>
								<div id = "emailExistsMsg">
									
								</div>
							</td>		
							<td>
							</td>		
							<td>
							</td>		
						</tr>
					</table>
				</div>
			</div>
		</div>
	</div>
</form>
<!-- Content Ends -->
