     <div>
        <a href="http://phpstg.seasiaconsulting.com:9040/ilook/zend-ilook/login/withfacebook">Login with Facebook</a>
      </div>
      <div style="margin-left:200px;">
        <a href="http://phpstg.seasiaconsulting.com:9040/ilook/zend-ilook/login/withtwitter">Login with Twitter</a>
      </div>
      <div>
      <a href="http://www.facebook.com/share.php?u=<full page url to share" onClick="return fbs_click(400, 300)" target="_blank" title="Share This on Facebook">Profile share with facebook</a>
      </div>
      <div style="margin-left:200px;">
      <a class="twitter" onclick="twitterwindow('http://twitter.com/share?text=This%20is%20so%20easy')" href="#">Profile share with twitter</a>
      </div>