 <?php 
 $this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/resetpassword.js" );
 ?>
<!-- Content Starts -->

<form id="rpform" name="rpform" action="" method="post">
<div class="bot-link-content">
	<div class="bot-link-content-data">
		<div class="create-pwd">
	   		<h3>Create New Password</h3>
	   		<p>Passwords are case-sensitive and must be at least 8 characters long. A good password should contain a mix of capital and lower-case
				letters, numbers and symbols</p>
				<div class="formbox-create-pwd">
					<div class="fieldbox-create-pwd">
						<label>New Password :</label>
						<div class="inputfieldbox-passwd">
						<input name="pwd" id="pwd" type="password" class="input-pwd" />
						</div>
					</div>
					<div class="fieldbox-create-pwd">
						<label>Re enter New Password :</label>
						<div class="inputfieldbox-passwd">
						<input name="cpwd" id="cpwd" type="password" class="input-pwd" />
						</div>
					</div>
					
					<div class="inputfieldbox-passwd">
					<input type="submit" value="Save" id="rpsubmit" name="rpsubmit" class="btn-save">	
  					<a href="/<?php echo PROJECT_NAME; ?>"><input name="cancel" type="button" class="btn-cancel" id="cancel" value="Cancel" /></a>
</div>
					
				</div>
			</div>
	   </div>
 </div>
 </form>
    <!-- Content Ends -->