<?php 
$this->headTitle()->prepend('About Us');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
<style>
/* .bot-link-content-data-right .col1 p{ font-size:16px;} */
.bot-link-content-data-left {
     transform: rotate(-90deg); 
 	-webkit-transform: rotate(-90deg); 
 	-moz-transform: rotate(-90deg); 
 	-ms-transform: rotate(-90deg);
 -o-transform: rotate(-90deg);
 filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
}
</style>
    <!-- Content Starts -->
    <div class="bot-link-content">

    <div class="bot-link-content-data">
    	<div class="bot-link-content-data-left text-purple2">About Us</div>
        <div class="bot-link-content-data-right">
        
        	<div class="bot-link-content-hdr"><img src="<?php echo IMAGE_PATH?>/ilook-2.png" /></div>
        	<div class="col1">
        	<ul class="col1-ul">
				<li>iLook is a Social Networking Website for Employed, Job Seekers, Recruiters, Business People, Students and Companies. </li>
           		<li>iLook is a platform that helps people to build their professional network, to improve their Career prospects, Job searches, Talent searches, Business development and Product promotions.</li>
           		<li>iLook was founded by Saravana Rajan P in August 2012 and launched in August 2015.</li>
           		<li>iLook is a product of i-Sjn Solutions Ltd, UK.</li>
			</ul>
			
<!-- 			<p>Lloyds Banking Group plc. Registered Office: The Mound, Edinburgh EH1 1YZ. Registered in Scotland no. SC95000. Telephone: 0131 225 4555. Lloyds Bank plc. Registered Office: 25 Gresham Street, London EC2V 7HN. Registered in England and Wales no. 2065. Telephone 0207626 1500. Bank of Scotland plc. Registered Office: The Mound, Edinburgh EH1 1YZ. Registered in Scotland no. SC327000. Telephone: 08457 21 31 41. Cheltenham & Gloucester plc. Registered Office: Barnett Way, Gloucester GL4 3RL. Registered in England and Wales 2299428. Telephone: 0845 603 1637</p> -->
<!-- 			<p>Lloyds Bank plc, Bank of Scotland plc are authorised by the Prudential Regulation Authority and regulated by the Financial Conduct Authority and Prudential Regulation Authority.</p> -->
<!-- 			<p>Cheltenham & Gloucester plc is authorised and regulated by the Financial Conduct Authority.</p> -->
<!-- 			<p>Halifax is a division of Bank of Scotland plc. Cheltenham & Gloucester Savings is a division of Lloyds Bank plc.</p> -->
<!-- 			<p>HBOS plc. Registered Office: The Mound, Edinburgh EH1 1YZ. Registered in Scotland no. SC218813.</p> -->
<!-- 			<p>This e-mail (including any attachments) is private and confidential and may contain privileged material. If you have received this e-mail in error, please notify the sender and delete it (including any attachments) immediately. You must not copy, distribute, disclose or use any of the information in it or any attachments. Telephone calls may be monitored or recorded.</p> -->
        	
<!-- 			<p>iLook is a product of i-Sjn Solutions Ltd, a company registered and based in UK.</p> -->
<!-- 			<p>The company came up with an idea of developing a Professional Networking website in August 2012 and got it launched in August 2015.</p> -->
<!-- 			<p>iLook is a Social networking website that aims to help people to build their professional network, to improve their Career prospects, Job searches, Skilled people searches, Business development, Product promotions, to stay in touch with their network and so on.</p> -->
<!-- 			<p>The Company has a team of 25 young and energetic people who have put their efforts to develop fine quality product.</p> -->
<!-- 			<p>iLook has been designed to make the User interface very simple, clear and user friendly.</p> -->
			
           </div>

                   
        </div>
    	
    </div>
  </div>
    <!-- Content Ends -->