<?php 
$this->headTitle()->prepend('Cookies');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
<style>
.bot-link-content-data-left {
     transform: rotate(-90deg); 
 	-webkit-transform: rotate(-90deg); 
 	-moz-transform: rotate(-90deg); 
 	-ms-transform: rotate(-90deg);
 -o-transform: rotate(-90deg);
 filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
}
</style>
    <!-- Content Starts -->
    <div class="bot-link-content">

    <div class="bot-link-content-data">
    	<div class="bot-link-content-data-left text-purple2">Cookies</div>
        <div class="bot-link-content-data-right">
        
        	<div class="bot-link-content-hdr"><img src="<?php echo IMAGE_PATH?>/ilook-2.png"/></div>
       
       		
       		
        <!-- Col 1 -->
        	<div class="col1">
            	
                <p class="text-purple2">
                Like nearly all websites, our Website uses cookies in order to provide you with a more personalised web service. We are unable to operate all of the functionality of the Website without using cookies. </p>
                <p class="text-purple2">A cookie is a text only string of information that we pass to your computer's hard disk through your web browser so that the Website can remember who you are. </p>
                <p class="text-purple2">Cookies cannot be used by themselves to identify you. A cookie will typically contain the name of the domain from which the cookie has come, the 'lifetime' of the cookie, and a value, usually a randomly generated unique number. For more information about cookies, please see <a target = '_blank' href = 'http://www.allaboutcookies.org'>www.allaboutcookies.org</a>. </p>
	
	    <p class="text-purple2">More specifically we use the following cookies which carry out the functions described:</p>
		<p>	
		<table cellpadding="0" cellspacing="0" border="0" style="width: 94%;">
			<tr>
				<th style="background:#d8d8d8; padding:5px 0 5px 0; ">Cookie</th>
				<th style="background:#d8d8d8; padding:5px 0 5px 10px;">Use</th>
			</tr>
			<tr>
				<td style="background:#f1f1f1; padding:5px 0 5px 5px;; border-right:1px solid #ddd;">__utma</td>
				<td style="background:#f1f1f1; padding:5px 0 5px 10px;">This is a Google Analytics cookie and tracks the number of times you have visited the Website.</td>
			</tr>
			
			<tr>
				<td style="background:#f1f1f1; padding:5px 0 5px 5px;; border-right:1px solid #ddd;">__utmb and  __utmc</td>
				<td style="background:#f1f1f1; padding:5px 0 5px 10px;">This is another Google Analytics cookie and acts to calculate how long you have spent on the Website in each session.</td>
			</tr>
			
			<tr>
				<td style="background:#f1f1f1; padding:5px 0 5px 5px;; border-right:1px solid #ddd;">__utmz</td>
				<td style="background:#f1f1f1; padding:5px 0 5px 10px;">This Google Analytics cookie tracks what search engine you have visited the site from and which search terms you used to find the Website.</td>
			</tr>
			
			<tr>
				<td style="background:#f1f1f1; padding:5px 0 5px 5px;; border-right:1px solid #ddd;">__utmv and __utmx</td>
				<td style="background:#f1f1f1; padding:5px 0 5px 10px;">These are Google Analytics cookies.</td>
			</tr>
			<tr>
				<td style="background:#f1f1f1; padding:5px 0 5px 5px;; border-right:1px solid #ddd;">ilook_user_email and ilook_user_password</td>
				<td style="background:#f1f1f1; padding:5px 0 5px 10px;">These cookies stores your email ID and password when you choose keep me logged in option.</td>
			</tr>
		</table>
		</p>	
				
		<p class="text-purple2">Under new rules, we are required to obtain your consent to use cookies. If you continue to use the Website having had the opportunity to read this policy and our privacy and data protection policy then we assume you are happy for us to use the cookies described above.</p>		
		<p class="text-purple2">The cookies we use are designed to help you get the most from our website but if you do not wish to receive cookies you can easily modify your web browser to refuse cookies, or to notify you when you receive a new cookie. To change your settings for your web browser you will need to go to your advanced preferences.  However, you may not be able to use all the interactive features of our site if cookies are disabled, and so in order to enjoy the Website to the full, we recommend that you leave them switched on. For further instructions on how to stop cookies being installed on your browser, please see: <a target = '_blank' href = 'http://www.allaboutcookies.org/manage-cookies'>www.allaboutcookies.org/manage-cookies</a>. </p>		
				
				</div>
            <!-- Col 1 -->
        </div>
    	
    </div>
  </div>
    <!-- Content Ends -->