<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
<div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Jobs</li>
                    </ul>
                </div>
                <h3>Jobs</h3>
                <p>Job Section connects the recruiters with the job seekers, thus giving you an edge above the others.</p>
            	<h4>How do I Save Job  Search? </h4>
              <p>This  allows you to save a particular search and view the jobs related to that search  in the saved job searches section, thus customizing the job search, you will  also be able to receive alerts based upon the saved search. You will also  receive an email notification to match with your saved job criteria. You will  be able to view the save search option, by following the below steps:
                </p>
              </p>
                <p>1.  Click on Jobs in the Menu<br />
                </p>
                <p>2.  Click on Search Jobs in the middle navigation<br />
                  </p>
                <p>3.  Click on Advance Search, at the bottom you will be displayed with Save Search  option<br />
                  </p>
                <p>4.  You will be required to enter the below fields:</p>
                <div class="search">
                <ul>
                  <li><strong>Saved Search Name: </strong>Enter the search name, to be saved in this column.<strong></strong></li>
                  <li><strong>Receive Alerts: </strong>Select on how often you want to receive alerts &#45; <strong> </strong>Daily, Weekly and Monthly<strong></strong></li>
                  <li><strong>Email:</strong> Enter  the email on which you wish to receive alerts.</li>
                </ul>
                </div>
                <p>5.  Click Save</p>
                <p>Or</p>
                <p>1.  Select the jobs option from the dropdown, corresponding to the advanced option,  towards the top right corner of the page<br />
                  </p>
                <p>2.  Enter the job search <br />
                  </p>
                <p>3.  Click on Advance Search, at the bottom you will be displayed with Save Search  option<br />
                  </p>
                <p>4.  You will be required to enter the below fields:</p>
               <div class="search">
                <ul>
                  <li><strong>Saved Search Name: </strong>Enter the search name, to be saved in this column.<strong></strong></li>
                  <li><strong>Receive Alerts: </strong>Select on how often you want to receive alerts &#45; <strong></strong>Daily, Weekly and Monthly<strong></strong></li>
                  <li><strong>Email:</strong> Enter  the email on which you wish to receive alerts.</li>
                </ul>
              </div>
                <p>5. Click Save</p>
                <h4>How do I receive Job  alerts?</h4>
                <p>You  will be able to receive job alerts, corresponding to the jobs saved search, you  can save the search as follows to receive job alerts:</p>
                <p>1. Click on Jobs in the Menu<br />
                  </p>
                <p>2. Click on Search Jobs in the middle navigation<br />
                  </p>
                <p>3. Click on Advance Search, at the bottom you will be displayed with Save Search  option<br />
                  </p>
                <p>4. You will be required to enter the below fields:</p>
                <div class="search">
                <ul>
                  <li><strong>Saved Search Name: </strong>Enter the search name, to be saved in this column.<strong></strong></li>
                  <li><strong>Receive Alerts: </strong>Select on how often you want to receive alerts &#45; <strong> </strong>Daily, Weekly and Monthly<strong></strong></li>
                  <li><strong>Email:</strong> Enter  the email on which you wish to receive alerts.</li>
                </ul>
              </div>
                <p>5.  Click Save</p>
              <p>Or</p>
                <p>1.  Select the jobs option from the dropdown, corresponding to the advanced option,  towards the top right corner of the page<br />
                  </p>
                <p>2.  Enter the job search <br />
                  </p>
                <p>3.  Click on Advance Search, at the bottom you will be displayed with Save Search  option<br />
                  </p>
                <p>4.  You will be required to enter the below fields:</p>
                <div class="search">
                <ul>
                  <li><strong>Saved Search Name: </strong>Enter the search name, to be saved in this column.<strong></strong></li>
                  <li><strong>Receive Alerts: </strong>Select on how often you want to receive alerts &#45; <strong> </strong>Daily, Weekly and Monthly<strong></strong></li>
                  <li><strong>Email:</strong> Enter  the email on which you wish to receive alerts.</li>
                </ul>
              </div>
                <p>5.  Click Save</p>
                <p><strong>Note:</strong> You will have to save search to receive alerts</p>
                <h4>How do I view  Recommended Jobs?</h4>
                  <p>You  will be able to view the jobs recommended to you by iLook Team in this section,  the jobs will be displayed to you, based upon your country, in case you want  specific job alerts then you can set an alert from the <strong><u>save job search</u></strong> section.</p>
                  </p>
                <p>You  can view this section:<br />
                  </p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on recommended jobs, in the middle navigation<br />
                  </p>
                <p>3.  You will be displayed with the Logo, Job title, company, location and status of  the job and the day on which the job was posted<br />
                  </p>
                <p>4.  You will be able to save job by clicking on the save job option towards the  left bottom of the job.<br />
                  </p>
                <p>5.  You can also apply by clicking on <strong><u>Quick Apply</u></strong></p>
                <p><strong>Note:</strong> On clicking the Job Title, you will be navigated to the detailed  screen from where you will be able to apply, save and share the job.</p>
             
                <h4>How Do I save Job?</h4>
                <p>You  will be able to save job, by following the below steps:<br />
                  </p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on recommended jobs, in the middle navigation<br />
                  </p>
                <p>3.  You will be displayed with the Save option towards the left bottom corner of  the job.<br />
                  </p>
                <p>4.  Click Save</p>
                <p>Or<br />
                  On  clicking the Job Title, you will be navigated to the detailed screen from where  you will be able to save the job.</p>
             
                <h4>How Do I apply for the Job?</h4>
                <p>You  will be able to apply for the job, by following the below steps:<br />
                  </p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on recommended jobs, in the middle navigation<br />
                  </p>
                <p>3.  Click on Quick Apply, the details will expand<br />
                  </p>
                <p>4.  Click on Browse, corresponding to Applicant CV, to upload your CV. Clicking  Browse will display a window, from where you will be able to upload your CV, the  screen will display the name of your uploaded file.<br />
                </p>
                <p>5.  Click on Browse, corresponding to Applicant Cover Letter, to upload Cover  Letter. Clicking Browse will display a window, from where you will be able to  upload Cover Letter, the screen will display the name of your uploaded file.<br />
                </p>
                <p>6.  You can add description, if required.<br />
                </p>
                <p>7.  Click Apply<br />
                </p>
                <p>8.  You will be displayed with Applied towards the right bottom of the job.</p>
                <p><strong>Note:</strong> You can also apply for the job, from the detailed screen, you will be  navigated to the detailed screen by clicking on the Job Title. Clicking apply on  detailed screen, will navigate you to the apply screen.</p>
                <h4>How the system displays Recommended  Jobs?</h4>
                <p>The system recommends you  jobs, based upon the country, you are currently living in.<br />
                  </p>
                <p><strong>For Example:</strong> In you are living in United Kingdom, you will be displayed with all the jobs in  United Kingdom, in the recommended jobs section</p>
                <h4>How do I search Jobs?</h4>
                <p>Refer to <strong><u>search jobs section</u></strong></p>
                <h4>How Do I view Saved Job searches?</h4>
                <p>You  can view the saved job searches in this section; this enables you to view all  the jobs, corresponding to a particular search saved previously, you will be  able to view all the saved searches in this section, you can view the saved  searches:</p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on Saved job Searches, in the middle navigation, the area will expand to  display all the saved jobs searches<br />
                  </p>
                <p>3.  Click on any saved search, corresponding to which you wish to view the jobs<br />
                  </p>
              <p>4. You will be displayed with all the jobs, corresponding to the saved search</p>
                <p><strong>Note: </strong>You will be displayed with the Logo, Job title, company name, location,  job type; you can also save and quick apply for the job from this screen. <br />
                You  will also be able to save search from this screen</p>
                <h4>How Do I rename the Saved Job searches?</h4>
                  <p>You will be able to rename  the saved searches, by following the below steps:<br />
                  </p>
                  <p>1. Click on Jobs in Menu<br />
                  </p>
                  <p>2. Click on                                                                        icon, corresponding to  the saved jobs searches, heading in the middle navigation section<br />
                  </p>
                  <p>3. You will be displayed a  pop up with the saved search jobs listing.<br />
                  </p>
                  <p>4. Double Click, on the name  of the saved search, which you wish to edit<br />
                  </p>
                  <p>5. it appears in the editable  mode, edit the name<br />
                  </p>
                  <p>6. Click on update
                  </p>
                  </p>
                <h4>How Do I delete the Saved Job searches?</h4>
                  <p>You will be able to delete  the saved searches, by following the below steps:<br />
                  </p>
                  <p>1. Click on Jobs in Menu<br />
                  </p>
                  <p>2. Click on icon, corresponding to  the saved jobs searches, heading in the middle navigation section<br />
                  </p>
                  <p>3. You will be displayed a  pop up with the saved search jobs listing.<br />
                  </p>
                  <p>4. Click on the cross icon
                  </p>
                  </p>
                <h4>How do I View Job Applications?</h4>
                  This section enables you to  view jobs for which you have applied previously, you will be able to view job  applications, by following the below steps:</p>
                <p>&nbsp;</p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on Applications<br />
                  </p>
                <p>3.  You will be displayed with a list of all the jobs, you have applied previously,  along with the date on which they were applied</p>
                <p><strong>Note:</strong> Clicking the Job Title, will navigate you to the detailed page where  in, you will be displayed with the job details, status whether applied or not  and you will be able to share the job with your links.</p>
                <h4>How do I share a job with my links?</h4>
                <p>This section enables you to  share jobs with your links, thus assisting your links in finding jobs according  to their skills, you will be able to share the job with your links:<br />
                  </p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  You will be displayed with the recommended jobs by default, click on the Job  Title<br />
                  </p>
                <p>3.  Click Share<br />
                  </p>
                <p>4.  You will be displayed with a pop up, from where you can either select all the  links to share the job, by clicking on the Select All option or you can select  the link specifically<br />
                </p>
                <p>5.  Click Add</p>
                <p><strong>Note:</strong> This option will only be visible on the detailed screen of the job  posting, you can navigate to the detailed screen by clicking on the Job title  on any screen in the jobs section.<br />
                  </p>
                <p>The  user will be able to view the shared job link, in Inbox, in <strong><u>Job  Invitations Requests</u></strong>, along with the details of the job</p>
                <h4>How do I view saved Jobs?</h4>
                  <p>You can save jobs from search  results and recommended job, and view them later in the saved Jobs page. This  helps you keep a track of the jobs you're interested in:
                  </p>
                  </p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Click on Saved Jobs, you will be displayed a listing of all the saved Jobs,  along with the date on which the job was saved</p>
                <p><strong>Note: </strong>You can navigate to the detailed screen by clicking the Job Title, you  will be able to un save, apply and share.<strong> </strong>The jobs applied will not have an option to save them.<strong></strong></p>
                <h4>How do I un save job from saved Job?</h4>
                  <p>You can un save jobs from  search results and recommended job, you will be able to un save job, by following  the below steps:
                  </p>
                  </p>
                <p>&nbsp;</p>
                <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2.  Move your cursor, over the Job saved option, provided towards the left bottom  corner of the saved jobs, it will display un save on hovering the cursor, click  un save </p>
                <p><strong>Note: </strong>You can navigate to the detailed screen by clicking the Job Title, you  will be able to un save, apply and share. Only the saved jobs, will have an  option to unsave.<strong></strong></p>
                <h4>How do I post a job?</h4>
                <p>You can post a job in iLook,  by following the below steps:</p>
                <p>1.  1. Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2. Click on Post a Job, under  the Job Poster heading<br />
                  </p>
                <p>3. You are required to enter  the fields displayed<br />
                  </p>
              <p>4. Click Post</p>
                <p>You will also be able to <strong><u>Preview your  post </u></strong>, by following the below steps:<br />
                  </p>
                <p>1. Click on the Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                <p>2. Click on Post a Job, under  the Job Poster heading<br />
                  </p>
                <p>3. Click on Preview</p>
                <h4>How do I view the status of the Job?</h4>
                  <p>You will be displayed with  three status of any job posted &#45; Active, Expired and closed
                  </p>
                  </p>
                <h4>How do I view jobs posted?</h4>
                  <p>You can view the jobs posted in  this section, by following the below steps:<br />
                  </p>
                  <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                  <p>2. Click on Jobs Posted, under  the Job Poster heading, the area will expand to display all the jobs &#45; Active,  Expired and Closed<br />
                  </p>
                  <p>3. Select the Job
                  </p>
                  </p>
                <p>&nbsp;</p>
              <h4>How do I view active jobs?</h4>
                  
                  <p>You will be displayed with  the jobs, you have posted in this section, the jobs which are in the active  state will be displayed, you can view active jobs, by following the below  steps:<br />
                  </p>
                  <p>1.  Click on Jobs in the <strong><u>Menu</u></strong><br />
                  </p>
                  <p>2. Click on Jobs Posted, under  the Job Poster heading, the area will expand to display all the jobs<br />
                  </p>
                  <p>3. Click on Active Jobs<br />
                  </p>
                  <p>4.  You will be able to view the all the active jobs in a grid view, along with the  Applicants, Shortlisted, company name and location etc.
                  </p>
                  </p>
                <p>You  can <strong><u>Close  the Job</u></strong>, this allows you to remove the job from iLook database.  Job Candidates will no longer be able to view and apply for the jobs, but you  will still be able to review your job status and the applications you have  received, by:</p>
                <p>1.  Click on Active Jobs<br />
                  </p>
                <p>2.  Select Close from the actions dropdown</p>
                <p>You  can <strong><u>Renew  the Job</u></strong>, this allows you to extend the expiry date of the job, ,  by following the below steps:</p>
                <p>1.  Click on Active Jobs<br />
                  </p>
                <p>2.  Select Renew from the actions dropdown<br />
                  </p>
                <p>3.  You will be displayed with a pop up, where in you can select a future date for  the job to expire, the job details will remain the same but the expiry date is  extended</p>
                <p>Or</p>
                <p>1.  Click on Expired jobs<br />
                  </p>
                <p>2.  Select Renew from the actions dropdown<br />
                  </p>
                <p>3.  You will be displayed with a pop up, where in you can select a future date for  the job to expire, the job details will remain the same but the expiry date is  extended</p>
                <p>&nbsp;</p>
                <p>You  can <strong><u>Share  the Job</u></strong>, with your links, , by following the below steps:</p>
                <p>1.  Click on Active Jobs<br />
                  </p>
                <p>2.  Select Renew from the actions dropdown<br />
                  </p>
                <p>3.  You will be displayed with a pop up, from where you can either select all the  links to share the job, by clicking on the Select All option or you can select  the link specifically<br />
                  </p>
                <p>5.  Click Add</p>
                <p>You  can <strong><u>add  comments to the job</u></strong> for your reference, the comments will be displayed  corresponding to every job:</p>
                <p>1.  Click on Active Jobs<br />
                  </p>
                <p>2.  Click      icon <br />
                  </p>
                <p>3.  Enter the comments<br />
                  </p>
                <p>4.  Click Save </p>
                <p>You  can also discard the comments, by clicking the discard option</p>
                <p><strong>Note:</strong> The Job Title will be clickable, you will be able to <strong><u>manage the  jobs</u></strong>, from the detailed screen.<br />
                  </p>
                <p><strong>Note:</strong> You can delete all the jobs by clicking the select all option in the  listing, towards the top left corner. You can also delete specific jobs by  clicking on the check box corresponding to that job and selecting the delete option  from the top right corner of the page.</p>
                <p>&nbsp;</p>
                <h4>How do I view applicants for the jobs?</h4>
                <p>You will be able to view the  applicants for the job, by following the below steps:<br />
              </p>
                <p>1.  Click on Active Jobs<br />
              </p>
                <p>2.  Click on the Job Title<br />
              </p>
                <p>3.  By default, applications will be displayed or you can also click on  applications at the top bar<br />
              </p>
                <p>4.  Click Manage, towards the right hand side<br />
              </p>
                <p>5.  Click Download CV, to <strong><u>download the CV</u></strong><br />
              </p>
                <p>6.  Click Cover Letter, to <strong><u>download the Cover Letter</u></strong><br />
              </p>
                <p>7.  Click Shortlist, to <strong><u>shortlist the candidate</u></strong><br />
              </p>
                <p>8.  Click delete, to delete <strong><u>the candidate</u></strong><br />
              </p>
                <p>Or <br />
              </p>
                <p>You  can also delete the job from the <strong><u>Closed Jobs</u></strong> section<br />
                  </p>
                <p><strong>Note:</strong> You will be able to sort the applications by date</p>
                <h4>How do I view the shortlisted candidates  for the job?</h4>
                  <p>You will be able to view the  candidates shortlisted for the job, by following the below steps:<br />
                  </p>
                  <p>1.  Click on Active Jobs<br />
                  </p>
                  <p>2.  Click on the Job Title<br />
                  </p>
                  <p>3.  Select Shortlisted heading from the top bar
                  </p>
                  </p>
                <h4>How do I view the job details?</h4>
                  <p>You will be able to view the  candidates shortlisted for the job, by following the below steps:<br />
                  </p>
                  <p>1.  Click on Active Jobs<br />
                  </p>
                  <p>2.  Click on the Job Title<br />
                  </p>
                  <p>3.  Select Job Details heading from the top bar
                  </p>
                  </p>
                <h4>How do I view closed jobs?</h4>
                  <p>Once  you choose to close the job, the candidates will no longer be able to view and  apply for the job, but you will still be able to review your job status and any  applications you have received. You can close job, by following the below  steps:<br />
                  </p>
                  <p>1.  Click on Jobs, in the Menu<br />
                  </p>
                  <p>2.  Click on Jobs Posted in the middle navigation section<br />
                  </p>
                  <p>3.  Select Closed Jobs, you will be able to view the number of applicants,  shortlisted, company name, location, expiry date and comments<br />
                  </p>
                  <p>4.  You can delete the job, by selecting the delete option from the actions  dropdown
                  </p>
                  </p>
                <p><strong>Note: </strong>The job title will be clickable; you will be able to view the  applicants, shortlisted candidates and job details, on clicking the same.<br />
                  You  can delete all the jobs by clicking the select all option in the listing, towards  the top left corner. You can also delete specific jobs by clicking on the check  box corresponding to that job and selecting the delete option from the top  right corner of the page.</p>
                <h4>How do I view expired jobs?</h4>
                  <p>You  will be able to view the expired Jobs in this section, you will be able to  close and renew the job from this section, by following the below steps:
                  </p>
                  </p>
                <h4>How do I close jobs?</h4>
                  <p>1.  Click on Jobs, in the Menu<br />
                  </p>
                  <p>2.  Click on Jobs Posted in the middle navigation section<br />
                  </p>
                  <p>3.  Select Expired Jobs, you will be able to view the number of applicants,  shortlisted, company name, location, expiry date and comments<br />
                  </p>
                  <p>4.  You can close the job, by selecting the close option from the actions dropdown,  this will remove the job from iLook database, job candidates will no longer be  able to view and apply for this job, but you will still be able to review your  job status and the applications you have received.
                  </p>
                  </p>
                <p>For  renew, refer to <strong><u>How Do I Renew the Job?</u></strong> Section.</p>
                <p><strong>Note:</strong> You can delete all the jobs by clicking the select all option in the  listing, towards the top left corner. You can also delete specific jobs by  clicking on the check box corresponding to that job and selecting the delete  option from the top right corner of the page.</p>
            </div>	