<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
            <div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Dashboard</li>
                    </ul>
                </div>
            	<h3>Dashboard </h3>
              <p>Dashboard is the default landing  pager for every user. You can navigate to this page from any page of the ilook  simply by clicking the heading Dashboard in the left side Black Bar. <br />
              </p>
              <p>This is the Wall of constantly  updating stories, in the middle of the page, which includes status updates  which can be general update, knowledge sharing or a simple job search/ job  opening post, and also sharing the links, URLs.. Other users can OK, comment  and share your stories to their wall.<br />
              </p>
              <p>The stories appear in a specific  order based upon when it was posted, commented and shared on a particular  story, thus enabling you to view the latest stories from your links on the top. <br />
              </p>
              <p>In Dashboard, you cannot share or  post any photos which you can do in iLook&rsquo;s second wall <strong>Display</strong>.<br />
              </p>
              <h4>How  do I view the News?</h4>
              <p>You will be able to view news by  clicking <strong>News</strong>,  on the <strong>Dashboard</strong>,  you will be navigated to the news screen. On clicking any heading, you will be  navigated to the detailed screen of the News. <br />
              </p>
              <p>On clicking News towards the top  right hand corner, of the detailed screen, the user will be navigated back to  the News page.<br />
              </p>
              <h4>How  do I expand/collapse the menu?</h4>
              <p>The menu in iLook is static and appears towards the left hand  side of every screen. You will be able to view the below static headings in the  menu:
              </p>
              </p>
              <div class="search">
                <ul>
                  <li>Dashboard</li>
                  <li>Display</li>
                  <li>Jobs </li>
                  <li>Skills</li>
                </ul>
                </div>
                <p>You will be able to <strong>expand</strong> the menu, by following the below steps:<br />
              <p>1. Click on icon on the menu,  towards the top left hand corner.<br />
              <p>You will be able to <strong>collapse</strong> the menu:<br />
              <p>1. Click on Hide Menu corresponding to icon on the menu, towards the top left hand corner.<br />
              <p><strong>Note: </strong>By default,  the menu will appear expandable. In few screens the menu, will appear  collapsed.<br />
              <p>You can navigate to different sections by clicking on any of the headings through the menu.<br />
              <h4>How  do I Post the Status?</h4>
                  <p>You can post the status from the dashboard. You will be able  to post the status, by following the below steps:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Type your  update in the text field, under the Viewed Your Profile section, corresponding  to your name</li>
                  <li>Select an  audience for the post, from the dropdown</li>
                  <li>Click Share</li>
                </ul>
                </div>
              <h4>How  do I edit status?</h4>
                  <p>You can edit the post, by following the below steps:<br />
                  </p>
                  <p>1. Click on the arrow icon towards the right, corresponding  to your name in the post window<br />
                  </p>
                  <p>2. Select edit post<br />
                  </p>
                  <p>3. Click on done editing<br />
                  </p>
              <h4>How  do I delete status?</h4>
                  <p>You can edit the post, by following the below steps:<br />
                  </p>
                  <p>1. Click on the arrow icon towards the right, corresponding  to your name in the post window<br />
                  </p>
                  <p>2. Select delete<br />
                  </p>
                  <p>3. Click on done editing<br />
                  </p>
              <h4>Who  viewed your profile</h4>
                  <p>Who&rsquo;s viewed your profile, enables you to know, who has  looked into your profile in the last few days. You can navigate to this section  by any of the following ways:<br />
                  </p>
                  <p>1. You will be able to view this  section under the News and Display on the dashboard; you can view the people  who have visited your profile, if more than 5 people have visited your profile,  you will be displayed with &ldquo;See More&rdquo;, on clicking &ldquo;See More&rdquo; you can view all  the people who have visited your profile in the past.<br />
                  </p>
                  <p>Clicking the image, you will be  navigated to the profile of the visitor.<br />
                  </p>
                  <p>2. Click the count for the links under  the profile photo, in the left navigation menu.
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Select  &ldquo;recently Viewed Your Profile&ldquo; in the middle navigation menu<h4> </u></strong></li>
                </ul>
                </div>
                <p><em>Note:</em> You will  not be displayed with this section if, anyone has not visited your profile.  Also, the records will vary from time to time based upon the users who view  your profile<strong><u> </u></strong><br />
              <h4>How do I Find People  You Know? </h4>
                  <p>People You  May Know shows you, link suggestions based upon the common areas between you  and the other users in iLook. You will be able to navigated to this section by  any of the following ways:<br />
                  </p>
                  <p>1. Go to Dashboard<br />
                  </p>
                  <p>2. You will be able to view you may know section towards the  right hand side of the screen, initially only 4-5 records will be displayed.<br />
                  </p>
                  <p>3. Click on See More, you will navigated to the detailed page  where in you can view all the people you may know, initially you will be  displayed with 10 records, on clicking &ldquo;View More&rdquo; you will be displayed with  another 10.<br />
                  </p>
                  <p>OR<br />
                  </p>
                  <p>1. Click the  count for the links under the profile photo, in the left navigation menu. <br />
                  </p>
                  <p>2. Click  People You My know in the grey bar<br />
                  </p>
                  <p><strong>Note:</strong> The data is matched through your  profile.<br />
                  </p>
              <h4>How do I accept/decline  the invitations in People You Know? </h4>
                  <p>You can <strong>accept</strong> the suggestion, by following the below steps:<br />
                  </p>
                  <p>1. Click on the      icon to accept the suggestion<br />
                  </p>
              <p>2. Once the notification is sent,  you will be displayed with      icon.
                </p>
                  </p>
                <p>You can <strong>decline </strong>the  suggestion, by following the below steps:<br />
                  </p>
                <p>1. Go to Dashboard<br />
              </p>
                <p>2. You will be able to view you may know section towards the  right hand side of the screen<br />
                  </p>
                <p>3. Click on the cross icon<br />
                  </p>
                <p>Note: The suggestion will be removed from the list  temporarily.</p>
            </div>	