<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
      <div class="help-content">
       	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Search</li>
                    </ul>
          </div>
       	<h3>How do I Search? </h3>
        <p>The  search box is on the top of every page in iLook, it allows you to perform a search  on different categories. Once you have  entered your keywords to search, you may click on the search icon and the  result will be displayed according to the keyword entered in the search tab.</p>
        <p>There are two different types  of searches available in iLook.</p>
        <p>&nbsp;</p>
        <p><strong class="text-purple2">Simple Search: </strong>You can search as per the below criteria&rsquo;s in the  search- People, Jobs and skill. For any type of search, you will have to select  the option from the dropdown first. </p>
        <p>You  can search, people by First name, Last Name, both or simply by entering the  First Name or the Last Name. Once you click on the search tab or enter a page  will be displayed showcasing the search results. </p>
        <p>You  can search, on the basis of Jobs, by typing the keyword in the search and  clicking on the search tab.</p>
        <p>You  can also search for the skills by entering the skill in the search box and then  clicking on the search icon.</p>
        <p>&nbsp;</p>
        <p><strong class="text-purple2">Skills:</strong><strong> </strong>You can select this option from the dropdown provided  corresponding to the advanced text on the top right corner of the screen, once  you have entered the text and clicked on the search icon, you will be able to  view the search results. </p>
        <p>You  will be displayed the skill name. If you are already following the skill then  the &ldquo;following&rdquo; will be displayed. If you are not following the skill, then  &ldquo;follow&rdquo; will be displayed in Green color. On clicking follow, you shall start  to follow the skill and the same will be reflected your profile section.</p>
        <p>You  will be navigated to the detailed screen, on clicking any skill, to view the  recruiters within ilook and within your links.</p>
        <p>If  you are registered as a recruiter, then you will be able to view the individuals  corresponding to the skill, within ilook and within your links.</p>
       <h3>Advanced Search</h3>
        <p>You  will also be able to search by using the Advanced Search feature in individual  categories. Once you click search after entering the keywords, then you will be  navigated to the corresponding category&rsquo;s search results page with the Advance  search option displayed in the same page.</p>
        <p>&nbsp;</p>
        <p><strong class="text-purple2">People:</strong><strong> </strong>You can select this option from the dropdown provided  corresponding to the advanced text on the top right corner of the screen, once  you have entered the text and clicked on the search icon, you will be able to  view the search results and the advance search option. On clicking the <strong class="text-purple2">Advance Search</strong> you will be displayed with the below options:</p>
       <div class="search">
        <ul>
          <li><strong>Name: </strong>You can search for the person on the  basis of Name.<strong></strong></li>
          <li><strong>Country: </strong>You can search for the person on the  basis of Country.<strong></strong></li>
          <li><strong>State: </strong>You can search for the person on the  basis of State.<strong></strong></li>
          <li><strong>City: </strong>You can search for the person on the  basis of City.<strong></strong></li>
          <li><strong>Company: </strong>You can search for the person on the  basis of Company.<strong></strong></li>
          <li><strong>Skills: </strong>You can search for the person on the  basis of Skills.<strong></strong></li>
          <li><strong>Industry: </strong>You can search for the person on the  basis of Industry.<strong></strong></li>
          <li><strong>Language: </strong>You can search for the person on the  basis of Language.<strong></strong></li>
        </ul>
        </div>
      
        <p>By  selecting any of the above options the results will be drilled down  automatically.</p>
        <p>&nbsp;</p>
        <p><strong class="text-purple2">Jobs</strong><strong>:</strong>
          You can select this option  from the dropdown, type the keyword and click on the search icon, you will be  navigated to the results screen with the Advance Search option, on clicking the <strong>Advance  Search</strong> you will be able to view  the below details:</p>
        <div class="search">
        <ul>
          <li><strong>Job Title:</strong> You can search for the Job on the  basis of the name.</li>
          <li><strong>Country: </strong>You can search for the Job on the  basis of Country.<strong></strong></li>
          <li><strong>State: </strong>You can search for the Job on the  basis of State.<strong></strong></li>
          <li><strong>City: </strong>You can search for the Job on the  basis of City.<strong></strong></li>
          <li><strong>Company:</strong> You can search for the Job on the  basis of the company.</li>
          <li><strong>Industry:</strong> You can search for the Job on the  basis of Industry.</li>
          <li><strong>Salary:</strong> You can search for the Job on the  basis of Salary.</li>
          <li><strong>Job Type:</strong> You can search for the Job on the  basis of Type of Job.</li>
          <li><strong>Experience Level:</strong> You can search for the Job on the  basis of Experience.</li>
          <li><strong>Date From/To:</strong> You can search for the Jobs on the  basis of jobs posted during the selected time duration.<strong></strong></li>
        </ul>
        </div>
        <p>By  selecting any of the above options the results will be drilled down by clicking  on search. You can save the job by clicking on the save text towards the top  left hand corner of all the jobs.</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p><strong>&nbsp;</strong></p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
        <p>&nbsp;</p>
      </div>