<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>

            <div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Settings</li>
                    </ul>
                </div>
              <h3>Settings</h3>
             
              <p>You will be able to change the settings from the settings  section</p>
           
             <h4>How Do I change my  General Settings?</h4>
                </p>
              <p>You will be able to update your general settings, by  following the below steps:<br />
              </p>
              <p>You can update your <strong><u>password</u></strong>, by  following the below steps:<strong><u> </u></strong><br />
              </p>
              <p>1. Hover your cursor  over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Click general settings in the middle navigation section<br />
              </p>
              <p>4. Click on Password, the area will expand<br />
              </p>
              <p>5. Enter Current, New and Confirm Password<br />
              </p>
              <p>6. Click Save<br />
              </p>
              <p>You can cancel the same, by clicking on cancel<br />
              </p>
              <p>You can update your <strong><u>status</u></strong>, by  following the below steps:<strong><u> </u></strong><br />
              </p>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Click general settings in the middle navigation section<br />
              </p>
              <p>4. Click on Current Status, the area will expand<br />
              </p>
              <p>5. Select the status from the dropdown<br />
              </p>
              <p>6. Click Save<br />
              </p>
              <p>You can cancel the same, by clicking on cancel<br />
              </p>
              <p>You can <strong><u>close your account</u></strong>, by  following the below steps:<strong><u>:</u></strong><br />
              </p>
              <p>1.Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Click general settings in the middle navigation section<br />
              </p>
              <p>4. Click on Close Account, the area will expand<br />
              </p>
              <p>5. Click Delete Account<br />
              </p>
              <p>6. Click Delete<br />
              </p>
              <p><strong>Note:</strong> If you do  not login within 30 days, your account will be permanently deleted.<br />
              </p>
              <h4>How Do I update my  Privacy Settings?</h4>
                </p>
              <p>You will be able to set <strong><u>who  can view your albums</u></strong>, by following the below steps:<strong><u>:</u></strong><br />
              </p>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Select Privacy Settings from the middle navigation section<br />
              </p>
              <p>4. Select any of the below</p>
              <div class="search">
              <ul>
                <li>Public</li>
                <li>Links</li>
                <li>Links of  Links</li>
                <li>Custom</li>
              </ul>
              </div>
              
              <p>5. Click Save<br />
              </p>
              <p>You will be able to <strong><u>block  user</u></strong>, by following the below steps:<strong><u>:</u></strong><br />
              </p>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Select Privacy Settings from the middle navigation section<br />
              </p>
              <p>4. Click Block user<br />
              </p>
              <p>5. Enter the name of the user, you will be displayed with  predictive search, click on the contact or click on <img width="30" height="27" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon you will be displayed with all the links  in a pop up, click on the checkbox corresponding to the contact, click add<br />
              </p>
              <p>6. Click Block<br />
              </p>
              <p>You will be able to un <strong><u>block  user:</u></strong><br />
              </p>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Select Privacy Settings from the middle navigation section<br />
                </p>
              <p>4. Click Unblock, corresponding to the list of blocked users<br />
              </p>
                
                <h4>How do I block user? </h4>
                <p class="text-purple2">You will be able to Block Users in iLook, by following the below steps:.</p>
                <p class="text-purple2">1. Click on the number in the Black Bar, you will be displayed with all the Links</p>
                <p class="text-purple2">2. Click on the image, you will be displayed with the short profile view</p>
                <p class="text-purple2">3. Click on Report Abuse, in the Manage Followers at the bottom of the pop up</p>
                <p class="text-purple2"><strong>Note:</strong> A request will be sent to the admin, but you will still be able to view that user </p>
				<p>You can block user from <strong><u>Privacy  Settings</u></strong> <br />
			  </p>
             <h4>How Do I update Email Notifications  Settings?</h4>
                </p>
              <p>You will be able to set <strong><u>email  notifications</u></strong> for the below:</p>
              
              <div class="search">
              <ul>
                <li>Link  request</li>
                <li>Feedback</li>
                <li>Reference</li>
                <li>Job Invite</li>
                <li>General  Notifications<strong><u> </u></strong></li>
              </ul>
              </div>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Account Settings<br />
              </p>
              <p>3. Select Notifications in the middle navigation section<br />
              </p>
              <p>4. Select the option &ldquo;Send Email Notification&rdquo; or &ldquo;Don&rsquo;t send  email notification&rdquo;, corresponding to the below</p>
             <div class="search">
              <ul>
                <li>Link  request</li>
                <li>Feedback</li>
                <li>Reference</li>
                <li>Job Invite</li>
                <li>General  Notifications<strong><u> </u></strong></li>
              </ul>
              </div>
              <p>5. Click Save Changes             </p>
              <h4>How Do I Sign Out?</h4>
                </p>
              <p>You will be able to Sign Out, by following the below steps:<br />
              </p>
              <p>1. Hover your cursor over <img width="26" height="22" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_image001_0002.png" />icon displayed on the top right hand<br />
              </p>
              <p>2. Click Sign Out</p>
             <h4>Feedback</h4>
                </p>
              <p>You will be able to provide feedback, to iLook team, by  following the below steps::<br />
              </p>
              <p>When not Logged In<br />
              </p>
              <p>1. Type the url <a href="http://www.iLook.com">www.iLook.com</a> <br />
              </p>
              <p>2. Scroll to the bottom of the page<br />
              </p>
              <p>3. Click Send Feedback<br />
              </p>
              <p>When Logged In<br />
              </p>
              <p>1. Click on the Feedback bar, on the right hand side<br />
              </p>
              <p>2. You will be navigated to the compose mail section, with  email id populated<br />
              </p>
              <p>3. Enter subject, message<br />
              </p>
              <p>4. Click Send<br />
              </p>
        
      </div>	