<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
           <div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Display</li>
                    </ul>
                </div>
            	<h3>Display</h3>
                  <p><strong>Display</strong> is the  second wall within iLook. This is very unique features wherein you will be able  to share/post photos with your links. You can navigate to this section by  clicking on Display in the Black Bar. <strong><u> </u></strong><br />
                  </p>
                  <p>In this section, you can only post/share  photos and not any links or general status update. You can post photos such as  your team, team party, team lunch/dinner, work Christmas party/new year party,  your portfolios, work, project, creations, products, services and so on. This  will enable you to promote your skills/products to your network.<br />
                  </p>
                  <p>The stories appear in a specific  order based upon when it was posted, commented and shared on a particular  story, thus enabling you to view the latest stories from your links on the top. <br />
                  </p>
              <h4>How  Do I Add photos?</h4>
              <p>You can add/post photos to iLook,  the photos added in iLook, will be stored in the <strong><u>albums </u></strong>of your Profile  section and will be visible and shared in the <strong><u>Display </u></strong>section. There  are two ways to post/add photos from Display section.</p>
              </p>
              <div class="search">
              <ul>
                <li>You will be  able to add photos without creating an Album by clicking on the<strong> </strong>Add Photos<strong> </strong>which  then will be stored in a default album within your profile called &lsquo;Display  album&rsquo;.</li>
                  <li>You will be  able to create a new album and add photos by clicking on the &rsquo;Create Album&rsquo;  which then will create a new album and you can add photos. This will be  displayed in the Display wall and also in your Profile Albums with the album  name that you have created.</li>
                </ul>
                </div>
              <p>Below are  the steps that will help you to create an album and add photos.</p>
                <div class="search">
                <ul>
                  <li>You can  choose to upload a new photo from your computer. </li>
                  <li>Once the  photo is uploaded, it will be displayed under the &ldquo;Say something box&rdquo;. </li>
                  <li>In the text  box, you can provide a title to the photo uploaded. You can also select the  privacy settings of the photo by clicking on the dropdown, under the photo.  This will enable you to decide who can view your photo.</li>
                  <li>Click  Share, the photo will be shared on your as well as your friend&rsquo;s wall, as per  the privacy settings selected you.</li>
                  <li>You can  delete the photo by clicking on the cross mark, at the top right hand corner of  the photo, the photo will then not be displayed any longer in the section.</li>
                </ul>
                </div>
              <p><strong><u>&nbsp;</u></strong></p>
                <h4>How  do I View Photo Albums?</h4>
                  <p>You can view your photo albums, by following the below steps:<strong><u> </u></strong><br />
                  </p>
                  <p>1. Go to Display<br />
                  </p>
                  <p>2. Click on Photo Albums, on the photo towards the right hand  corner<br />
                  </p>
                  <p>3. You will be navigated to photos and portfolios where in,  you can view the photo albums<br />
                  </p>
                  <p><strong>Or</strong><br />
                  </p>
                  <p>1. Click on your name, at the top right corner<br />
                  </p>
                  <p>2. Select Photos and Portfolios<br />
                  </p>
              <h4>How  do I Create Photo Albums?</h4>
                  <p>You will be able to create Album, by following the below  steps:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Go to  Display</li>
                  <li>Click on  Create photo Albums</li>
                  <li>You will be  displayed with a pop to upload photos from your computer, the photos will be  displayed under the &ldquo;Say something box&rdquo;.</li>
                  <li>You can:</li>
                  <li>Provide a title to the album uploaded, in the text box</li>
                  <li>You can also select the privacy settings of the album  by clicking on the dropdown, under the album. This will enable you to decide  who can view your photo</li>
                  <li>Add Name to Album</li>
                  <li>Click Share</li>
                </ul>
                </div>
                <p><strong>Note: </strong>The album  uploaded will be visible on your wall as well as the in the Albums section. <strong></strong><br />
              <h4>How  do I Delete Photo Albums?</h4>
                  <p>You will be able to delete the album, by following the below  steps:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Go to  display</li>
                  <li>Click on  the arrow icon towards the right, corresponding the album posted.</li>
                  <li>Click on  delete</li>
                  <li>Click on  yes in the pop up</li>
                  <li>Album will  be deleted successfully</li>
                </ul>
                </div>
              <h4>What  is Wish Section?</h4>
                  <p>You will displayed with the below events of your links in  this section
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>New Link</li>
                  <li>New Job</li>
                  <li>Birthdays</li>
                  <li>Job  Anniversaries</li>
                </ul>
                </div>
              <h4>New  Link</h4>
                  <p>You will receive this notification if your link has a new  link, you can perform the below actions:<br />
                  </p>
                  <p>1. You will be displayed with the link name of both the links that got linked<br />
                  </p>
                  <p>2. Click on the wish to navigate to the profile of the link<br />
                  </p>
              <h4>New  Job</h4>
                  <p>You will receive this notification if your link has a new job,  you can perform the below actions:<br />
                  </p>
                  <p>1. You will be displayed with the new job of your link<br />
                  </p>
                  <p>2. Click on the wish<br />
                  </p>
                  <p>3. You will be displayed with a pop up<br />
                  </p>
                  <p>4. You can ok and comment the wish, you will be able to view the ok and comments of other  links<br />
                  </p>
              <h4>Birthdays</h4>
                  <p>You will receive this notification if your link has Birthday  today, you can perform the below actions:<br />
                  </p>
                  <p>1. You will be displayed with the Birthday<br />
                  </p>
                  <p>2. Click on the wish<br />
                  </p>
                  <p>3. You will be displayed with a pop up<br />
                  </p>
                  <p>4. You can ok and comment the wish, you will be able to view  the ok and comments of other links<br />
                  </p>
              <h4>Job  Anniversary</h4>
                  <p>You will receive this notification if your link has completed  X years in their current job, you can perform the below actions:<br />
                  </p>
                  <p>1. You will be displayed with the job where in the link has completed  their job anniversary<br />
                  </p>
                  <p>2. Click on the wish<br />
                  </p>
                  <p>3. You will be displayed with a pop up<br />
                  </p>
                  <p>4. You can ok and comment the wish, you will be able to view  the ok and comments of other links<br />
                  </p>
                  <p><strong>Note:</strong> Wish  section will be displayed for a time period of 24 hours<br />
                  </p>
              <h4>How  do I view the Wish Section?</h4>
                  <p>You will be able to view the wish section, by following the  below steps:<br />
                  </p>
                  <p>1. Click on Display in the <strong><u>Menu</u></strong><br />
                  </p>
                  <p>2. Towards the right hand side of the wall, you will be able  to view the wish section<br />
                  </p>
                  <p><strong>Note:</strong> You will  be displayed with maximum 10 wishes on display screen, to view more, you can  click on the view more link provided at the bottom of the wishes.</p>
              </p>
            </div>	