<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );

// $this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/home_search.js" );
// $this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/registeration.js" );
?>

            <div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Links</li>
                    </ul>
                </div>
            	<h3>Links</h3>
<p>This section enables you to expand  your network, by sending and accepting requests from other users. You can  invite your friends to your network.</p>
<h4>How do I View My Links? </h4>

<p>You will be able to view your links, by following the below  steps:<br />
  </p>
<p>1. Click on the number in the Black Bar<br />
  </p>
<p>2. You will be displayed with all the links<br />
  </p>
<p><strong>Note:</strong> You will  be displayed with 0 initially, when you do not have any links in your Profile<br />
</p>
<h4>How do I View the  profile of my links?</h4>
<p>You can view the profile of your links, where in you will be  able to view the Profile details entered by the user, Skills, Feedback,  References, by following the below steps:<br />
  </p>
<p>1. Click on the number in the Black Bar<br />
  </p>
<p>2. You will be displayed with all the links<br />
  </p>
<p>3. Click on the Name of your Link, displayed under the image<br />
  <h4>How do I Add New Link?</h4>
  <p>You can Invite your friends to join iLook, by following the  below steps:<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on Add New Links<br />
    </p>
  <p>3. You will be able to directly invite contacts through Gmail  and Yahoo, by clicking Gmail and Yahoo icon, you may also enter the email id in  the search box to send invitations directly<br />
    </p>
  <p>4. Your friends will receive a link, to register in iLook<br />
  </p>
  <h4>How do I view Pending  link Requests?</h4>
  <p>You will be able to view the pending Link requests, by  following the below steps:<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on New Link Requests<br />
    </p>
  <p>3. You will be displayed with the pending link requests in  this section<strong> </strong><br />
    </p>
  <p>Or<br />
    </p>
  <p>1. through the <strong><a class="text-purple-link" style="cursor:default;" href="javascript:void(0);">Link Request  Notifications</a></strong> <br />
    </p>
  <p><strong>Note:</strong> If there  are no Pending requests, then you will be displayed with People You May Know<br />
  </p>
  <h4>How do I send link  request?</h4>
  <p>You will be able to send Link requests, by following the below  steps:<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on      icon, the icon will change to <br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Visit a Profile<br />
    </p>
  <p>2. Click on Invite To Links<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on Add New Links<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Search Link<br />
    </p>
  <p>2. Click on      icon, the icon will change to <br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Search Link<br />
    </p>
  <p>2. Click on the image, you will be displayed with a pop up<br />
    </p>
  <p>2. Click on Invite To Link corresponding to      icon, <br />
    </p>
  <p><strong>Note:</strong> Initially  when there are no links, you will be able to send link requests from the People  you May know section<br />
  </p>
  <h4>How do I decline link  request?</h4>
  <p>You will be able to  decline Link requests, by following the below steps:<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on New Link Requests<br />
    </p>
  <p>3. Click Decline<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Click on mail icon<br />
    </p>
  <p>2. You will be displayed with the link requests<br />
    </p>
  <p>3. Click on Decline under the link Request<br />
  </p>
  <h4>How do I accept link  request?</h4>
  <p>You will be able to  accept Link requests, by following the below steps:<br />
    </p>
  <p>1. Click on the number in the Black Bar<br />
    </p>
  <p>2. Click on New Link Requests<br />
    </p>
  <p>3. Click accept<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Click on mail icon<br />
    </p>
  <p>2. You will be displayed with the link requests<br />
    </p>
  <p>3. Click on accept under the link Request<br />
  </p>
  <h4>How Do I cancel the link  request?</h4>
  <p>You can cancel the Link request which you have sent, by  following the below steps:<br />
    </p>
  <p>1. Search Link, to whom you have sent Link request<br />
    </p>
  <p>2. Click on the      icon<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Search Link, to whom you have sent Link request<br />
    </p>
  <p>2. Click on the image of the Link<br />
    </p>
  <p>3. You will be displayed with the pop up<br />
    </p>
  <p>4. Click on Cancel request corresponding to the icon, in the pop up, under the manage followers heading<br />
    </p>
  <p>5. You will be displayed with a pop up, click unlink<br />
  </p>
  <h4>How do I unlink my  link?</h4>
  <p>You will be able to unlink your link, by following the below  steps:<br />
    </p>
  <p>1. Search the Link<br />
    </p>
  <p>2. Click on the image of the Link<br />
    </p>
  <p>3. You will be displayed with the pop up<br />
    </p>
  <p>4. Click on unlink, in the pop up, under the manage followers  heading<br />
  </p>
  <h4>How do I send message?</h4>
  <p>You can connect with your links by sending them messages, you  can send message to your link:<br />
    </p>
  <p>1. Search for your link<br />
    </p>
  <p>2. You will be displayed with the icon to send a message, towards the bottom right corner of the  image<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Search for your link<br />
    </p>
  <p>2. Click on the image of the Link<br />
    </p>
  <p>3. You will be displayed with the email id, corresponding to      icon.<br />
    </p>
  <p>4. Click on email<br />
    </p>
  <p>Or<br />
    </p>
  <p>1. Click on the number in the Black Bar, you will be  navigated to the All Links section<br />
    </p>
  <p>2. You will be displayed with the icon to send a message, towards the bottom right corner of the  image
    </p>
    </p>
  </p>
  <p>Or<br />
              </p>
  <p>1. Click on the number in the Black Bar, you will be  navigated to the All Links section<br />
              </p>
  <p>2. Click on the image of the Link<br />
              </p>
  <p>3. You will be displayed with the pop up<br />
              </p>
  <p>3. You will be displayed with the email id, corresponding to icon.<br />
              </p>
  <p>4. Click on email<br />
              </p>
  <p>You will be navigated to the compose mail section, to send the mail<br />
        </p>
  <p><strong>Note: </strong>You will  also be able to send the mail, from the <strong><u>compose  mail</u></strong> section.</p>
             
             
             		<h4>How do I Tag my Links  to a group?</h4>
			  </p>
				<p>You will be able to tag your links to groups, by following  the below steps:<br />
			    </p>
				<p>1. Search a Link<br />
			    </p>
				<p>2. Click on the image of the Link<br />
			    </p>
				<p>3. You will be displayed with the pop up<br />
			    </p>
				<p>4. Click on Tags<br />
			    </p>
				<p>5. You will be displayed with a pop up<br />
			    </p>
				<p>6. Click on the checkbox corresponding to the name displayed  in the pop up<br />
			    </p>
				<p>7. Click Save, your link will be assigned with the Tag<br />
			    </p>
				<p>Or<br />
				  </p>
			  <p>1. Click on the number in the Black Bar, you will be  displayed with all the Links<br />
				  </p>
			  <p>2. Click on the image of the Link<br />
				  </p>
			  <p>3. You will be displayed with the pop up<br />
				  </p>
			  <p>4. Click on Tags<br />
				  </p>
			  <p>6. Click on the checkbox corresponding to the name displayed  in the pop up<br />
				  </p>
			  <p>7. Click Save, your link will be assigned with the Tag</p>
              <p>&nbsp;</p>
              <p><strong>Note:</strong> You will  be able to assign, multiple tags to a single Link</p>
              <p>&nbsp;</p>
              <h4>How do I View Tagged  Links?</h4>
              </p>
              <p>You can view the Tagged links under the groups which you have  tagged them already, by following the below steps<strong></strong><br />
              </p>
              <p>1. Click on the number of links in the Black Bar<br />
              </p>
              <p>2. You will be displayed with the Tags listing, under the  categories, in the middle navigation panel<br />
              </p>
              <p>3. Click on any Tag name, in the middle navigation panel, you  will be displayed with all the links associated with that tag<br />
              </p>
              <p>&nbsp;</p>
              <h4>How do I create new  tags?</h4>
                </p>
              <p>You will be able to add tags, by following the below steps:<br />
              </p>
              <p>1. Click on the number of links in the Black Bar<br />
              </p>
              <p>2. Click on <img width="25" height="24" style="vertical-align: middle;" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_links.png" />icon, corresponding to the Tags, in the middle  navigation section, beneath the Categories heading<br />
              </p>
              <p>3. You will be displayed with a pop up<br />
              </p>
              <p>3. Enter the Name of the tag, in the text box<br />
              </p>
              <p>4. Click on Add Tag<br />
              </p>
              <p>Or<br />
              </p>
              <p>1. Click on the number of links in the Black Bar<br />
              </p>
              <p>2. Click on the image of the user, you will be displayed with  short profile view<br />
              </p>
              <p>3. Click Tags<br />
              </p>
              <p>4. Enter the Name of the tag, in the text box<br />
              </p>
              <p>5. Click on Add Tag<br />
              </p>
              <p><strong>Note: </strong>Once the  tag is added, it will start getting displayed, under the tags heading, in the  middle navigation section<br />
                </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <h4>How do I delete tags?</h4>
                </p>
              <p>You will be able to delete the tag, by following the below  steps:<br />
                </p>
              <p>1. Click on the number of links in the Black Bar<br />
                </p>
              <p>2. Click on <img width="25" height="24" style="vertical-align: middle;" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_links.png" />icon, corresponding to the Tags, in the middle  navigation section, under the Categories heading<br />
                </p>
              <p>3. You will be displayed with a pop up, click on the cross  icon, corresponding to the tag <br />
                </p>
              <p>&nbsp;</p>
              <p>&nbsp;</p>
              <h4>How do I edit tags?</h4>
                </p>
              <p>You will be able to edit the tag, by following the below  steps:<br />
                </p>
              <p>1. Click on the number of links in the Black Bar<br />
                2. Click on <img width="25" height="24" style="vertical-align: middle;" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-settings_clip_links.png" />icon, corresponding to the Tags, in the middle  navigation section, under the Categories heading<br />
                </p>
              <p>3. You will be displayed with a pop up, double click the tag  name, it will appear in the editable mode<br />
                </p>
              <p>4. Re- enter the tag name<br />
                </p>
              <p>5. Click Save<br />
                </p>
              <p>&nbsp;</p>
              <h4>How Do I view People You May Know?</h4>
                </p>
              <p>You will be displayed with suggestions to extent your network  based upon certain similarities such as your college and company name, you can  view people you may know, by following the below steps:<br />
                </p>
              <p>1. Click on the number of links in the Black Bar<br />
                </p>
              <p>2. Click People You May Know, in the middle navigation  section<br />
                </p>
              <p>Or<br />
                </p>
              <p>1. Go to Dashboard<br />
                </p>
              <p>2. You will be displayed with People You May Know section, on  the right hand side<br />
                </p>
              <p><strong>Note:</strong> You will  be displayed with 10 suggestions on the right hand side, on clicking see more,  you will be navigated to the people you may know section in the links<br />
                </p>
              <p>Initially when you do not have any suggestions, then you will  be displayed Invite contacts.<br />
                </p>
              <p>You will be displayed with users whom you have sent link  request and the ones suggested by iLook team.<br />
                </p>
              <p>&nbsp;</p>
             <h4>How Do I remove the suggestions from People You May Know?</h4>
                </p>
              <p>You will be able to remove the suggestions from people you  may know, by following the below steps:<br />
                </p>
              <p>1. Go to Dashboard, you will be displayed with people you may  know on the right hand side.<br />
                </p>
              <p>2. Click on the cross icon on the right hand side of the name  of the suggested user<br />
                </p>
              <p><strong>Note: </strong>The  suggestions will not be visible for some timespan<br />
                </p>
              <p>&nbsp;</p>
             <h4>How Do I view who Recently Viewed your profile?</h4>
                </p>
              <p>You will be able to view the links, who recently viewed you  profile, by following the below steps:<br />
                </p>
              <p>1. Click on the number of links in the Black Bar<br />
                </p>
              <p>2. Click on Recently Viewed your profile, in the middle  navigation section<br />
                </p>
              <p><strong>Note:</strong> You will  be displayed with both the Links and other iLook users<br />
                </p>
              <p>&nbsp;</p>
             <h4>View Others Profile</h4>
                </p>
              <p>You can view the profile of any one on iLook, to view the  profile of your links, follow the below steps:<br />
                </p>
              <p>1. Click on the number of links in the Black Bar<br />
                </p>
              <p>2. Click on the name of your link, highlighted in purple<br />
                </p>
              <p>You can view the profile of other users on iLook:<br />
                </p>
              <p>1. Search the name of the user in the search box on the top  right corner <br />
                </p>
              <p>2. You will be displayed with the users matching your search<br />
                </p>
              <p>3. Click on the name of your link, highlighted in purple<br />
                </p>
              <p>Or<br />
                </p>
              <p>You may also view the links and other users on ilook, through  the Dashboard and Display, by clicking on the name of the user who has  posted/liked/commented or shared an update</p>
              <p>&nbsp;</p>
              <h4>Delete Link Request</h4>
</p>
              <p>You will be able to delete Link request from the <strong><u>Inbox link requests  section</u></strong> <br />
  </p>
                             	
            </div>	