<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
     <div class="help-content">
       	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Skills</li>
                    </ul>
          </div>
 
        </u></strong></p>
        <h3>Skills </h3>
        <p>In this section, you will be able to view your skills, search  skills, view recruiters/ individuals for that skill.<br />
          If you are a recruiter, you will be displayed with the  individuals following the skill.<br />
          In case you are an individual, you will be displayed with the  recruiters following the skill.</p>
        <h4>Support  skills</h4>
          <p>Support  Skill enables you to appreciate the skill of your links by supporting them. It  enables you to increase and explore your professional network. You can support  skill by any of the following ways:<br />
          </p>
          <p>1. Go to  dashboard<br />
          </p>
          <p>2. You will  be able to view support section towards the right hand side of the screen<br />
          3. Under the  Name of the user, click on the <img width="32" height="32" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image001.png" />icon<br />
          </p>
          <p><strong>OR</strong><br />
          </p>
          <p>1. Go to  profile of any iLook user, by clicking on their name.<br />
          </p>
          <p>2. Click on  Skills tab<br />
          3. Click on <img width="29" height="20" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image002.png" />icon towards the left hand side<br />
          </p>
          <p><strong>Note:</strong> This section will be visible only if  you have not supported any of your links skill. Your links should have added  skills to their profile, to get notifications; you don&rsquo;t have to ask for skill  support.<br />
          </p>
        <h4>How  do I view users who have supported my skills?</h4>
          <p>1. Go to  profile section, by clicking on your name.<br />
          </p>
          <p>2. Click on  Skills tab<br />
          </p>
          <p>3. Click on  the <img width="16" height="16" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image003.png" />icon towards the right hand side, the lower  portion will expand displaying the users who have supported your skills        </p>
          </p>
        <h4>How Do I view the skills I follow?</h4>
        <p>You will be able to view the skills you follow, by following  the below steps:<br />
        </p>
        <p>1. Click on Skills in the <strong><u>Menu</u></strong><br />
        </p>
        <p>2. Click on My Skills<br />
        </p>
        <p>3. You will be displayed with all the skills that you are  following<br />
        </p>
        <p>4. Click on the <img width="15" height="15" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image004.png" />icon, corresponding to the skill, the area  will expand<br />
        </p>
        <p>5. You will be displayed with all your links following that  skill, you will be displayed with the name and the profile photo of your link</p>
        <p>You can collapse the area, by clicking on the <img width="28" height="12" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image005.png" />icon</p>
        <p><strong>Note: </strong>You will be displayed with the name and profile photo of your  link, on clicking the name you will be navigated to the profile of the user.  You can also, add and edit skill, from this section</p>
        <p>Or <br />
          </p>
        <p>You can view through the profile<br />
          </p>
        <p>1. Click on your name towards the top right corner<br />
          </p>
        <p>2. Click on the Skills tab<br />
          </p>
        <p>3. You will be displayed with all the skills that you are  following<br />
          </p>
        <p>4. Click on the <img width="15" height="15" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image004_0000.png" />icon, corresponding to the skill, the area  will expand<br />
          </p>
        <p>5. You will be displayed with all your links following that  skill, you will be displayed with the name and the profile photo of your link</p>
        <p>You can collapse the area, by clicking on the <img width="28" height="12" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image005_0000.png" />icon</p>
        <h3>When you are Logged In as an Individual</h3>
        <h4>How Do I search recruiters corresponding a skill?</h4>
        <p>You will be able to view the links, following your skills, by  following the below steps:</p>
        <p>1. Click on Skills in the <strong><u>Menu</u></strong><br />
          </p>
        <p>2. Click on search recruiters<br />
          </p>
        <p>3. Enter a Skill<br />
          </p>
        <p>4. You will be displayed with the skill<br />
          </p>
        <p>5. Click Follow, if you are not following the skill, if you  are already following the skill, then the following will be displayed<br />
          </p>
        <p>6. Click Skill Name<br />
          7. You will be displayed with all the recruiters who are  following that skill, you can send recruiters link request by clicking <img width="48" height="47" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image007.jpg" />icon, if already link then you can send mail  by clicking on the <img width="49" height="40" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image009.jpg"/>icon, you will be navigated to the recruiters  profile by clicking on the name.<br />
          </p>
        <p>8. You can view the recruiters on the basis of within ilook  and within your links.</p>
        <p><strong>Note: </strong>You will be  displayed with the name and profile photo of your link, on clicking the name  you will be navigated to the profile of the user.</p>
        <h3>When you are Logged In as a Recruiter</h3>
      
        <h4>How Do I search Individuals corresponding a skill?</h4>
        <p>You will be able to view the links, following your skills, by  following the below steps:</p>
        <p>1. Click on Skills in the <strong><u>Menu</u></strong><br />
        <p>2. Click on search individuals<br />
        <p>3. Enter a Skill<br />
        <p>4. You will be displayed with the skill<br />
        <p>5. Click Follow, if you are not following the skill, if you  are already following the skill, then the following will be displayed<br />
        <p>6. Click Skill Name<br />
          7. You will be displayed with all the individuals who are  following that skill, you can send individuals link request by clicking <img width="48" height="47" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image007_0000.jpg"/>icon, if already link then you can send mail  by clicking on the <img width="49" height="40" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image009_0000.jpg" />icon, you will be navigated to the individuals  profile by clicking on the name.<br />
        <p>8. You can view the individuals on the basis of within ilook  and within your links.<br />
        <h4>How do I Add skills?</h4>
          <p>You will be able to add skills, by following the below steps:<br />
          1. Click on Skills in the <strong><u>Menu</u></strong><br />
          </p>
          <p>2. By default, you will be displayed with My Skills<br />
          </p>
          <p>3. Click on &ldquo;Add More skills&rdquo;<br />
          </p>
          <p>4. Enter a skill<br />
          </p>
          <p>5. Click Save<br />
          </p>
          <p><strong>Note: </strong>To add  multiple skills click on &ldquo;Add More Skills&rdquo;, once the skill is added to your  profile the same shall be displayed throughout.<br />
          </p>
        <h4>How do I edit my skill?</h4>
          <p>You will be able to edit your skill, by following the below  steps:<br />
          </p>
          <p>1. Click on your name displayed at the top right corner<strong><u> </u></strong><br />
          </p>
          <p>2. Click on Edit profile in the middle grey panel<br />
          </p>
          <p>3. Click on Skills, in the middle grey panel<br />
          4. Click on <img width="32" height="33" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image010.png" />icon at the bottom of the skills<br />
          5. You will be displayed with <img width="24" height="24" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-skills_clip_image011.png" />icon, on clicking the skill will  be deleted.<br />
          </p>
        <h4>Bookmarks</h4>
          <p>You will also be able to view the bookmarked profiles from  this section:<br />
          Click on Bookmarks, you will be navigated to the, <strong><u>bookmarks section in Profile</u></strong></p>
          </p>
      </div>