<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
            <div class="help-content">
           	  <div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Notifications</li>
                    </ul>
                </div>
            	<h3>Mails</h3>
              <h4>How Do I compose mail?</h4>
              <p>You can compose mail, by following the below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. Click on compose mail in the middle navigation section<br />
                3. Enter the name of the link, you will be displayed with the  names in the predictive search, select the name OR click on<img width="30" height="27" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image002.png" />icon you will be displayed with  all the links in a pop up, click on the checkbox corresponding to the contact,  you wish to add, click add<br />
              </p>
              <p>4. Enter subject, message<br />
              </p>
              <p>5. Click Send<br />
              </p>
              <p>You can cancel the message by clicking on the cancel<br />
              </p>
              <p>OR<br />
                1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0000.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. You will be navigated to the inbox<br />
                3. Click on <img width="25" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image003.png" />icon, on the top right corner, you  will be navigated to the compose mail section<br />
              </p>
              <h4>How Do I navigate to  mails section?</h4>
              <p>Mails will help you to explain information through messages;  you will be displayed with the mails section, by following the below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0000.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. You will be navigated to the mails section<br />
              </p>
              <h4>How Do I view sent  mails?</h4>
              <p>You will be able to view the sent mails, by following the  below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0000.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. Click on sent mail in the middle navigation section<br />
              </p>
              <p>3. You will be displayed with the Name of the user to whom,  you have sent the message, along with the message and the time frame at which  the message was sent<br />
              </p>
              <p><strong>Note: </strong>You can  also, compose a mail from this section, you will be able to search on the basis  of any keyword through the search provided on the top right hand side<br />
              </p>
              <h4>How Do I delete a sent message?</h4>
              <p>You will be able to delete sent messages, by following the  below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0003.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. Click on sent mail in the middle navigation section<br />
              </p>
              <p>3. Click on the arrow icon, on the right bottom of the  message <br />
              </p>
              <p>4. Click Delete<br />
              </p>
              <p>You can delete multiple messages at the same time,<br />
              </p>
              <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
              </p>
              <p>2. Click manage<br />
              </p>
              <p>3. Click delete<br />
              </p>
              <h4>How Do I archive sent message?</h4>
              <p>You will be able to delete sent messages, by following the  below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0004.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. Click on sent mail in the middle navigation section<br />
              </p>
              <p>3. Click on the arrow icon, on the right bottom of the  message <br />
              </p>
              <p>4. Click archive<br />
              </p>
              <p>You can archive multiple messages at the same time, by  following the below steps:<br />
              </p>
              <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
              </p>
              <p>2. Click manage<br />
              </p>
              <p>3. Click Archive<br />
              </p>
              <h4>How Do I forward sent message?</h4>
              <p>You will be able to delete sent messages, by following the  below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0005.png" />icon, on the top right hand corner<br />
              </p>
              <p>2. Click on sent mail in the middle navigation section<br />
              </p>
              <p>3. Click on the arrow icon, on the right bottom of the  message <br />
              </p>
              <p>4. Click forward<br />
                5. Enter the name of the link, you will be displayed with the  names in the predictive search, select the name OR click on<img width="30" height="27" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image002_0000.png" />icon you will be displayed with  all the links in a pop up, click on the checkbox corresponding to the contact,  you wish to add, click add<br />
              </p>
              <p>6. Enter the subject, message<br />
              </p>
              <p>7. Click Send Message, on the top of the message<br />
                You can also clear the content by clicking on the clear <br />
              </p>
              <h4>How Do I archive  messages?</h4>
              <p>You will be able to archive messages, by following the below  steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0006.png" /> icon, on the top right hand corner<br />
              </p>
              <p>2. Click on Email messages<br />
              </p>
              <p>3. Click on the arrow icon, on the right bottom of the  message<br />
              </p>
              <p>4. Click on Archive<br />
              </p>
              <p>OR<br />
                1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0007.png" /> icon, on the top right hand corner<br />
              </p>
              <p>2. Click on Email messages<br />
              </p>
              <p>3. Click on Mail, you will be navigated to the detailed mail<br />
              </p>
              <p>4. Click Archive<br />
              </p>
              <p><strong>Note:</strong> Once the  message is archived, it will be navigated to the archive section<br />
              </p>
              <h4>How Do I view archived  messages?</h4>
              <p>You will be able to view the archived messages in this section,  you can view the archived messages, by following the below steps:<br />
              </p>
              <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0008.png" /> icon, on the top right hand corner<br />
              </p>
              <p>2. Click on archived messages<br />
              </p>
              <p>You can perform the below actions on the archived messages:
              </p>
              </p>
              <div class="search">
                <ul>
                  <li>Reply</li>
                  <li>Forward</li>
                  <li>Mark as  Unread</li>
                  <li>Inbox </li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the archived messages in the middle navigation  section<br />
              <p>2. Click on the arrow icon, on the right bottom of the  message, you will be able to view all the options<br />
              <h4>How Do I manage archive  messages?</h4>
                  <p>You can manage multiple mails in the archive at the same time,  by following the below steps:<br />
                  </p>
                  <p>1. Click on the archived messages in the middle navigation  section<br />
                  </p>
                  <p>2. Select the mails, which you wish to manage, by clicking on  the checkbox, on the left hand side<br />
                  </p>
                  <p>3. Click Manage at the top<br />
                  </p>
                  <p>4. You will be able to perform the below actions on the  selected mails:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Move to  Inbox</li>
                  <li>Mark as  read</li>
                  <li>Mark as  Unread</li>
                  <li>Delete</li>
                </ul>
                </div>
              <h4>How Do I view trash  messages?</h4>
                  <p>You will be able to view the trash messages, by following the  below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0009.png" />icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click on the trash messages in the middle navigation  section<br />
                  </p>
              <h4>How Do I delete  messages?</h4>
                  <p>You will be able to delete messages, from any section in  mails, you can do so, by following the below steps:<br />
                  </p>
                  <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
                  </p>
                  <p>2. Click Manage<br />
                  </p>
                  <p>3. Select Delete<br />
                  </p>
              <h4>How Do I view inbox  messages?</h4>
                  <p>You will be able to view the messages in the inbox, by  following the below steps:<br />
                  1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0010.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on Email messages the middle navigation section<br />
                  </p>
                  <p>You will be able to view the image, name of the link, who has  sent the message, days ago, when the message was sent.<br />
                  </p>
                  <p>You will be able to perform the below actions:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Reply</li>
                  <li>Forward</li>
                  <li>Archive</li>
                  <li>Mark as  read</li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the arrow icon, on the right bottom of the  message, you will be able to view all the above options<br />
                  </p>
                <p>You can also manage the below options:</p>
                <div class="search">
                <ul>
                  <li>Archive</li>
                  <li>Mark as  read</li>
                  <li>Mark as  unread</li>
                  <li>Delete</li>
              </ul>
              </div>
                <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
              <p>2. Click Manage<br />
              <h4>How Do I view Link  Requests?</h4>
                  <p>You can view the Link requests received, in this section, by  following the below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0011.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on Link requests the middle navigation section<br />
                  </p>
                  <p>You will be displayed with the Name, Image of your link, on  clicking the request you can accept/decline the same<br />
                  </p>
              <h4>How Do I accept Link  Requests?</h4>
                  <p>You can accept Link requests received, in this section, by  following the below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0012.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on Link requests the middle navigation section<br />
                  </p>
                  <p>4. You will be displayed with the link request, click on mail<br />
                  </p>
                  <p>5. Click Accept<br />
                  </p>
              <h4>How Do I decline Link  Requests?</h4>
                  <p>You can accept Link requests received, in this section, by  following the below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0013.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on Link requests the middle navigation section<br />
                  </p>
                  <p>4. You will be displayed with the link request, click on mail<br />
                  </p>
                  <p>5. Click Decline<br />
                  </p>
                  <p>You will be able to perform the below actions:
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Mark as  unread</li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the arrow icon, on the right bottom of the  message, you will be able to view all the options<br />
                You will be able to manage the below:</p>
                <div class="search">
                <ul>
                  <li>Mark as  read</li>
                  <li>Mark as  unread</li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
              <p>2. Click Manage<br />
              <h4>How Do I view Job  Invitations?</h4>
                  <p>You will be able to view the job Invitations in the inbox, by  following the below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0014.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on job Invitations in the middle navigation section<br />
                  </p>
                  <p>You will be able to view the image, name of the link and the  time when the message was sent.<br />
                  </p>
                  <p>You will be able to perform the below actions:
                  </p>
                  </p>
               <div class="search">
                <ul>
                  <li>Mark as  read</li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the arrow icon, on the right bottom of the  message, you will be able to view all the above options<br />
                You can also manage the below options:</p>
                <div class="search">
                <ul>
                  <li>Mark as  read</li>
                  <li>Mark as  unread</li>
                  <li>Delete</li>
                </ul>
              </div>
                <p>1. Click on the checkbox corresponding to the image, on the  left hand side<br />
                  2. Click Manage<br />
  <h4>How Do I view Feedback  Requests?</h4>
                  <p>You will be able to view feedback requests, by following the  below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0015.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  </p>
                  <p>3. Click on feedback requests in the middle navigation  section<br />
                  You can also provide and request feedback from this section,  by clicking on the <img width="24" height="29" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image004.png" />icon.<br />
                  </p>
              <h4>How Do I view Reference  Requests?</h4>
                  <p>You will be able to view reference requests, by following the  below steps:<br />
                  </p>
                  <p>1. Click on <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0016.png" /> icon, on the top right hand corner<br />
                  </p>
                  <p>2. Click Inbox<br />
                  3. Click on reference requests in the middle navigation  section<br />
                  </p>
                  <p>You can also provide and request reference from this section,  by clicking on the <img width="24" height="29" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image004_0000.png" />icon.<br />
                  </p>
              <h4>Notifications</h4>
                  <p>You will be able to view the notifications in this section,  there are two types of Notifications
                    </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Mail</li>
                  <li>General </li>
                </ul>
                </div>
              <h4>Mail Notifications</h4>
                  <p>You will be able to view the mail notifications, for the  below scenarios, by following the below steps:<br />
                  </p>
                  <p>1. Hover your cursor over <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0017.png" />icon<br />
                  </p>
                  <p>2. You will be displayed with all the notifications<br />
                  </p>
                  <p>3. On clicking any notification, you will be navigated to  that particular notification<br />
                  </p>
                  <p>You will receive notifications for the below:
                  </p>
                  </p>
                <div class="search">
                    <ul>
                      <li>Email  Messages</li>
                      <li>Link  Requests</li>
                      <li>Job  Invitation Requests</li>
                      <li>Feedback  Requests</li>
                      <li>Reference  Requests</li>
                  </ul>
              </div>
                <p>You will be able to accept feedback, reference and link  requests from the notifications<br />
              <h4>How do I accept Link  request from notifications?</h4>
                  <p>You will be able to view the mail notifications, by following  the below steps:<br />
                  </p>
                  <p>1.Hover your cursor over <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0018.png" />icon<br />
                  </p>
                  <p>2. You will be displayed with all the notifications<br />
                  </p>
                  <p>3. On clicking any notification, you will be navigated to  that particular notification<br />
                  </p>
                  <p>4. Click Accept<br />
                  </p>
              <h4>How do I accept feedback  Requests from notifications?</h4>
                  <p>You will be able to accept feedback requests from the  notifications, by following the below steps:<br />
                  </p>
                  <p>1.Hover your cursor over <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0019.png" />icon<br />
                  </p>
                  <p>2. You will be displayed with all the notifications<br />
                  </p>
                  <p>3. Click accept in the feedback requests notifications<br />
                  </p>
                  <p>4. You will be displayed with Provide Feedback screen<br />
                  </p>
                  <p><strong>Note:</strong> You can  provide feedback only if you are linked<br />
                  </p>
              <h4>How do I accept Reference  Requests from notifications?</h4>
                  <p>You will be able to accept reference requests from the  notifications, by following the below steps:<br />
                  </p>
                  <p>1.Hover your cursor over <img width="23" height="23" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image001_0020.png" />icon<br />
                  </p>
                  <p>2. You will be displayed with all the notifications<br />
                  </p>
                  <p>3. Click accept in the reference requests notifications<br />
                  </p>
                  <p>4. You will be displayed with Provide reference screen<br />
                  </p>
                  <p><strong>Note:</strong> You can  provide reference only if you are linked<br />
                  </p>
              <h4>General Notifications</h4>
                  <p>You will be able to view the general notifications, by  following the below steps:<br />
                  </p>
                  <p>1. Hover your cursor over <img width="36" height="24" style="vertical-align: middle;" src="<?php echo IMAGE_PATH ?>/help-notification_clip_image005.png" />icon<br />
                  </p>
                  <p>2. You will be displayed with all the notifications<br />
                  </p>
                  <p>You will be able to view the general notifications, in the  below scenarios:
                  </p>
                  </p>
                  <div class="search">
                <ul>
                  <li>When  someone ok, comments or shares your wall posts and wishes</li>
                  <li>When  someone views your profile</li>
                  <li>When  someone supports your skills</li>
                  <li>When  someone provides you feedback</li>
                  <li>When  someone provides you reference</li>
              </ul>
                       </div>      	
            </div>	