<?php 
$this->headTitle()->prepend('Help');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
      <div class="help-content">
            	<div class="breadcrumb">
                	<ul>
                    	<li><a href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a></li>
                        <li>></li>
                        <li>Profile</li>
                    </ul>
                </div>
   	    <h3>Profile</h3>
                  <p>Your profile, is your collection of personnel information  such as skills, feedbacks, references, photos, links.<br />
                  </p>
              <h4>How  Do I View My Profile?</h4>
                  <p>You will be able to view your profile, by following the below  steps:<br />
                  </p>
                  <p>1. Click your name, towards the top right corner, under the  search<br />
                  </p>
                  <p>2. You will be able to navigate, through the various sections  of your profile, from the top bar<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click your name, towards the top right corner, under the  search<br />
                  </p>
                  <p>2. Click on View Profile in the sub navigation section<br />
                  </p>
              <h4>How  Do I View Others Profile?</h4>
                  <p>You will be able to view others profile, by following the  below steps:<br />
                  </p>
                  <p>Click on the name of other user<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1.<strong><u> Search</u></strong> for user in the text box provided  at the top right corner<br />
                  </p>
              <h4>How  Do I Edit Profile?</h4>
                  <p>You will be able to edit your profile, by following the below  steps:<br />
                  </p>
                  <p>1. Click on your name at the top right corner of the page.<br />
                  </p>
                  <p>2. Click on Edit Profile in the sub navigation section,  besides the <strong><u>Menu</u></strong><br />
                  </p>
                  <p>3. You will be displayed with all the headings in the sub  navigation, under the edit profile, by default the first heading will appear in  the editable mode<br />
                  </p>
                  <p>4. On selecting any heading from the sub navigation menu, the  heading will appear in the editable mode.<br />
                  </p>
                  <p>5. You will be able to edit the below headings from this  section:
                  </p>
                  </p>
                  <div class="search">
                <ul>
                  <li>Contact</li>
                  <li>Basic</li>
                  <li>Summary </li>
                  <li>Experience</li>
                  <li>Education</li>
                  <li>Skill</li>
                  <li>Languages</li>
                  <li>Personnel  Information</li>
                  <li>Additional  Information</li>
              </ul>
              </div>
        <h4>Notes</h4>
                                  <p>You can prepare notes corresponding to every profile, for  future reference. This section will help you to easily recall an event.<br />
                                  </p>
              <h4>How  do I view notes?</h4>
                  <p>You will be able to view notes, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name at the top right corner of the page.<br />
                  </p>
                  <p>2. Click on Notes in the sub navigation section, besides the <strong><u>Menu</u></strong><br />
                  </p>
              <h4>How  do I add notes?</h4>
                  <p>You will be able to add notes, by following the below steps:<br />
                  </p>
                  <p>1. Click on Links in the Black Bar.<br />
                  </p>
                  <p>2. You will be displayed with a listing, of your links<br />
                  </p>
                  <p>3. Click on the image, you will be able to view the short  profile view<br />
                  </p>
                  <p>4. Click on Notes, add a note<br />
                  </p>
                  <p>5. Click on Save Changes<br />
                  </p>
              <h4>How  do I edit notes?</h4>
                  <p>You will be able to edit notes, by following the below steps:<br />
                  </p>
                  <p>1. Click on Links in the Black Bar<br />
                  </p>
                  <p>2. You will be displayed with a listing, of your links<br />
                  </p>
                  <p>3. Click on the image, you will be able to view the short  profile view<br />
                  </p>
                  <p>4. Click on Notes, edit the note, <br />
                  </p>
                  <p>5. Click on Save Changes, the updated Note will be saved<br />
                  </p>
                  <p>OR<br />
                  </p>
                  <p>1. Click on your name, at the top right corner<br />
                  </p>
                  <p>2. Click on N (notes) in the middle navigation panel<br />
                  </p>
                  <p>3. You will be displayed with a listing of the notes saved<br />
                  </p>
                  <p>4. Click Edit, corresponding to the profile whose note, you  wish to edit<br />
                  </p>
                  <p>5. Click save towards the right hand side<br />
                  </p>
              <h4>How  do I delete a note?</h4>
                  <p>You will be able to delete notes, by following the below  steps:<br />
                  </p>
                  <p>1. Click on your name, at the top right corner<br />
                  </p>
                  <p>2. Click on N (notes) in the middle navigation panel<br />
                  </p>
                  <p>3. You will be displayed with a listing of the notes saved<br />
                  </p>
                  <p>4. Click Delete, corresponding to the profile whose note, you  wish to delete<br />
                  </p>
                  <p>5. You will be displayed with a pop up, click yes to delete<br />
                  </p>
              <h4>How  do I delete all my notes?</h4>
                  <p>You will be able to delete all the notes, by following the  below steps:<br />
                  </p>
                  <p>1. Click on your name, at the top right corner<br />
                  </p>
                  <p>2. Click on N (notes) in the middle navigation panel<br />
                  </p>
                  <p>3. You will be displayed with a listing of the notes saved<br />
                  </p>
                  <p>4. Click on the check box, provided at the top left corner  above the notes<br />
                  </p>
                  <p>5. You will be displayed with the delete option, click delete<br />
                  </p>
                  <p>6. You will be displayed with a pop up, click ok to continue  deletion<br />
            </p>
        <h4>Feedback</h4>
                  <p>Feedback is a great way to recognize the efforts of your  links. This lets you appreciate and validate the strengths found in your links. <br />
                  </p>
              <h4>How  do I Provide feedback?</h4>
                  <p>You will be able to provide feedback, by following the below  steps:<br />
                  </p>
                  <p>1. Click on the name of your link<br />
                  </p>
                  <p>2. You will be navigated to their profile, click on Feedback<br />
                  </p>
                  <p>3. Click on Give Feedback towards the top right corner, under  the feedback<br />
                  </p>
                  <p>3. You will be navigated to the provide feedback section<br />
                  </p>
                  <p>4. Select any of the links to whom, you wish to provide  feedback<br />
                  </p>
                  <p>5. Select their job title for which the feedback has to be  provided<br />
                  </p>
                  <p>6. Click on Provide Feedback<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click on the mail icon provided at  the top right corner of the page<br />
                  </p>
                  <p>2. Click on Inbox<br />
                  </p>
                  <p>3. Click on Feedback Requests<br />
                  </p>
                  <p>4. Click on      Provide Feedback<br />
                  </p>
                  <p>5. Select any of the links to whom, you wish to provide  feedback<br />
                  </p>
                  <p>6. Select their job title for which the feedback has to be  provided<br />
                  </p>
                  <p>7. Click on Provide Feedback<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click on Your Name<br />
                  </p>
                  <p>2. Click on Feedback in the middle navigation panel<br />
                  </p>
                  <p>3. Click on Provide Feedback under the Feedback section<br />
                  </p>
                  <p>4. Select any of the links to whom, you wish to provide  feedback<br />
                  </p>
                  <p>5. Select their job title for which the feedback has to be  provided<br />
                  </p>
                  <p>6. Click on Provide Feedback<br />
                  </p>
              <h4>How  do I view the feedback provided?</h4>
                  <p>In this section, you will be able to view the feedback  provided by you to your links, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Feedback Provided<br />
                  </p>
                  <p>4. You will be able to view the feedback provided to all the links  in the list view<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the feedback provided in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile.<br />
                  </p>
              <h4>How  do I view the received feedback?</h4>
                  <p>In this section, you will be able to view the feedback  received, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Feedback<br />
                  </p>
                  <p>4. You will be able to view the feedback received from all  your links <br />
                  </p>
                  <p>5. You will be able to view the name and job title of the  link, who has provided feedback, along with the feedback provided and your job  title for which the feedback is provided<br />
                  </p>
                  <p>6. You can click on accept/display towards the bottom right  hand side of the feedback, in order to display the feedback on your profile.<br />
                  </p>
                  <p>7. You can also <strong><u>Hide feedback</u></strong> and <strong><u>Delete feedback</u></strong> <br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the feedback received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The feedback is not displayed on your profile to other users,  until and till, you choose to accept and display the feedback
                  </p>
                  </p>
                <p><h4>How  do I view the pending feedback?</h4>
                  <p>All the feedbacks requested by your links, will be visible in  this section, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Click on Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Pending Feedback, under the Feedback<br />
                  </p>
                  <p>4. You will be able to view all the feedback requested by  your links in a list view, along with the message by your link. Click on Accept  &amp; Provide Feedback<br />
                  </p>
                  <p>4. You will be able to
                  </p>
                  </p>
                <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting  feedback</li>
                  <li>Type Text</li>
        </ul>
        </div>
                <p>5. Click on Provide Feedback<br />
        <h4>How  do I Request feedback?</h4>
                  <p>You will be able to request feedback to your links from this  section, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Click on Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Request Feedback, under the Feedback<br />
                  </p>
                  <p>4. You will be able to
                  </p>
                  </p>
                  <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting  feedback</li>
                  <li>Type Text</li>
                </ul>
                </div>
                <p>5. Click on Request Feedback<br />
                  </p>
                <p>Or<br />
                  </p>
                <p>1. Click on your name<br />
                  </p>
                <p>2. Click on feedback bar, in the profile section<br />
                  </p>
                <p>3. Click on Request feedback towards the top left corner, under  the feedback heading<br />
                  </p>
                <p>4. You will be able to</p>
                <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting  feedback</li>
                  <li>Type Text</li>
        </ul>
        </div>
                <p>5. Click on Request Feedback<br />
              <p><strong>Note:</strong> The  feedback requested by you to your links, will be visible to them in the Pending  Feedback section.<br />
              <h4>How  do I delete feedback?</h4>
                  <p>You can choose to delete the feedback, in case you feel that  the feedback is not appropriate, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Feedback, under the Feedback<br />
                  </p>
                  <p>4. You will be able to view the feedback received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the feedback<br />
                  </p>
                  <p>7. Click on Delete Feedback<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the feedback received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The feedback is not displayed on your profile to other users,  until and till, you choose to accept and display the feedback<br />
                  </p>
              <h4>How  do I display feedback?</h4>
                  <p>You can choose to accept &amp; display feedback, this option  enables you to display the feedback provided by your links on your profile, by  enabling this option others will also be able to view the feedback, when  viewing your profile<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Feedback<br />
                  </p>
                  <p>4. You will be able to view the feedback received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the feedback<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the feedback received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
              <h4>How  do I Hide feedback?</h4>
                  <p>You can choose to hide feedback from your profile, by  selecting this option feedback remains in the received section, but it will no  longer be displayed to others, viewing your profile<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Feedback<br />
                  </p>
                  <p>4. You will be able to view the feedback received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the feedback<br />
                  </p>
                  <p>7. Click on Hide Feedback<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the feedback received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The feedback is not displayed on your profile to other users,  until and till, you choose to accept and display the feedback<br />
                  </p>
              <h4>How  do I Un Hide feedback?</h4>
                  <p>You can choose to unhide or display  feedback on your profile, by selecting this option the feedback will again  start displaying on your profile, others will also be able to view the feedback,  by following the below steps<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Feedback in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Feedback<br />
                  </p>
                  <p>4. You will be able to view the feedback received from all  your links <br />
                  </p>
                  <p>6. Click on display towards the bottom right hand side of the  feedback<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view display, if you had previously hidden the feedback<br />
                  You will be able to view the feedback received in ascending  and descending order on the basis of the dates. On clicking the name of the  link, you will be navigated to their profile. <br />
                  </p>
              <h4>References</h4>
                  <p>iLook, enables you to provide references to your links, thus  helping your links to have better job opportunities. <br />
                  </p>
              <h4>How  do I Provide Reference?</h4>
                  <p>You will be able to provide Reference, by following the below  steps:<br />
                  </p>
                  <p>1. Click on the name of your link<br />
                  </p>
                  <p>2. You will be navigated to their profile, click on Reference<br />
                  </p>
                  <p>3. Click on Give Reference towards the top right corner, under  the Reference<br />
                  </p>
                  <p>3. You will be navigated to the provide Reference section<br />
                  </p>
                  <p>4. Select any of the links to whom, you wish to provide  Reference<br />
                  </p>
                  <p>5. Select their job title for which the Reference has to be  provided<br />
                  </p>
                  <p>6. Click on Provide Reference<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click on the       mail icon provided at  the top right corner of the page<br />
                  </p>
                  <p>2. Click on Inbox<br />
                  </p>
                  <p>3. Click on Reference Requests<br />
                  </p>
                  <p>4. Click on      Provide Reference<br />
                  </p>
                  <p>5. Select any of the links to whom, you wish to provide  Reference<br />
                  </p>
                  <p>6. Select their job title for which the Reference has to be  provided<br />
                  </p>
                  <p>7. Click on Provide Reference<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click on Your Name<br />
                  </p>
                  <p>2. Click on Reference in the middle navigation panel<br />
                  </p>
                  <p>3. Click on Provide Reference under the Reference section<br />
                  </p>
                  <p>4. Select any of the links to whom, you wish to provide  Reference<br />
                  </p>
                  <p>5. Select their job title for which the Reference has to be provided<br />
                  </p>
                  <p>6. Click on Provide Reference<br />
            </p>
        <h4>How  do I Request Reference?</h4>
                  <p>You will be able to request Reference to your links from this  section, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Click on Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Request Reference, under the Reference<br />
                  </p>
                  <p>4. You will be able to
                  </p>
                  </p>
                  <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting Reference</li>
                  <li>Type Text</li>
        </ul>
        </div>
                <p>5. Click on Request Reference<br />
                  </p>
                <p>Or<br />
                  </p>
                <p>1. Click on your name<br />
                  </p>
                <p>2. Click on Reference bar, in the profile section<br />
                  </p>
                <p>3. Click on Request Reference towards the top left corner, under  the Reference heading<br />
                  </p>
                <p>4. You will be able to</p>
                <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting Reference</li>
                  <li>Type Text</li>
        </ul>
        </div>
                <p>5. Click on Request Reference<br />
              <p><strong>Note:</strong> The  Reference requested by you to your links, will be visible to them in the  Pending Reference section.<br />
              <h4>How  do I delete Reference?</h4>
                  <p>You can choose to delete the Reference, in case you feel that  the Reference is not appropriate, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Reference, under the Reference<br />
                  </p>
                  <p>4. You will be able to view the Reference received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the Reference<br />
                  </p>
                  <p>7. Click on Delete Reference<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the Reference received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The Reference is not displayed on your profile to other  users, until and till, you choose to accept and display the Reference
                  </p>
                  </p>
                <h4>How  do I Hide/Unhide Reference?</h4>
                  <p>You can choose to unhide or display  Reference on your profile, by selecting this option the Reference will again  start displaying on your profile, others will also be able to view the  Reference, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Reference<br />
                  </p>
                  <p>4. You will be able to view the Reference received from all  your links <br />
                  </p>
                  <p>6. Click on display towards the bottom right hand side of the  Reference<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view display, if you had previously hidden the Reference<br />
                  You will be able to view the Reference received in ascending  and descending order on the basis of the dates. On clicking the name of the  link, you will be navigated to their profile. <br />
                  </p>
              <h4>How  do I display reference?</h4>
                  <p>You can choose to accept &amp;  display Reference, this option enables you to display the Reference provided by  your links on your profile, by enabling this option others will also be able to  view the Reference, when viewing your profile:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Reference<br />
                  </p>
                  <p>4. You will be able to view the Reference received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the Reference<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the Reference received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
              <h4>How  do I Hide Reference?</h4>
                  <p>You can choose to hide Reference from your profile, by  selecting this option Reference remains in the received section, but it will no  longer be displayed to others, viewing your profile<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Reference<br />
                  </p>
                  <p>4. You will be able to view the Reference received from all  your links <br />
                  </p>
                  <p>6. Click on accept &amp; display towards the bottom right  hand side of the Reference<br />
                  </p>
                  <p>7. Click on Hide Reference<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the Reference received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The Reference is not displayed on your profile to other  users, until and till, you choose to accept and display the Reference<br />
                  </p>
              <h4>How  do I view the reference provided?</h4>
                  <p>In this section, you will be able to view the Reference  provided by you to your links, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Reference Provided<br />
                  </p>
                  <p>4. You will be able to view the Reference provided to all the  links in the list view<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the Reference provided in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile.<br />
                  </p>
              <h4>How  do I view the received reference?</h4>
                  <p>In this section, you will be able to view the Reference  received, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name towards the top right corner<br />
                  </p>
                  <p>2. Select Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Received Reference<br />
                  </p>
                  <p>4. You will be able to view the Reference received from all  your links <br />
                  </p>
                  <p>5. You will be able to view the name and job title of the  link, who has provided Reference, along with the Reference provided and your  job title for which the Reference is provided<br />
                  </p>
                  <p>6. You can click on accept/display towards the bottom right  hand side of the Reference, in order to display the Reference on your profile.<br />
                  </p>
                  <p>7. You can also <strong><u>Hide Reference</u></strong> and <strong><u>Delete Reference</u></strong> <br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to view the Reference received in ascending and descending order on the  basis of the dates. On clicking the name of the link, you will be navigated to  their profile. <br />
                  </p>
                  <p>The Reference is not displayed on your profile to other  users, until and till, you choose to accept and display the Reference<br />
                  </p>
              <h4>How  do I view the pending reference?</h4>
                  <p>All the References requested by your links, will be visible  in this section, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Click on Reference in the middle navigation section<br />
                  </p>
                  <p>3. Click on Pending Reference, under the Reference<br />
                  </p>
                  <p>4. You will be able to view all the Reference requested by  your links in a list view, along with the message by your link. Click on Accept  &amp; Provide Reference<br />
                  </p>
                  <p>4. You will be able to
                  </p>
                  </p>
                  <div class="search">
                <ul>
                  <li>Select the link from dropdown</li>
                  <li>Select the Job title for which, you are requesting Reference</li>
                  <li>Type Text</li>
              </ul>
              </div>
              <p>5. Click on Provide Reference<br />
        <h4>Bookmarks</h4>
                  <p>You will be able to view the profiles, bookmarked in this section,  you can bookmark the profiles which you wish to view at a glance<br />
                  </p>
                  <p><strong>Note:</strong> This  section only appears if you have bookmarked any link<br />
                  </p>
              <h4>How  do I View Bookmarks?</h4>
                  <p>In this section, you will be able to view the profiles which  you have bookmarked, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
                  <p>Or<br />
                  </p>
                  <p>1. Click on Skills, in the <strong><u>Menu</u></strong><br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
              <h4>How  do I Add a Profile to Bookmark?</h4>
                  <p>You will be able to add profile to Bookmarks, by following  the below steps:<br />
                  </p>
                  <p>1. Click on the image of the link<br />
                  </p>
                  <p>2. You will be displayed with a short profile view pop up, Click on icon<br />
                  </p>
                  <p>3. The icon color will change to and the profile will  start getting displayed in the Bookmark section<br />
                  </p>
                  <p>OR<br />
                  </p>
                  <p>1. Click on the Name of your Link<br />
                  </p>
                  <p>2. You will be displayed with icon<br />
                  </p>
                  <p>3. On clicking the color will change to and the profile will start getting displayed in the bookmarks.<br />
                  </p>
              <h4>How  Do I Create Groups in Bookmark?</h4>
                  <p>You can also create groups and distinguish your links on the  basis of groups, by assigning your links to a specific group, by following the  below steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
                  <p>3. Click on Groups edit icon in the middle navigation panel, under Categories<br />
                  </p>
                  <p>4. You will be displayed with a pop up, add the name of the  group in the text box<br />
                  </p>
                  <p>5. Click on Add Group and the group will start getting  displayed in the middle navigation section<br />
                  </p>
              <h4>How  Do I add my links to a Group in Bookmark?</h4>
                  <p>You can assign your links to a particular group in iLook,  this will help you to easily distinguish your links, by following the below  steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
                  <p>3. Click on the check box corresponding to the image of the user.<br />
                  </p>
                  <p>4. Click on Manage<br />
                  </p>
                  <p>5. Click on Edit Group<br />
                  </p>
                  <p>6. You will be able to view a pop with the names of the  groups, click on the checkbox corresponding to the group.<br />
                  </p>
                  <p>7. Click Save<br />
                  </p>
                  <p><strong>Note: </strong>You will be  able to assign your links to more than one group at the same time.<br />
                  </p>
              <h4>How  Do I delete a Group in Bookmark?</h4>
                  <p>You will be able to delete a group from the Bookmarks  section, to delete a group, follow the below steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on icon corresponding to  the Groups, under the categories, in the middle navigation section<br />
                  </p>
                  <p>3. A pop up with all the groups  will open, you will be displayed with the cross mark corresponding to every  group<br />
                  </p>
                  <p>4. Click on the cross icon<br />
                  </p>
              <h4>How  Do I Rename a group from Bookmark?</h4>
                  <p>You will be able to rename your groups, by following the  below steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on icon corresponding to  the Groups, under the categories, in the middle navigation section<br />
                  </p>
                  <p>3. You will be displayed with a  listing of all the groups<br />
                  </p>
                  <p>4. Double click on the name of the  group <br />
                  </p>
                  <p>5. Click Save<br />
                  </p>
              <h4>How  Do I delete a Link from group?</h4>
                  <p>You can delete a link from a particular group, if you no  longer wish to view that link in a particular group, to do so:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on the group name, in the middle navigation section,  from which you wish to delete the link.<br />
                  </p>
                  <p>3 Select the links by clicking on the checkbox, corresponding  to the image of the user<br />
                  </p>
                  <p>4. Click on the Mange link provided at the towards the top  left corner of the screen<br />
                  </p>
                  <p>5. Click on Remove from Group<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to remove multiple users from the group, at the same time<br />
                  </p>
              <h4>How  Do I delete a Link from a bookmark?</h4>
                  <p>You can delete a link from a particular group, if you no  longer wish to view that link in a particular group, to do so:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
                  <p>3. Select the links by clicking on the checkbox,  corresponding to the image of the user<br />
                  </p>
                  <p>4. Click on the Mange link provided at the towards the top  left corner of the screen<br />
                  </p>
                  <p>5. Click on Remove from Bookmark<br />
                  </p>
                  <p><strong>Note:</strong> You will  be able to remove multiple or single user from the bookmark, at the same time<br />
                  </p>
              <h4>How  do I send message to multiple users at the same time from Bookmark?</h4>
                  <p>You can send messages to multiple users at the same time from  the bookmarks, you can do so:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on Bookmarks, in the middle navigation section<br />
                  </p>
                  <p>3. Select the links by clicking on the checkbox,  corresponding to the image of the user<br />
                  </p>
                  <p>4. Click on the Mange link provided at the towards the top left  corner of the screen<br />
                  </p>
                  <p>5. Click on send message<br />
                  </p>
                  <p>6. A pop up will be displayed where in you will be able to  enter the message<br />
                  </p>
                  <p>7. Click on Send<br />
                  </p>
              <h4>How  do I send message to multiple users at the same time from a particular Group?</h4>
                  <p>You can send messages to multiple users at the same time from  the bookmarks, by following the below steps:<br />
                  </p>
                  <p>1. Click on your name, towards the top right hand corner<br />
                  </p>
                  <p>2. Click on the group, in the middle navigation section<br />
                  </p>
                  <p>3. Select the links by clicking on the checkbox,  corresponding to the image of the links<br />
                  </p>
                  <p>4. Click on the Mange link provided at the towards the top  left corner of the screen<br />
                  </p>
                  <p>5. Click on send message<br />
                  </p>
                  <p>6. A pop up will be displayed where in you will be able to  enter the message<br />
                  </p>
                  <p>7. Click on Send<br />
                  </p>
              <h4>How  do I reassign a group to a link?</h4>
                  <p>You can also reassign a link to another group, by following  the below steps:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Select Bookmarks in the middle navigation section<br />
                  </p>
                  <p>3. Select the link by clicking on the checkbox corresponding  to their image<br />
                  </p>
                  <p>4. Click Manage<br />
                  </p>
                  <p>5. Click on Edit Group<br />
                  </p>
                  <p>6. You will be displayed with a pop, select the group, by  clicking on the checkbox, you wish to assign to the link. You can select  multiple groups at the same time.<br />
                  </p>
                  <p>7. Click Save<br />
                  </p>
              <h4>How  do I search in Bookmarks?</h4>
                  <p>You will be able to search for a link on the Bookmarks, you  can do so:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. You will be displayed with the search box towards the  right hand side<br />
                  </p>
                  <p>3. Enter the name<br />
                  </p>
              <h4>How  do I search in Groups?</h4>
                  <p>You will be able to search for a link in the group, you can  do so:<br />
                  </p>
                  <p>1. Click on your name<br />
                  </p>
                  <p>2. Click on the group<br />
                  </p>
                  <p>3. Enter the name<br />
                  </p>
                  <p>4. You will be displayed with the results from that  particular group<br />
                  </p>
              <h4>How  do I Download Profile?</h4>
            <p>You will be able to download the profile of your links,  by  following the below steps:<br />
        </p>
            <p>1. Click on the image of your link<br />
            </p>
            <p>2. You will be displayed with a short profile view pop up<br />
            </p>
            <p>3. Click on icon towards the top right hand side of the pop up<br />
            </p>
            <p>4. You will be displayed with an option to download either  the complete profile information or selected sections, by clicking on the  checkbox corresponding to the profile sections, updated by the user in their  profile<br />
            </p>
            <p>Or<br />
            </p>
            <p>1. Click on the Name of your link<br />
            </p>
            <p>2. You will be navigated to their profile<br />
            </p>
            <p>3. Click on the icon towards the right  hand side<br />
            </p>
            <p>4. You will be displayed with an  option to download either the complete profile information or selected  sections, by clicking on the checkbox corresponding to the profile sections,  updated by the user in their profile<br />
            </p>
            <p><strong>Note:</strong> In the download pop up only those sections will be visible,  in which the user has added their details.</p>
            <h5>How  do I upload My Profile Photo?</h5>
            <p>Your profile picture enables your links to recognize you on  iLook. You can upload the profile picture, by following the below steps:<br />
            </p>
            <p>1. Click on Upload in the navigation <strong>Menu, </strong>towards the left hand side  of the screen<br />
            </p>
            <p>2. You will be displayed with a pop up to upload a photo<br />
            </p>
            <p>3. You can browse a photo and click on the upload button to  upload the photo<br />
            </p>
            <p>4. Crop your photo, you can also view the preview towards the  top right corner of the pop up.<br />
            </p>
            <p>5. Click on set image.<br />
            </p>
            <h4>How  do I Edit My Profile Photo?</h4>
            <p>You can change your profile picture, by following the below  steps:<br />
            </p>
            <p>1. Click on edit in the navigation <strong>Menu, </strong>towards the left hand side  of the screen<br />
            </p>
            <p>2. You will be displayed with a pop up to upload a photo<br />
            </p>
            <p>3. You can browse a photo and click on the upload button to  upload the photo<br />
            </p>
            <p>4. Crop your photo, you can also view the preview towards the  top right corner of the pop up.<br />
            </p>
            <p>5. Click on set image.<br />
            </p>
            <p><strong>Note:</strong> Your  profile picture will be public by default <br />
            </p>
            <h4>How  do I Remove My Profile Photo?</h4>
            <p>You will be able to remove your profile photo, by following  the below steps:<br />
            </p>
            <p>1. Click on Remove, below the profile photo, in the <strong><u>Menu</u></strong> on the left hand side<br />
            </p>
            <p><strong>Note:</strong> You will  be able to view this option, only if the Menu is expanded<br />
            </p>
            <h4>How  Do I Add Cover photo?</h4>
            <p>You will be able to add cover photos, from <strong><u>My Profile</u></strong> section; you can navigate to this section by clicking on your name at the top  right corner of the screen or by clicking Profile in the Black Bar and then  clicking on <strong><u>View  Profile</u></strong><br />
            </p>
            <p>1. On hovering the cover photo, you will be able to view the icon towards the top  left corner of the screen.<br />
            </p>
            <p>2. When you click on the cover photo, you will be able to  view the text &ldquo;upload cover photo&rdquo; in the pop up.<br />
            </p>
            <p>3. When you click this text, you will be able to upload a photo  from your computer. You can reposition this photo, by dragging it, this will  help you to it the photo in frame. <br />
            </p>
            <p>4. Click Save<br />
            </p>
            <p>5. You can cancel uploading the photo, by clicking on the  Cancel button, under the photo. <br />
            </p>
            <h4>How  do I upload My Profile Photo?</h4>
            <p>Your profile picture enables your links to recognize you on  iLook<br />
            </p>
            <h4>How  do I Edit My Profile Photo?</h4>
            <p>You can change your profile picture, by following the below  steps:<br />
            </p>
            <p>1. Click on edit in the black bar<br />
            </p>
            <p>2. You will be displayed with a pop up to upload a photo<br />
            </p>
            <p>3. You can browse a photo and click on the upload button to  upload the photo<br />
            </p>
            <p>4. Crop your photo and click on the set image. You can also  view the preview towards the top right corner of the page.<br />
            </p>
            <p><strong>Note:</strong> Your  profile picture will be public by default <br />
            </p>
            <h4>How  do I Remove My Profile Photo?</h4>
            <p>You will be able to remove your profile photo, by following  the below steps:<br />
            </p>
            <p>1. Click on Remove, below the profile photo, in the <strong><u>Menu</u></strong> on the left hand side<br />
            </p>
            <p><strong>Note:</strong> You will  be able to view this option, only if the Menu is expanded<br />
            </p>
            <h4>How  Do I update status?</h4>
            <p>You will be able to update your status from <strong><u>General  Settings</u></strong> </p>
            <p><br />
            </p>
        </p>
      </div>	