<?php 
$this->headTitle()->prepend('Privacy Policy');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
<style>
.bot-link-content-hdr 
{
    margin: 0;
}
</style>
    <!-- Content Starts -->
    <div class="bot-link-content">

    <div class="bot-link-content-data">
    	<div class="bot-link-content-data-left text-purple2"><img src="<?php echo IMAGE_PATH?>/privacy-img.png" /></div>
        <div class="bot-link-content-data-right">
        
        	<div class="bot-link-content-hdr"><img src="<?php echo IMAGE_PATH?>/ilook-2.png" /></div>
       
       		
       		
        <!-- Col 1 -->
        	<div class="col1">
            	<div class="hdr text-purple2">1.	General</div>
                <p class="text-purple2">
                1.1	i-Sjn Solutions Ltd trading as iLook ("we" or "us") take the privacy of your information very seriously. Our Privacy and Data Protection Policy is designed to tell you, the user of our mobile application or website (together referred to as the "Service") about our practices regarding the collection, use and disclosure of personal and other information about you, your enterprise or your organisation that may be provided via this website (the "Site") or collected through other means such as an online form, email, or telephone communication. </p>
                <p class="text-purple2">
				1.2	This policy applies to information provided by our users, registered or otherwise.   
				</p>
				<p class="text-purple2">1.3	By using the Service, you are consenting to the collection, use, and disclosure of that information about you in accordance with, and are agreeing to be bound by, this Privacy and Data Protection Policy.</p>
				<p class="text-purple2">1.4	i-Sjn Solutions Ltd is registered under the Data Protection Act 1998 (the "Act"). The Act sets out a number of important principles that organisations must apply when processing personal data. For more information see <a target = '_blank' href = 'http://www.ico.org.uk/'>http://www.ico.org.uk/</a>.</p> 

				<div class="hdr text-purple2">2. Ways that we collect information</div> 
				<p class="text-purple2">2.1	We may collect and process the following personal information or data (information that can be uniquely identified with you) about you: </p>
				<p class="text-purple2 sub-p">2.1.1	information provided to register or subscribe with the Site; </p>
				<p class="text-purple2 sub-p">2.1.2	your username, gender, date of birth, photos and any content you may have created by your use of the Service</p>
				<p class="text-purple2 sub-p">2.1.3	information contained within your profile such as notes, references, and details of contacts;</p>
				<p class="text-purple2 sub-p">2.1.4	a record of links and comments that you have posted on the Service;</p>
				<p class="text-purple2 sub-p">2.1.5	payment information we may use to collect payment for a subscription;</p>
				<p class="text-purple2 sub-p">2.1.6	a record of any correspondence between you and us;</p>
				<p class="text-purple2 sub-p">2.1.7	replies to any surveys or questionnaires that we may use for research purposes; </p>
				<p class="text-purple2 sub-p">2.1.8	details of your visits to the Service and the resources that you access; </p>
				<p class="text-purple2 sub-p">2.1.9	any information we may require from you when you report a problem or complaint.</p>
				<p class="text-purple2">2.2	We only collect such information when you choose to supply it to us. You do not have to supply any personal information to us but our Service will not be operable in practice without providing data to us.</p>
				<p class="text-purple2">2.3	Information may also be gathered through the Site without you actively providing it, through the use of various technologies and methods such as Internet Protocol (IP) addresses and cookies. These methods do not collect or store personal information.</p>
				<p class="text-purple2">2.4	An IP address is a number assigned to your computer by your Internet Service Provider (ISP), so you can access the Internet. It is generally considered to be non-personally identifiable information, because in most cases an IP address can only be traced back to your ISP or the large company or organisation that provides your internet access (such as your employer if you are at work).</p>
				<p class="text-purple2">2.5	We use your IP address to diagnose problems with our server, report aggregate information, and determine the fastest route for your computer to use in connecting to our site, and to administer and improve the site.</p>
				
				
				
				<div class="hdr text-purple2">3.	Use </div>
				<p class="text-purple2">3.1	We may use this information to:</p>
				<p class="text-purple2 sub-p">3.1.1	ensure that any users are over 13 years of age; </p>
				<p class="text-purple2 sub-p">3.1.2	select a default profile photo for users based on their gender;</p>
				<p class="text-purple2 sub-p">3.1.3	ensure that the content of the Service is presented in the most effective manner for you and for your device and customise the Service to your preferences; </p>
				<p class="text-purple2 sub-p">3.1.4	provide services to you; </p>
				<p class="text-purple2 sub-p">3.1.5	assist in the administration of subscriptions;</p>
				<p class="text-purple2 sub-p">3.1.6	assist in making general improvements to our services;</p>
				<p class="text-purple2 sub-p">3.1.7	sell advertising space on the site;</p>
				<p class="text-purple2 sub-p">3.1.8	market services to users;</p>
				<p class="text-purple2 sub-p">3.1.9	carry out and administer any obligations arising from any agreements entered into between you and us;</p>
				<p class="text-purple2 sub-p">3.1.10	contact you and notify you about changes to our services or the services we offer (except where you have asked us not to do this);</p>
				<p class="text-purple2 sub-p">3.1.11	manage your account and provide you with customer support;</p>
				<p class="text-purple2 sub-p">3.1.12	analyse how our services are used.</p>
				
				<div class="hdr text-purple2">4.	Sharing your information</div>
				<p class="text-purple2">4.1	Users of the Service will be able to view any data posted on your public profile. You will be able to adjust the information registered and unregistered Users of the Service can view by adjusting your privacy settings within your profile.  </p>
				<p class="text-purple2">4.2	We do not disclose any information you provide to any third parties other than  as follows:</p>
				<p class="text-purple2 sub-p">4.2.1	Where you have opted to share any of your content with any other person, you authorise us to deliver that content via email, SMS or other electronic messaging or communication system; </p>
				<p class="text-purple2 sub-p">4.2.2	payment information may be provided to our payment processors;</p>
				<p class="text-purple2 sub-p">4.2.3	if we are under a duty to disclose or share your personal data in order to comply with any legal obligation (for example, if required to do so by a court order or for the purposes of prevention of fraud or other crime);</p>
				<p class="text-purple2 sub-p">4.2.4	in order to enforce any terms and conditions or agreements for our Services that may apply; </p>
				<p class="text-purple2 sub-p">4.2.5	we may transfer your personal information to a third party as part of a sale of some or all of our business and assets to any third party or as part of any business restructuring or reorganisation, but we will take steps with the aim of ensuring that your privacy rights continue to be protected;</p>
				<p class="text-purple2 sub-p">4.2.6	to protect the rights, property, or safety of i-Sjn Solutions Ltd, our users, or any other third parties. </p>
				<p class="text-purple2">4.3	Other than as set out above, we shall not disclose any of your personal information unless you give us permission to do so.</p>
				
				
				
				
				
				
				<div class="hdr text-purple2">5.	Security</div>
				<p class="text-purple2">5.1	In order to safeguard the information we collect from you we will take all reasonable steps to ensure that: </p>
				<p class="text-purple2 sub-p">5.1.1	our servers are protected by both hardware and software firewalls;</p>
				<p class="text-purple2 sub-p">5.1.2	our data processing storage facilities are sited in secure locations to prevent unauthorised access;</p>
				<p class="text-purple2 sub-p">5.1.3	all data stored on our server is encrypted through HTTP Secure, an industry standard encryption method that encrypts the data between your computer and our server so that in the event of your network being insecure no data is passed in a format that could easily be deciphered.</p>
				
				
				<div class="hdr text-purple2">6.	Access to and correction of personal information</div>
				<p class="text-purple2">6.1	You can review and update your personal information, or deactivate your account by accessing the account settings section within the Service.  </p>
				<p class="text-purple2">6.2	If you deactivate your account we will keep certain information for analytical purposes and to enforce our Terms of Use.  </p>
				<p class="text-purple2">6.3	We will take all reasonable steps in accordance with our legal obligations to update or correct personally identifiable information in our possession. </p>
				<p class="text-purple2">6.4	The Act gives you the right to access information held about you. Your right of access can be exercised in accordance with the Act. Any access request may be subject to a fee of &pound;10 to meet our costs in providing you with details of the information we hold about you. If you wish to see details of any personal information that we hold about you please contact us by way of our contact page.</p>
				
				<div class="hdr text-purple2">7.	Other websites</div>
				<p class="text-purple2">7.1	Our Site may contain links and references to other websites. Please be aware that this Privacy Policy does not apply to those websites.</p>
				<p class="text-purple2">7.2	We cannot be responsible for the privacy policies and practices of sites that are not operated by us, even if you access them via the Site and/or any other service that is operated by us. We recommend that you check the policy of each site you visit and contact its owner or operator if you have any concerns or questions.</p>
				<p class="text-purple2">7.3	In addition, if you came to this Service via a third party site, we cannot be responsible for the privacy policies and practices of the owners or operators of that third party site and recommend that you check the policy of that third party site and contact its owner or operator if you have any concerns or questions.</p>
				
				<div class="hdr text-purple2">8.	Transferring your information outside of Europe</div>
				<p class="text-purple2">8.1	As part of the services offered to you the information you provide to us may be transferred to, and stored at, countries outside of the European Union ("EU"). By way of example, this may happen if any of our servers are from time to time located in a country outside of the EU or one of our service providers is located in a country outside of the EU. We may also share information with other equivalent national bodies, which may be located in countries worldwide. These countries may not have similar data protection laws to the UK. If we transfer your information outside of the EU in this way, we will take steps with the aim of ensuring that your privacy rights continue to be protected as outlined in this privacy policy.</p>
				<p class="text-purple2">8.2	If you use our Service while you are outside the EU, your information may be transferred outside the EU in order to provide you with those services.</p>
				<p class="text-purple2">8.3	By submitting your personal information to us you agree to the transfer, storing or processing of your information outside the EU in the manner described above.</p>
				
					
				<div class="hdr text-purple2">9.	Notification of changes to our Privacy Policy</div>
				<p class="text-purple2">We will post details of any changes to our Privacy Policy on the Site or the App to help ensure you are always aware of the information we collect, how we use it, and in what circumstances, if any, we share it with other parties.</p>
					
				<div class="hdr text-purple2">10.	Policy towards children</div>
				<p class="text-purple2">The Service is not available to individuals under 13. Our policy is not to intentionally or knowingly collect, process, maintain or use personal information from any individual under the age of 13. 	</p>
				
				
				
				<div class="hdr text-purple2">11.	Contact us</div>
				<p class="text-purple2">If at any time you would like to contact us with your views about our privacy practices, or with any enquiry relating to your personal information, you can do so by way of our contact page.</p>
				
				
				</div>
            <!-- Col 1 -->
        </div>
    	
    </div>
  </div>
    <!-- Content Ends -->