<?php 
$this->headTitle()->prepend('Terms');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/pages.css" );
?>
<style>
.bot-link-content-data-left 
{
    transform: rotate(-90deg); 
 	-webkit-transform: rotate(-90deg); 
 	-moz-transform: rotate(-90deg); 
 	-ms-transform: rotate(-90deg);
 	-o-transform: rotate(-90deg);
 	filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3);
}




/* .bot-link-content-data-right .col1 p  */
/* { */
/*     width: 95%; */
/* } */

.bot-link-content-data-right p 
{
    width: 95%;
}
</style>
    <!-- Content Starts -->
    <div class="bot-link-content">

    <div class="bot-link-content-data">
    	<div class="bot-link-content-data-left text-purple2">Terms</div>
        <div class="bot-link-content-data-right">
        
        	<div class="bot-link-content-hdr"><img src="<?php echo IMAGE_PATH?>/ilook-2.png" /></div>
       
       		<p>These Terms and Conditions govern your use of this website <a href = 'http://www.ilook.net'>https://www.ilook.com</a> and any app or other electronic service offered by us (together the "Site") and your relationship with i-Sjn Solutions Ltd ("we", "us" or "i-Sjn Solutions"). Please read these terms carefully as they affect your rights and liabilities under the law. </p>
			<p>The Website, app and other services provided by us via any technology or media shall together be referred to as the "Service"</p>
			<p>If you do not agree to these Terms and Conditions, please do not use the Service or the Site, or register as a user.</p>
			<p>Please also see our <u><a href = '/<?php echo PROJECT_NAME?>page/privacy-policy'>Privacy and Data Protection Policy</a></u> for information about how we collect and use your personal data.</p>
       		
       		
        <!-- Col 1 -->
        	<div class="col1">
            	<div class="hdr text-purple2">1.	Introduction</div>
                <p class="text-purple2">
                1.1	This Service provides a social networking tool, which allows individuals from around the globe to connect with each other enabling them, amongst other things, to share information about their education, careers, experiences and skills and to build up a network of relationships in order to advance career opportunities and communicate easily with employers and other professionals. The Service is mainly aimed at students, recruiters and professionals however the Service is open to all individuals who wish to share information with each other. 
                </p>
                <p class="text-purple2">
				1.2	These terms will apply to registered members and those who simply view the Site ("you"). 
				</p>
				<p class="text-purple2">1.3	By using the Site and the Service, you agree to be bound by these Terms of Use.</p>
				<p class="text-purple2">1.4	You are responsible for ensuring that all persons who use the Service through your mobile device or internet connection are aware of these Terms of Use, and that they comply with them.</p> 
<p class="text-purple2">1.5	If you are accepting these Terms and Conditions on behalf of an enterprise, organisation or business then you agree and accept that these Terms and Conditions will be binding on all personnel who use the Service of the Site on behalf of that enterprise, organisation or business.</p>
<p class="text-purple2">1.6	Please note that these terms and conditions may be amended from time to time. Notification of any changes will be made by posting new terms onto the Site. In continuing to use the Site you confirm that you accept the then current terms and conditions in full at the time you use the Site. If you do not accept terms and conditions which we have varied then you must cancel your registration or subscription within 30 days of such change being made and the previous terms will continue to apply pending termination. If you continue to use the Service without notifying us of your objections within 30 days you will be deemed to have accepted the varied Terms and Conditions.</p>
	
	<div class="hdr text-purple2">2.	Registration</div> 
				<p class="text-purple2">2.1	You must register on the Site with your name and email address in order to use the Service. These details must also be verified. </p>
				<p class="text-purple2">2.2	Registered Individuals and recruiters will together be referred to as "Users". </p>
				<p class="text-purple2">2.3	To use the Services, you must be 13 years or older. Our Services are not directed to persons under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to remove such information and terminate the child's account.</p>
				<p class="text-purple2">2.4	When you register as a User we will ask for some of your personal information. Any personal information you provide to us will be handled in accordance with our Privacy and Data Protection Policy, which can be viewed here <b><a href = '/<?php echo PROJECT_NAME?>page/privacy-policy'>Privacy Policy</a></b>.</p>
				<p class="text-purple2">2.5	If you register to use the Site you will be asked to create a password. In order to prevent fraud, you must keep this password confidential and must not disclose it or share it with anyone. If you know or suspect that someone else knows your password you should notify us by contacting <a href = 'mailto:admin@iLook.net'>admin@iLook.net</a>  and change your password immediately.</p>
				<p class="text-purple2">2.6	If we have reason to believe that there is likely to be a breach of security or misuse of the Service or the Site through your account or the use of your password or unauthorised access to one of your third party services that we link to, we may require you to change your passwords on our system and with your other suppliers, or we may suspend your account. Until you have changed all your passwords or we have reactivated your account you will not be able to access the Service.</p>
				<p class="text-purple2">2.7	Users may not solicit login information or access to an account belonging to another individual.</p>
				<p class="text-purple2">2.8	You agree that all information that you supply to us will be accurate, complete and kept up to date at all times. We may use the information provided to us to contact you.</p>
				<p class="text-purple2">2.9	We reserve the right to cancel your registration at any time and for any reason.</p>
				
				<div class="hdr text-purple2">3.	Sharing and Messages</div>
				<p class="text-purple2">3.1	The Services allow for the sharing of information in various ways through your profile, use of the dashboard and display walls, job postings, notes and internal messages. </p>
				<p class="text-purple2">3.2	Information and content which you share or post may be seen by other Users or if made public, by visitors to the Site. </p>
				<p class="text-purple2">3.3	Where such settings are available, you may choose to limit who can view content or information by altering your privacy settings. Activities such as making a job application and sending internal mail to your links are private and only viewable by you and the addressee(s).</p>
				
				<div class="hdr text-purple2">4.	Profiles</div>
				<p class="text-purple2">4.1	You are responsible for the information displayed on your profile.</p>
				<p class="text-purple2">4.2	You are not entitled to allow any other person to use or borrow your profile - any other person wishing to become a member must register separately and create their own profile.</p>
				<p class="text-purple2">4.3	You are not entitled to impersonate anybody else or otherwise provide misleading information. </p>
				<p class="text-purple2">4.4	The information that you place on your public profile (other than sensitive personal information such as your email address, date of birth and precise location) will be viewable by all other Users.</p>
				
				<div class="hdr text-purple2">5.	Subscription</div>
				<p class="text-purple2">5.1	The Services are available to all users free of charge; however we may in the future charge you for the use of the Services. We will notify you in advance of any charges that may be incurred and you will have the opportunity to terminate your agreement with us before incurring any charges. </p>
				
				<div class="hdr text-purple2">6.	Parental Guidance</div>
				<p class="text-purple2">6.1	Certain content on the Site may not be suitable for children. If you permit a child to access the Site, you are solely responsible for deciding whether the content on the Site is appropriate for that child to view. </p>
				
				<div class="hdr text-purple2">7.	Acceptable Use Policy</div>
				<p class="text-purple2">7.1	The Service and Site are provided for legitimate personal, business, professional and social purposes. You must not use the Service or the Site for any illegal, unethical or immoral purposes. We reserve the right to remove any account at our discretion at any time, without giving reasons if we suspect that an account is being operated in breach of these Terms and Conditions.</p>
				<p class="text-purple2">7.2	We grant you a limited licence to access and make personal use of the Site and the Service, but not to download (other than page caching) or modify the Site or any software which we use to operate the Service, or any portion of it, except with our express written consent.  </p>
				<p class="text-purple2">7.3	You agree that you will not:</p>
				<p class="text-purple2">7.3.1	Solicit log-in information or access an account belonging to someone else.</p>
				<p class="text-purple2">7.3.2	Bully, intimidate, or harass any user of the Site or the Service.</p>
				<p class="text-purple2">7.3.3	Do anything unlawful, misleading, malicious, or discriminatory using the Service or the Site.</p>
				<p class="text-purple2">7.3.4	Do anything to suggest, express or imply that statements made by you are endorsed by us.</p>
				<p class="text-purple2">7.3.5	Impersonate any other person whether or not that other person is a user of the Site or the Service.</p>
				</p>
				
				<div class="hdr text-purple2">8.	Advertising and Commercial Use</div>
				<p class="text-purple2">8.1	Users of the Site are not entitled to directly advertise to or solicit the custom of other users without our express written consent.</p>
				<p class="text-purple2">8.2	You are not entitled to resell or commercially exploit the Site's contents other than content you have posted. You are not entitled to use any data mining, robots, or similar data gathering and extraction tools to collect user names, e-mail addresses or any other data for the purposes of sending unsolicited e-mail or for any other use. </p>
				<p class="text-purple2">8.3	In the event that you are found by us to have been sending unsolicited e-mail to our users in contravention of the Privacy and Electronic Communications Regulations 2003 having taken their address from our Site then we reserve the right to terminate without notice your use of the Site without limiting any other rights and remedies we may have.</p>
				
				<div class="hdr text-purple2">9.	Disputes and Harassment</div>
				<p class="text-purple2">You will be responsible for communications with other users. If a dispute arises between users of the Site then we reserve the right to adjudicate such dispute and take such action as we consider necessary. Please note that we are under no obligation to adjudicate any such dispute. Please also note that we do not screen users or subscribers.</p>
					
				<div class="hdr text-purple2">10.	Content</div>
				<p class="text-purple2">10.1	The Service allows for Users to create content to be distributed by the Service. Any content which is distributed by the Service or which you integrate with the Service (for instance by placing an "iLook" hyperlink within your own content),  which we refer to as "Content" in these terms must comply with our content standards, which are set out in this clause 10.</p>
				<p class="text-purple2">10.2	You agree that any Content which will be integrated with the Service or distributed by the Service will be your own creation or will be Content which you are entitled to use and will not be used in breach of any intellectual property rights;</p>
				<p class="text-purple2">10.3	Any Content will be your personal responsibility. You will be personally liable for all claims relating to defamation, breach of intellectual property, privacy or any other claim arising from your Content.</p>
				<p class="text-purple2">10.4	You agree to indemnify us in relation to any liability we may suffer as a result of any claims relating to defamation, breach of intellectual property, privacy or any other claim arising from your Content.</p>
				<p class="text-purple2">10.5	You agree that you will not publish any offensive, inaccurate, misleading, defamatory, fraudulent or illegal Content. </p>
				<p class="text-purple2">10.6	In particular you agree not to use the Site or the Service to distribute any Content which:</p>
				<p class="text-purple2">10.6.1	promotes racism, bigotry, hatred or physical harm of any kind against any group or individual; </p>
				<p class="text-purple2">10.6.2	harasses any person or advocates harassment of any person; </p>
				<p class="text-purple2">10.6.3	displays or promotes pornographic or sexually explicit material of any kind; </p>
				<p class="text-purple2">10.6.4	does anything or promotes any conduct that is abusive, threatening, obscene, defamatory or libellous;</p>
				<p class="text-purple2">10.6.5	is illegal, infringes intellectual property rights, defames any person, breaches confidentiality or promotes any illegal activities;</p>
				<p class="text-purple2">10.6.6	promotes illegal or unauthorized copying of another person's copyright work, such as providing pirated computer programs or links to them, providing information to circumvent manufacturer-installed copy protect devices, or providing pirated music or links to pirated music files; </p>
				<p class="text-purple2">10.6.7	provides instruction  information about illegal activities, such as making or buying illegal weapons, violating someone else's privacy or providing or creating computer viruses;</p>
				<p class="text-purple2">10.6.8	solicits passwords or personally identifying information from other users for commercial or unlawful purposes; </p>
				<p class="text-purple2">10.6.9	involves the transmission of "junk mail", "chain letters" or unsolicited mass mailing or "spamming";</p>
				<p class="text-purple2">10.6.10	promotes information that you know to be false or misleading;</p>
				<p class="text-purple2">10.6.11	contains personal information e.g. names or contact details (unless permission has been sought from the holder of the relevant personal information); or </p>
				<p class="text-purple2">10.6.12	engages in commercial activities and/or sales, such as contests, sweepstakes, barter, advertising and pyramid schemes.</p>
				<p class="text-purple2">10.7	By creating or integrating your Content with the Service you agree that we will be entitled to use such Content for the purposes of delivering the Service. We reserve the right to investigate and remove any Content at any time and for any reason.</p>
				
				<div class="hdr text-purple2">11.	Viruses, hacking and other offences</div>
				<p class="text-purple2">11.1	You agree not to upload any files or post, distribute publish any files on the Site or using the Service that contain viruses, corrupted files, or malicious code or any other similar software or programs that may damage the operation of another's computer.</p>
				<p class="text-purple2">11.2	You must not misuse our Site or the Service by knowingly introducing viruses, trojans, worms, logic bombs or other material which is malicious or technologically harmful. You must not attempt to gain unauthorised access to our Site or the Service, the server on which our site is stored or any server, computer or database connected to the Site or Service. You must not attack our Site or the Service via a denial-of-service attack or a distributed denial-of service attack. </p>
				<p class="text-purple2">11.3	By breaching this provision, you would commit a criminal offence under the Computer Misuse Act 1990. We will report any such breach to the relevant law enforcement authorities and we will co-operate with those authorities by disclosing your identity to them. In the event of such a breach, your membership and right to use our Site will cease immediately.</p>
				<p class="text-purple2">11.4	We will not be liable for any loss or damage caused by viruses, a distributed denial-of-service attack or other technologically harmful material that may infect your computer equipment, computer programs, data or other proprietary material due to your use of our Site or the Service or to your downloading of any material posted on it, or on any website linked to it.</p>
				
				<div class="hdr text-purple2">12.	Availability </div>
				<p class="text-purple2">12.1	Although we aim to offer you the best service possible, we make no promise that our Service will meet your requirements. We cannot guarantee that the Service will be fault-free. If a fault occurs with the Site or the Service you should report it to <a href = 'mailto:admin@iLook.net'>admin@iLook.net</a>  and we will attempt to correct the fault as soon as we reasonably can.</p>
				<p class="text-purple2">12.2	Your access to the Service may be occasionally restricted or interrupted to allow for repairs, maintenance or the introduction of new facilities or services or because we are unable to offer the Service for reasons beyond our control (such as a denial of service attack). In this event we will attempt to restore the service as soon as we reasonably can. Access to the Site may be restricted whether or not you have registered with us. Any such restrictions or interruptions shall not constitute a breach by us of these terms.</p>
				
				<div class="hdr text-purple2">13.	Our Liability</div>
				<p class="text-purple2">13.1	We will operate the Site with the reasonable skill and care of an online service provider. Services provided do not extend to detailed monitoring or supervision of content, membership or contacts and communications between users of the Site. </p>
				<p class="text-purple2">13.2	Our liability is limited to the fullest extent permitted by law.</p>
				<p class="text-purple2">13.3	From time to time it may be necessary to suspend access to the Site for a period of time and any such interruptions shall not constitute a breach by us of these terms. Our liability to you for breach of contract will be strictly limited to the subscription price (if any) actually paid by you to us. </p>
				<p class="text-purple2">13.4	The Service may allow its members to distribute Content and use the Service without detailed oversight or monitoring. While we put systems in place to allow for users and other third parties to report harassment, improper use of the Service and distribution of offensive, inaccurate, misleading, defamatory, fraudulent or illegal Content, we do not make any warranties or guarantees in relation to use of the Service and the Site. If we are legitimately informed of any abuse or infringement of these terms in accordance with clause 18 we will attempt to resolve the matter and we may delete the relevant account and/ or removing inappropriate content as soon as we can.</p>
				<p class="text-purple2">13.5	We will not be liable for any business, financial, or economic loss nor for any consequential or indirect loss (such as lost reputation, lost profit or lost opportunity) arising as a result of your use of the Site whether such loss is incurred or suffered as a result of our negligence or otherwise. We will not be liable if content you have posted and stored on the Site is lost, corrupted or damaged.</p>
				<p class="text-purple2">13.6	Nothing in these terms will limit our liability for fraud or for death or personal injury caused as a result of our negligence.</p>
				
				<div class="hdr text-purple2">14.	Cancellation and Termination </div>
				<p class="text-purple2">14.1	On receipt of an email from you to us cancelling your membership we will delete your member profile, terminate your membership and delete any content on the site after 30 days (the "<b>Cancellation Period</b>") of receiving your notification. Please note that content may continue to be accessible in search engine caches or on other sites and we cannot agree to delete such content.</p>
				<p class="text-purple2">14.2	You may still access and re-activate your account during the Cancellation Period. You will however be unable to reactivate your account after the Cancellation Period has passed and will need to re-register with the Site in the event that you wish to use the Services again. We will not be liable for any loss of your information once your membership is terminated. </p>
				<p class="text-purple2">14.3	We reserve the right to terminate your membership immediately without notice if in our opinion you have breached these terms and your member profile and any content on the site will be deleted.</p>
				<p class="text-purple2">14.4	Any subscription charges we have taken in advance will be refundable (less one month) in the event of cancellation by you. </p>
				
				<div class="hdr text-purple2">15.	Data Protection Policy</div>
				<p class="text-purple2">15.1	We request that all information included in your member profile is accurate, current and complete.</p>
				<p class="text-purple2">15.2	All notices sent to you will be sent to the email address provided with your registration details (as updated by you). By accepting these terms you give your consent to receive communications from us by email and you agree that all agreements, notices, disclosures and other communications that we provide to you by email satisfy any legal requirement that such communications be in writing. </p>
				<p class="text-purple2">15.3	Any information and content posted onto the Site including sensitive and personal information is publicly available and by posting any such content you are expressly consenting to its public display.</p>
				<p class="text-purple2">15.4	Personal information that you supply to us will not be disclosed by us to any third party without your consent. You agree that we may use the personal information supplied by you in order to carry out our responsibilities as set out in these terms including:</p>
				<p class="text-purple2">15.4.1	sending notices to you;</p>
				<p class="text-purple2">15.4.2	sending any communications to you that you have agreed to receive;</p>
				<p class="text-purple2">15.4.3	contacting you if we are asked to do so by another user or member of the public; </p>
				<p class="text-purple2">15.4.4	processing subscription payments from you;</p>
				<p class="text-purple2">15.4.5	any other use of the information for which we obtain your consent.</p>
				
				<div class="hdr text-purple2">16.	Other Sites</div>
				<p class="text-purple2">The Site may include links to other web sites or material which are beyond its control. We are not responsible for content on any site outside the Site.  </p>
				
				<div class="hdr text-purple2">17.	Intellectual Property</div>
				<p class="text-purple2">17.1	The format and content of this Site is protected by United Kingdom and international copyright and we reserve all rights in relation to our copyright whether owned or licensed to us and all rights are reserved to any of our registered and unregistered trademarks (whether owned or licensed to us) which appear on this Site.  </p>
				<p class="text-purple2">17.2	By displaying content on this site you expressly grant a licence to us to display the content and to use it for any of our other business purposes and you agree to indemnify us in relation to any liability we may suffer as a result of the publication of any defamatory, misleading or offensive content.</p>
				<p class="text-purple2">17.3	We do not screen content or information on the Site and we cannot give any assurance as to its accuracy or completeness. Users of this Site are expressly asked not to publish any defamatory, misleading or offensive content or any content which infringes any other persons intellectual property rights (e.g. copyright). Any such content is contrary to our policy and we do not accept liability in respect of such content. The User responsible will be personally liable for any damages or other liability arising as a result of such content.</p>
				<p class="text-purple2">17.4	If you believe that any content on the Site contains a defamatory statement, is offensive or is in breach of intellectual property or other rights, please notify us immediately at <a href = 'mailto:admin@iLook.net'>admin@iLook.net</a> and we will make all reasonable endeavours to remove the relevant content within a reasonable time. If content posted by you is removed you must not re-post the content.</p>
				<p class="text-purple2">17.5	This website or any portion of this website may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without our express written consent. You may not systematically extract and/or re-utilise parts of the contents of the Site without our express written consent. In particular, you may not utilise any data mining, robots, or similar data gathering and extraction tools to extract (whether once or many times) for re-utilisation of any substantial parts of this Site without our express written consent. </p>
				
				<div class="hdr text-purple2">18.	Notice and Take-Down</div>
				<p class="text-purple2">18.1	We will make all reasonable efforts to delete accounts which are being used in breach of our terms and conditions and to identify and remove Content that is defamatory or infringing on intellectual property rights when we are notified but we cannot be responsible if you have failed to provide the relevant information.</p>
				<p class="text-purple2">18.2	In the event that you believe that an account is being used in an inappropriate manner or that any Content which is distributed using the Service is defamatory or infringing on intellectual property rights you should notify us in writing either by email to <a href = 'mailto:admin@iLook.net'>admin@iLook.net</a> or using our Site online enquiry form including the following:</p>
				<p class="text-purple2">18.2.1	Your full name and contact details, including postal address, telephone number and e-mail address;</p>
				<p class="text-purple2">18.2.2	The exact URL at which the defamatory or infringing Content appears;</p>
				<p class="text-purple2">18.2.3	The Content that you believe is defamatory or infringing on intellectual property rights;</p>
				<p class="text-purple2">18.2.4	The reasons that you believe the Content is defamatory or infringing on intellectual property rights;</p>
				<p class="text-purple2">18.2.5	A statement confirming that you are authorised to act on behalf of the claimant or rights holders; and</p>
				<p class="text-purple2">18.2.6	A signed declaration truth in respect of the information in the notice.</p>
				<p class="text-purple2">18.3	Any statement made under this clause 18 may be used in court proceedings.</p>
				
				<div class="hdr text-purple2">19.	International Use</div>
				<p class="text-purple2">19.1	You shall comply with all foreign and local laws and regulations which apply to your use of our Site in whatever country you are physically located, including without limitation, consumer law, export control laws and regulations.</p>
				
				<div class="hdr text-purple2">20.	General</div>
				<p class="text-purple2">20.1	These conditions are governed by and construed in accordance with the laws of England and Wales. You agree, as we do, to submit to the non-exclusive jurisdiction of the English courts.</p>
				<p class="text-purple2">20.2	If you breach these terms and conditions and we decide to take no action or neglect to do so, then we will still be entitled to take action and enforce our rights and remedies for any other breach.</p>
				<p class="text-purple2">20.3	We will not be responsible for any breach of these Terms and Conditions caused by circumstances beyond our reasonable control.</p>
				<p class="text-purple2">20.4	We may make changes to the format of the Site, services provided or to the Site's content at any time without notice.</p>
				
				
				</div>
            <!-- Col 1 -->
            

                   
        </div>
    	
    </div>
  </div>
    <!-- Content Ends -->