<?php
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/investors_look.css" );
?>

<!-- Header Ends -->
<!-- Content Starts -->

    <div class="bot-link-content">
        <div class="bot-link-content-data">
            <div class="create-pwd font-change" >
                <div class="tracker-hdrlink">Investor&#39;s look on ilook </div>
               <div class="tracker-img"> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/5m.jpg"></div>
                <div class="tracker-data">
               <p>Dear iLooker,</p>

                <ul>
                    <li><img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	iLook team is extremely happy to announce that iLook has drawn the attention of London Angel Investor.</li>

                    <li> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	iLook has signed a deal with the investor for 5 Million USD. Thereby making iLook one of the million dollar companies in the world.</li>

                    <li> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	The CEO has assured that with his excellent proposed Business model, the company will be in profit within 5 years and also assured investors with high returns.</li>

                    <li> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	All the other details are kept confidential at present and will be announced once the legal formalities are complete.</li>

                    <li> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	iLook is based in UK now and as a next step, iLook will set up their Development Centre in India. The company is analysing the pros and cons on various IT cities of India for their new office set up such as Chennai, Hyderabad, Bangalore, Chandigarh & Gurgaon.</li>

                    <li> <img src="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>/public/images/arrow.jpg">	Follow iLook’s Facebook page for more updates in few days for announcement.
               </li>
                </ul>
               <p> Thanks for being a part of iLook Family. Keep Looking in iLook.</p>

               <p> - iLook Team</p>
                    </div>

            </div>
        </div>
    </div>

<!-- Content Ends -->
