
<?php
/* Including JS */
//$this->headScript()->appendFile( PUBLIC_PATH."/js/backend/jquery.dataTables.js" );
$this->headScript()->appendFile( "//code.jquery.com/jquery-1.11.1.min.js" );
$this->headScript()->appendFile( "//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js" );
//$this->headScript()->appendFile( PUBLIC_PATH."/js/backend/data_tables.js" );
/* Including CSS */
$this->headLink()->appendStylesheet( "//cdn.datatables.net/1.10.7/css/jquery.dataTables.css" );
//$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/backend/dataTables.css" );


?>
<style>
table, th, td {
   border: 1px solid #8a73ac;
} 

table {
    border-collapse: collapse;
}
th {
    text-align: centre;
}

td {
    height: 20px;
    vertical-align: bottom;
	padding : 15px;
}
</style>
<script>
$(document).ready(function() {
	$('#example').dataTable( {
		"bProcessing": true,
		"bServerSide": true,
		"sAjaxSource": "/" + PROJECT_NAME + "/development/data-table-records",
		"aoColumns" : [
					{
		       			"mDataProp" : "checkbox",
		       			"bSearchable" : false,
		       			"bSortable": false
					},
		       		{
		       			"mDataProp" : "name",
		       			"bSearchable" : true,
		       			"bSortable": true
		       		}
		       	],
		       	"fnServerData" : function(sSource, aoData, fnCallback) {
		    		var url = sSource;
		    		var data = aoData;
		    		var success = fnCallback;
					AJAXCaller(url,data,success);
		    	},
		    	"fnDrawCallback": function(oSettings, json)
				{
					$("div#tableDiv input.datatableCB").click(function(){
						isallChecked();
					});	
					isallChecked();
				}
		
	} );
} );

/**
 * Function used to check/uncheck all the checkboxes !
 * 
 * @author Jaskaran Singh
 * @since ''
 * @version 1.0
 */
function isallChecked() {
    if (!$('div#tableDiv input.datatableCB:not(:checked)').length == true) // Is all checked
    {
        $("div#tableDiv input#checkAll").prop('checked', true);
    } else {
        $("div#tableDiv input#checkAll").prop('checked', false);
    }
}
</script>

<table id="example" width="100%" cellspacing="0" cellpadding="0" border="0" class="display">
<thead>
<tr>
<th><input id="checkAll" type="checkbox" value=""></th>
<th>Name</th>

</tr>
</thead>

<tfoot>
<tr>
<th></th>
<th>Name</th>


</tr>
</tfoot>
</table>

