<?php
$this->headTitle ()->prepend ( 'R & D' );
?>
<!-- <script type="text/javascript">

document.write(strip("<span> hello<p>world</p></span>"));

</script>
<div id='temp_uploads_info'></div>
<form
	action="/<?php echo PROJECT_NAME ?>enquiry/move-uploaded-files-to-temp-location"
	class="dropzone"></form>-->

<div id="MonsterJobSearchResultPlaceHoldervH0AAA_e_e" class="xmns_distroph"></div>
<script type="text/javascript">
(function() {
  var oScript = document.createElement('script');
  oScript.type = 'text/javascript';
  oScript.async = true;
  oScript.src = ('https:' == document.location.protocol ? 'https://' : 'http://') + 'publisher.monster.com/Services/WidgetHandler.ashx?WidgetID=EAAQAU1UhksDtOpdQp0Xe58yaPFait9MiUJGJlIzWQA62CM-&Verb=Initialize';
  var oParent = document.getElementsByTagName('script')[0];
  oParent.parentNode.insertBefore(oScript, oParent);
})();
</script>
<a id="monsterBrowseLinkvH0AAA_e_e" class="monsterBrowseLink fnt4" href="http://jobsearch.monster.com/jobs/">View More Job Search Results</a>
