<?php 

$this->headTitle()->prepend('News');

$news_arr2 = new \Zend_Session_Namespace('News_arr2');
// if(!isset($news_arr2->list)){
	$this->headScript()->appendFile ( PUBLIC_PATH . "/js/frontend/news-list.js" );
// }
?>
<style type="text/css">
.news-listing-col1 .top{
	height:92px !important; /* 182*/
	vertical-align:middle;
	display:table-cell;
	text-align:center;
	float:none;
	width:276px;
}
/* .news-listing-col1{ */
/* 	width:238px; */
/* 	height:215px !important; */
/* } */
.news-listing-col1 {
    height: 215px !important;
    width: 32%;
}
.news-content-outer{
	padding: 2% 1% 0 2%;
    width: 97%;
}
.news-listing-col1 .top img{
	width:auto;
}
.news-listing-col1{
	position:relative;
	font-family: arial;
}

.news-listing-col1 .bot p {
    font-size: 12px;
}
.news-listing-col1 .play{
	width:100%;
	position:absolute;
	background:#000;
	opacity:0.3;
	top:0;
	left:0;
	z-index:9999;
	height:95px;	
	text-align:center;
}
.play-icon{
	margin: 0;
    padding: 35px 0;
    position: absolute;
    text-align: center;
    width: 100%;
}
.text-link{
	text-decoration:none !important;
	color : #6c518f;
}
.text-link:hover{
	text-decoration:underline !important;
}

.top img
{
	width:100px ;
	height:100px;
	margin:10px 0 0;
}
</style>
<script>

	</script>
<!-- Content Right Right Starts -->
<div class="socialise-content">

	<!-- Socialise hdr Starts -->
	<div class="news-header">
		<h1 class="text-purple">News</h1>
	</div>
	<!-- Socialise hdr Ends -->

	<!-- Col1 -->
	<div class="news-content-outer">
	<div>
<?php 
	
		$bbcNews=$this->news;
// 		Zend_Debug::dump($bbcNews);
// 		die;
		for($i=0;$i<count($bbcNews);$i++){
			if($i % 3 == 0){
				echo "</div>";
				echo "<div>";
				}
			
?>	

	
		<!-- News Outer --->
		
		<div class="news-listing-col1">
<?php 
		if (preg_match("/video/", $bbcNews[$i]['link']) || preg_match("/AUDIO/", $bbcNews[$i]['link'])) 
		{
?>
			<div class="play-icon">
				<img id="showDownload" src="<?php echo IMAGE_PATH;?>/play.png" width="25" height="25" />
			</div>
<?php 
		}
		
?>
			<div class="top">	
<?php
			if($bbcNews[$i]['image'])
			{ 
			
				echo '<img src="'.$bbcNews[$i]['image'].'" />';
			
			}
			else
			{
				echo '<img src="'.IMAGE_PATH.'/no_image.png" />';
			}
?>
			</div>
			<div class="bot">
				<h3 title="<?php echo $bbcNews[$i]['title'];?>">
<?php 
				if (preg_match("/VIDEO/", $bbcNews[$i]['title'])) 
				{
					$detail_url =  $bbcNews[$i]['link'];
				}
				else if (preg_match("/AUDIO/", $bbcNews[$i]['title'])) 
				{
					$detail_url = $bbcNews[$i]['link'];
				}
				else
				{
// 					$detail_url = str_replace("http://www.bbc.co.uk/", PROJECT_URL."/".PROJECT_NAME."news/detail/", $bbcNews[$i]['link']);
					$detail_url = PROJECT_URL."/".PROJECT_NAME."news/detail/".$bbcNews[$i]['link'];
				}
?>
				<a href= "<?php echo $detail_url;?>" class="text-link">
				<?php 
				if(strlen($bbcNews[$i]['title'])>22)
				{
					echo substr($bbcNews[$i]['title'],0,22)."..";
				}
				else
				{
					echo $bbcNews[$i]['title'];
				}
					?>
				</a>	
				</h3>
				<p class="text-grey2">
				<?php 
					$timestamp = strtotime($bbcNews[$i]['dateNtime']);
					$newDate = date('l, F j, Y g:iA ', $timestamp);
					echo $newDate;
				?>
				</p>
			  <p>
			 
		<?php 

	
			if(strlen($bbcNews[$i]['description'])>200){
				echo substr($bbcNews[$i]['description'],0,200)."..";
			}
			else{
				echo $bbcNews[$i]['description'];
			}
		?></p>

			</div>
		</div>
		<!-- News Outer --->
<?php 
		
		}

		
?>
	</div>
	</div>
	<!-- Col1 -->
<input type="hidden" name="initialPoint" id="initialPoint" value="12">
	<div id="loadingDiv" style="display:none;font-size:13px;font-weight:bold;background: none repeat scroll 0% 0% white; float: left; height: 25px;padding-top: 3px; width: 100%; text-align: center;">
		<img style="margin-top:-7px" src="<?php echo IMAGE_PATH; ?>/loading_large_purple.gif" />
	</div>




</div>
<!-- Content Right Right Ends -->