<?php
$this->headTitle()->prepend('Jobs');
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/jobs.js" );
/* Including CSS */
// $this->headLink()->appendStylesheet( "//cdn.datatables.net/1.10.7/css/jquery.dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/jobs.css" );
?>
<div id='heading'>
	<h2>Jobs
		<span style = 'float:right; margin-right: 5px;' title = 'Total Users according to current criteria' id = 'num_of_users'></span>
	</h2>
</div>

<div class="content">
	<div id="ilook_dt_wrapper" class="dataTables_wrapper">
		<div class="dataTables_length" id="jquery_dt_length">
			<label>Show <select name="jquery_dt_length" aria-controls="jquery_dt" class="">
					<option value="50">50</option>
					<option value="100">100</option>
					<option value="250">250</option>
					<option value="500">500</option></select> entries
			</label>
			<span class = "buttons">
				<span title="Click to close selected jobs" id = "close_records"></span>
			</span>
			<span class = "buttons">
				<span title="Click to delete selected jobs" id = "delete_records"></span>
			</span>
		
			
		</div>
						
		<div id="jquery_dt_filter" class="dataTables_filter">
			<label>Search:<input type="search" class="" placeholder="" aria-controls="jquery_dt"></label>
		</div>

		<div id="jquery_dt_filter" class="dataTables_filter" style = 'margin-right:10px;'>
			<label>Country:
				<select name = 'country_filter' aria-controls="jquery_dt" >
				<option value = "">All</option>
<?php 
					$countries = \Extended\country_ref::getAllCountriesJobsPosted();
					foreach ( $countries as $country )
					{
						echo "<option value = '".$country->getId()."'>".$country->getName()."</option>";
					}				
?>
					
				</select>
			</label>
		</div>
		
		<div id="jquery_dt_processing" class="dataTables_processing"
			style="display: none;">Processing...</div>

		<table id="jquery_dt" class="display dataTable" 
			cellspacing="0" cellpadding="0" border="0" role="grid"
			aria-describedby="jquery_dt_info" >
			<thead>
				<tr role="row">
<!-- 				----------------------------------------------------------------------------------------------------- -->
<!-- 				db_column attribute is set according to doctrine2 query requirement. Please see query in model class. -->
<!-- 				----------------------------------------------------------------------------------------------------- -->
					<th style="text-align:left; ">
					<input type = "checkbox" name = "master_delete_checkbox" class = "master_delete_cb">
					</th>
					<th class="sorting sorting_asc active" tabindex="0"
						aria-controls="jquery_dt" rowspan="1" colspan="1"
						 aria-sort="ASC" 
						db_column="job.id" db_column_alias="idd" position = "2">
						#
					</th>
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='job.job_title' db_column_alias="job_title"  position = "3">Reference Number</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='job.job_title' db_column_alias="job_title"  position = "3">Title</th>
					
					<th  class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='ilook_user.email' db_column_alias="email" position = "4">Owner Email id</th>
				
 					<th  class="sorting" tabindex="0" aria-controls="jquery_dt" 
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='ilook_user.username' db_column_alias="username" position = "5">Posted by</th> 
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='job.created_at' db_column_alias="posted_date" position = "6">Posted Date</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='job.expiry_date' db_column_alias="expiry_date" position = "7">Expiry Date</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='country_ref.name' db_column_alias="country_name" position = "8">Country</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='company.name' db_column_alias="company_name" position = "9">Company</th>
						
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1"  aria-sort="ASC"
						db_column='industry_ref.title' db_column_alias="industry_name" position = "9">Industry</th>
					
					<th class="sorting_disabled" rowspan="1" colspan="1"
						  position = "10">Actions</th>
				</tr>
			</thead>
			<tbody>

			</tbody>
			<tfoot>
				<tr>
					<th rowspan="1" colspan="1"></th>
					<th rowspan="1" colspan="1">#</th>
					<th rowspan="1" colspan="1">Job Reference Number</th>
					<th rowspan="1" colspan="1">Job Title</th>
					<th rowspan="1" colspan="1">Posted by email id </th>
					<th rowspan="1" colspan="1">Posted by user name</th>
					<th rowspan="1" colspan="1">Posted Date</th>
					<th rowspan="1" colspan="1">Expiry Date</th>
					<th rowspan="1" colspan="1">Country</th>
					<th rowspan="1" colspan="1">Company</th>
					<th rowspan="1" colspan="1">Industry</th>
					<th rowspan="1" colspan="1">Actions</th>
				</tr>
			</tfoot>
		</table>

		<div class="dataTables_info" id="jquery_dt_info" role="status"
			aria-live="polite"></div>

		<div class="dataTables_paginate paging_simple_numbers"
			id="jquery_dt_paginate">
			<a class="paginate_button previous disabled" aria-controls="jquery_dt"
				data-dt-idx="" tabindex="0" id="jquery_dt_previous">Previous</a>
				<span id = "page_buttons">
				</span>
			<a class="paginate_button next" aria-controls="jquery_dt" 
				data-dt-idx="" tabindex="0" id="jquery_dt_next">Next</a>
		</div>
	</div>
</div>
<!-- Dialog Box -->
<div style="display:none;" id="dialog_confirm_close_jobs" title="close job(s)">
	<p>
		Are you sure you want to close selected job(s) ?
	</p>
</div>
<div style="display:none;" id="dialog_confirm_delete_jobs" title="delete job(s)">
	<p>
		Are you sure you want to delete selected job(s) ?
	</p>
</div>


