<?php 
$this->headTitle()->prepend('Dashboard');

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/dashboard.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/js/tokenInput/token-input-facebook.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/import_contacts.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/links-common.css" );

$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/short_profile.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/tokenInput/jquery.tokeninput.js" );

$this->headScript()->prependFile( PUBLIC_PATH."/js/cloud-carousel.1.0.5.js");
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/dashboard.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/import_contacts.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/support.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/jQuery.bPopup.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );

$inviteYourContactsHtml = '';
$inviteYourContactsHtml .= '<div class="invite-mails-outer">';
$inviteYourContactsHtml .= '<div class="invite-mails-hdr">Invite your Mail Contacts</div>';
$inviteYourContactsHtml .= '<div class="invite-mails-data">';
$inviteYourContactsHtml .= '<a id="gmail" href="javascript:;"><img src="'.IMAGE_PATH.'/gmail-icon2.png"  alt=""/> <span>Gmail</span></a>';
//$inviteYourContactsHtml .= '<a href="javascript:;"><img src="'.IMAGE_PATH.'/outlook-icon2.png"  alt=""/> <span>Outlook</span></a>';
//$inviteYourContactsHtml .= '<a id="yahoo" href="javascript:;"><img src="'.IMAGE_PATH.'/yahoo-icon2.png"  alt=""/> <span>Yahoo</span></a>';
$inviteYourContactsHtml .= '</div>';
$inviteYourContactsHtml .= '<form action="#" id = "more_ways_to_connect_frm" onsubmit="return false">';
$inviteYourContactsHtml .= '<div class="you-may-input">';
$inviteYourContactsHtml .= '<input type="text" placeholder="Emails separated by semi-colons." id="more_ways_to_connect" value="" name="more_ways_to_connect">';
$inviteYourContactsHtml .= '<input id="more_ways_to_connect_btn" name="more_ways_to_connect_btn" value="Send" type="button">';
$inviteYourContactsHtml .= '</div>';
$inviteYourContactsHtml .= '</form>';
$inviteYourContactsHtml .= '</div>';
?>
<style>
.share-link-detail p{
	 word-wrap: break-word;
}
.quickview-top-right .left{
	width: 90px !important;
}
.quickview-top-right .right{
	width: 380px !important;
}
</style>
<script type = "text/javascript">
$(document).ready(function()
{
	// This initialises carousels on the container elements specified, in this case, carousel1.
	$("#carousel1").CloudCarousel(		
		{			
			xPos: 208,
			yPos: 17,
			buttonLeft: $("#left-but"),
			buttonRight: $("#right-but"),
			altBox: $("#alt-text"),
			titleBox: $("#title-text")
		}
	);
	
	$("#socialise-banner").click(function(){
		location.href = "/"+ PROJECT_NAME +"socialise/photo-feed";
		});	
	$(".links-banner").click(function(){
		location.href = "/"+ PROJECT_NAME +"job/recommended-jobs";
		});		
	$("div.socialise-banner-bot-closed").click(function(){
		location.href = "/"+ PROJECT_NAME +"socialise/photo-feed";
		});	
	$(".links-banner-bot-closed").click(function(){
		location.href = "/"+ PROJECT_NAME +"job/recommended-jobs";
		});	

});

</script>
<style>

.socialise-banner {
    cursor: pointer !important;
}
.links-banner{
	cursor:pointer !important;
}
.socialise-banner-bot-closed {
    cursor: pointer !important;
}
.links-banner-bot-closed{
	cursor:pointer !important;
}
.urlResult{
	 background: none repeat scroll 0 0 #fff;
    display: block;
    float: left;
    margin: 2px 0 0;
    padding: 10px;
    position: relative;
    width: 96.3%;
}

.notes-popup-outer{
	left: 15px;
	top: 140px;
}
</style>
<div class="common-div">
	<!-- News Starts -->
	<div id="minimize-menu-banner">
		<div class="links-banner-bot-closed text-white">
				<h2>JOBS</h2>
				 
			</div>
			
			<div class="socialise-banner-bot-closed text-white">
			<h2>DISPLAY</h2>
		</div>
	</div>
	<div class="links-banner">
		<div class="links-banner-top">
			<img  src="<?php echo IMAGE_PATH?>/dash-img2.png">
			
			</div>
			<div class="links-banner-bot text-white">
				<h2>JOBS</h2>
			</div>
		
		
	</div>
	<!-- News Ends -->

	<!-- Socialise Starts -->
	<div class="socialise-banner" id="socialise-banner">
		<div class="socialise-banner-top">
			<img src="<?php echo IMAGE_PATH?>/img4.jpg">
			
		</div>
		<div class="socialise-banner-bot text-white">
			<h2>DISPLAY</h2>
		</div>
	</div>
	<!-- Socialise Ends -->


</div>

<!-- 	dashboard-knw-adv-outer Starts  -->
<div class="dashboard-knw-adv-outer">
	<!-- Left Start  -->
	<div class="left">
		<div class="viewed-profile-outer">
<?php 
		if(!empty($this->vistors))
		{
?>
		<!-- Viewed Your Profile Starts -->
			<div class="viewed-profilenew">
				<div class="viewed-profile-left text-purple2">
					<h3>VIEWED YOUR PROFILE</h3>
				</div>
			</div>
			<!-- Viewed Your Profile Ends -->
			<div class="carasol-content">
				<div id="carousel1"
					style=" height: 140px; overflow: scroll;  z-index:1 !important;">
					<!-- All images with class of "cloudcarousel" will be turned into carousel items -->
					<!-- You can place links around these images -->
<?php 
					$i=0;
					foreach ($this->vistors as $key=>$vistors)
					{
						if($i==5) break;
						$filename="images/profile/medium_thumbnails/thumbnail_".$vistors->getVisitorsIlook_user()->getProfessional_image();
						if($vistors->getVisitorsIlook_user()->getProfessional_image()!="" && file_exists($filename))
						{
							$img_name=IMAGE_PATH."/profile/medium_thumbnails/thumbnail_".$vistors->getVisitorsIlook_user()->getProfessional_image();
						}
						else
						{
							if($vistors->getVisitorsIlook_user()->getGender()==Extended\ilook_user::USER_GENDER_MALE)
							{
								$img_name=IMAGE_PATH."/profile/default_profile_image_male_medium.png";
							}
							else
							{
								$img_name=IMAGE_PATH."/profile/default_profile_image_female_medium.png";
							}
						}
?>	
					<a  class="text-purple2-link" id = "carousal_anchor_<?php echo $key;?>"
						href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.$vistors->getVisitorsIlook_user()->getUsername();?>">
						
						<img class="cloudcarousel" id = "carousal_img_<?php echo $key;?>"
						src="<?php echo $img_name ?>"
						alt="<?php echo $vistors->getVisitorsIlook_user()->getFirstname()." ".$vistors->getVisitorsIlook_user()->getLastname();?>"
						title="<?php echo $vistors->getVisitorsIlook_user()->getFirstname()." ".$vistors->getVisitorsIlook_user()->getLastname();?>" />
					
					
					 
					</a>
<?php 
				$i++;
					
		}
				if(count ( $this->vistors ) > 5) {
		?>
				<div class="viewed-profile_crousal">
						<a href="/<?php echo PROJECT_NAME?>links/recently-viewed"
							class="text-purple2-link">SEE MORE</a> <img width="8" height="13"
							src="<?php echo IMAGE_PATH?>/arrow-right.png">
					</div>
<?php 
					}
?>
						
				</div>
				<!-- Here we define left and right buttons. -->
				<input id="left-but" type="button" value="" /> <input
					style="margin-left: 150px;" id="right-but" type="button" value="" />

			</div>
<?php 
		} 
		else
		{
?>
			<div class="viewed-profilenew" style="display: none;"></div>
			<div class="carasol-content" style="display: none;"></div>
<?php 
		} 
?>
			<!-- Share Something Starts -->
			<div class="share-something">
				<div class="share-something-left">
					<div class="img-profile">
						<img src="<?php echo Helper_common::getUserProfessionalPhoto( Auth_UserAdapter::getIdentity()->getId(), 3 );?>" />
					</div>
					<div class="url-loader clr ">
						<img id="loading_indicator" src="<?php echo IMAGE_PATH?>/loading_small_purple.gif">
					</div>
					
				</div>
				<div class="share-something-right">
				
					<textarea name="post_box" cols="" class="bg-textarea" rows=""
						id="post_box" maxlength="1000"></textarea>
					<div class="share-something-right-bot">
						<div style="margin: 5px 0 0 0;" class="fl">Share with</div>
						<div class="sharewith-links" id="win-xp1">
							<select name="privacy_dd" id="privacy_dd" style="display: none;">
								<option value="<?php echo \Extended\wall_post::VISIBILITY_CRITERIA_PUBLIC; ?>">Public</option>
								<option value="<?php echo \Extended\wall_post::VISIBILITY_CRITERIA_LINKS; ?>">Links</option>
								<option value="<?php echo \Extended\wall_post::VISIBILITY_CRITERIA_LINKS_OF_LINKS; ?>">Links of Links</option>
							</select>
						</div>
						<div style="margin: 5px 0px 0px 20px;" class="fl">Tag</div>
						<div class="sharewith-links" id="win-xp1">
							<select name="post_tags" id="post_tags" style="display: none;">
								<option value="<?php echo 1; ?>">General</option>
								<option value="<?php echo 2; ?>">Job</option>
							</select>
						</div>
						<div class="fl" id="share_button">
							<div>
								<input name="share" alt="Share" title="Share" type="button" id="share" class="btn-purple" value="Share" />
							</div>
						</div>
					</div>
					
				</div>
			</div>
			<!-- Share Something Ends -->
			 <div id="results" class="urlResult">
			 	
     		</div> 
		</div>
		<!-- News Outer Starts -->
		<div class="news-outer">
			<div class="news-heading">
				<h3>Updates</h3>
				<h4>
				<div class="update_posts_by_tag">
				<a onclick='loadUpdatesOnWall(0,2)' href='javascript:;' >Filter Posts by Job Tag</a>
				</div>
				</h4>
				
				<input type="hidden" id = "is_dashboard" value="1" name="is_dashboard"/>
				<input type="hidden" name="offsettt" value="0" id="offsettt"/>
				<input type = "hidden" name= "hidden_url_title" id = "hidden_url_title" value = ""/>
				<input type = "hidden" name="hidden_url_content" id = "hidden_url_content" value = ""/>
				<input type = "hidden" name="hidden_is_url" id = "hidden_is_url" value = "0"/>
				<input type = "hidden" name="hidden_url" id = "hidden_url" value = ""/>
				<input type = "hidden" id = "my_small_image" value = "<?php echo Helper_common::getUserProfessionalPhoto( Auth_UserAdapter::getIdentity()->getId(), 3 ); ?>">
				<input type = "hidden" id = "my_user_id" value = "<?php echo Auth_UserAdapter::getIdentity()->getId();?>">
				<input type="hidden" id="offset_who_liked" value="0">
				<input type="hidden" id="limit_who_liked" value="10">
				<input type="hidden" id="offset_who_shared" value="0">
				<input type="hidden" id="limit_who_shared" value="10">
				<input name="tag_id" type="hidden" id="tag_id" value="0">
				<input type="hidden" id="is_filtered_by_tag" value="0">
			</div>
			<div id="updates_holder">
				<!-- Updates append here -->
			</div>
		</div>
		<!-- News Outer Ends -->

	</div>
	<!-- Left Ends -->

	<!-- Right Starts -->
	<div class="right">
	<div id="sticky-anchor"></div>
		<div id="sticky" class = "inner_right">
		<!-- Youmay Know Starts -->
		
		
		<!-- Content Right Starts -->
 				<div  class="you-may-know-outer">
	     			<div class="you-may-know-hdr">You May Know</div>
	     			<?php 
	     			$newMergeArray = $this->youMayKnowUsers;
	     				
	     			if(!empty($newMergeArray))
					{	
						//Zend_Debug::dump($newMergeArray);die;
						foreach ($newMergeArray as $neew)
						{ // \Zend_Debug::dump($neew); die;?>
							<div class="you-may-know-column you-may-know-column_<?php echo $neew->getId();?>">
				            	<div class="youmay-know-cross" rel="<?php echo $neew->getId();?>">
									<img width="9" height="8" src="<?php echo IMAGE_PATH ; ?>/cross.png" >
								</div>
								
								<?php
									$filename = "images/profile/small_thumbnails/thumbnail_" . $neew->getProfessional_image ();
									if ($neew->getProfessional_image () != "" && file_exists ( $filename )) 
									{
										$img_name = IMAGE_PATH . "/profile/small_thumbnails/thumbnail_" . $neew->getProfessional_image ();
									} 
									else 
									{
										if($neew->getGender()==Extended\ilook_user::USER_GENDER_MALE)
										{
											$img_name=IMAGE_PATH."/profile/default_profile_image_male_big.png";
										}
										else
										{
											$img_name=IMAGE_PATH."/profile/default_profile_image_female_big.png";
										}
									}
									$jsonArr = array("user_id"=>$neew->getId(),"showEditGroupsOption"=>NULL,"disableParentBorder"=>1);
									$finalJson = Zend_Json::encode($jsonArr);    
								?> 
				            	<div class="you-may-know-img">
				            		<!--  commented short profile view  -->
				            		<!--a  href="javascript:;"  id="<?php echo $neew->getId();?>" onclick="getShortProfile(this,'<?php echo htmlentities($finalJson);?>')" disable-border="1">
				            			<img class="userProfileImage" src="<?php echo $img_name; ?>" width="50" height="50"/>
				            		</a-->
				            		<img class="userProfileImage" src="<?php echo $img_name; ?>" width="50" height="50"/>
				            		<div class="quickview-outer" style="display:none;" id="view-outer_<?php echo $neew->getId();?>" popup-state="off">
										<div class="popupArrow">
											<img src="<?php echo IMAGE_PATH;?>/arrow-purple2.png" width="36" height="22" />
										</div>
										<div class="quickview" id="view_<?php echo $neew->getId();?>">
										   <!-- user records view.... -->
										</div>
									</div>
				            	</div>
				                <div class="you-may-know-data">
				                	<h4 title="<?php echo $neew->getFirstname()." ".$neew->getLastname() ; ?>">
				                	<?php 
				                	$urlPath=PROJECT_URL."/".PROJECT_NAME."profile/iprofile/id/".$neew->getId();
				                	?>
				                	<a href="<?php echo $urlPath;?>" class="text-dark-purple">
				                	<?php echo Helper_common::showCroppedText($neew->getFirstname()." ".$neew->getLastname(), 15 ); ?>
				                	</a>
				                	</h4>
				                   
				                   <?php
								   $userProfession =  Helper_common::getUserProfessionalInfo($neew->getId());
								   if($userProfession) {
									   if (isset($userProfession[0])){
											echo '<h5>'.$userProfession[0].'</h5>';
									   }
									   if (isset($userProfession[1])){
										   echo '<p>'.$userProfession[1].'</p>';
									   }
									}
								   ?>

				                </div>
				                
				           		<div class="you-may-know-add">
				                    <a style="background-size:30px 30px !important"onclick="inviteToLink(this)" href="javascript:;" title="Invite to Link" class="cursor-style invite_<?php echo $neew->getId();?> invitation-request" id="<?php echo $neew->getId();?>">
				                    <!--img id="dashboard-invitation_<?php echo $neew->getId();?>" src="<?php echo IMAGE_PATH ?>/invitation-request-icon.png" title="Send Request" alt="" width="27" /-->
				                    </a>
				               </div> 
				       </div>

<?php 
						} 

						if( $this->is_more_records)
						{
						
							echo'<div class="see_more_you_may_know job-content view_more">';
							echo'<p>';
							echo'<a href="/'.PROJECT_NAME.'links/people-you-may-know" class="see_more_you_may_know_text text-dark-purple fr">';
							echo'See More >>';
							echo'</a>';
							echo'</p>';
							echo'</div>';
						}
						
?>
					<!-- <div class="you-may-know-column">
              			<div class="you-may-know-more"><a href="<?php // echo PROJECT_URL."/".PROJECT_NAME;?>links/people-you-may-know">More >></a></div> 
              		</div>-->
<?php
				echo $inviteYourContactsHtml;
				 	if(count($newMergeArray)==2){
				 		echo '<style>.you-may-input{display:none;}</style>';
				 	}
				 	else if(count($newMergeArray)==3){
				 		echo '<style>.you-may-input{display:none;}.invite-mails-outer{display:none;}</style>';
				 	}
				}
				else
				{ 
					echo $inviteYourContactsHtml;
				} 
?>            	
                </div>
    <!-- Content Ends -->

		<!-- Youmay Know Ends -->


		<!-- Right Div Starts -->
		<div class="right-div">

			<!-- SUPPORT SECTION STARTS HERE -->
<?php 
		if($this->support_skills_array && count($this->support_skills_array) != 0) {?>
			<div class="youmay-know">
				<div class="youmay-know-heading">
					<h3 style="">Support Skills</h3>
				</div>
<?php 
				// foreach start for listing user and his/her skills
				$listCount = 1 ;
				foreach ($this->support_skills_array as $supportList)
				{ 
					// end of if condition
					if ($supportList['skills'])
					{
						if($listCount <= 3)
						{
?>
					<div id="user_<?php echo $supportList['userId']; ?>" class="youmay-know-col1" style="background-color: rgb(255, 255, 255);">
					<form method="post" id=<?php echo $supportList['userId']; ?> name="support">
						<input type="hidden" value=<?php echo $supportList['userId']; ?> id="user_id" name="user_id">
						<div class="youmay-know-col1-img" style = "margin:6px 0 0 0; width:25%;" >
						<!--  commented short profile view  -->	
						<!--a  href="javascript:;"  id="<?php echo $supportList['userId'];?>" onclick="getShortProfile(this,'<?php echo htmlentities($finalJson);?>')" disable-border="1">
								<img class="userProfileImage" width="100%" height="" src="<?php echo $supportList['userImage'] ;?>">
						</a-->
						<img class="userProfileImage" width="100%" height="" src="<?php echo $supportList['userImage'] ;?>">
						<div class="quickview-outer" style="display:none;" id="view-outer_<?php echo $supportList['userId'];?>" popup-state="off">
								<div class="popupArrow">
									<img src="<?php echo IMAGE_PATH;?>/arrow-purple2.png" width="36" height="22" />
								</div>
								<div class="quickview" id="view_<?php echo $supportList['userId'];?>">
								   <!-- user records view.... -->
								</div>
							</div>
							
						</div>
						<div style="width:65%;" class="youmay-know-col1-title">
						<div class="youmay-know-cross">
								<img width="9" height="8" onclick="removeFromList(<?php echo $supportList['userId']; ?>);" src="<?php echo IMAGE_PATH ; ?>/cross.png" id="remove_<?php echo $supportList['userId']; ?>">
							</div>
							<div  style="margin:0 3px;" class="youmay-know-text1">
								<a class="text-dark-purple" href="/<?php echo PROJECT_NAME.$supportList['user_username'] ;?>" style="text-decoration:none;"><?php echo Helper_common::showCroppedText( $supportList['userName'], 15 ); ?></a>
								
<?php 
									$skillCount = 1 ;
									foreach ($supportList['skills'] as $keys => $skill) {
										if($skillCount <= 1){
											echo '<input type="checkbox" value="'.$keys.'" name="skills[]" checked="checked" style="visibility: hidden;"><h5>'.$skill.'</h5>';
									 		$skillCount++ ;
									 		$skill_id = $keys ;
										}
									}
?>											
							</div>	
									
							
							<div class="youmay-know-text2" id="supportDiv_<?php echo $supportList['userId']; ?>" style="visibility: visible; margin-left:-5px;">
								<span id="loader_<?php echo $supportList['userId']; ?>"></span>
								<div id="support_img_<?php echo $supportList['userId']; ?>">
									<img style="cursor: pointer" rel = "<?php echo $supportList['userId']; ?>" onclick="Supportskills(<?php echo $skill_id.', '.$supportList['userId']; ?>);" src="<?php echo IMAGE_PATH.'/icon-support2.png' ;?>" alt="Support" />
								</div>
							</div>
						</div>
					</form>
				</div>
<?php 
							$listCount++ ;
						}
					}
				}
				// end of foreach
?>		
			</div>
<?php 
			// end of if condition
			}
?>
			<!-- SUPPORT SECTION STARTS ENDS -->
		</div>
		<!-- Right Div Ends -->
		</div>
	</div>

	<!-- Right Ends -->
</div>
<!-- Dialog Box -->
<div id="delete_comm_dialog_confirm" title="Delete Comment" style = "display: none;">
  <p>
  	Are you sure you want to delete this comment ?
  </p>
</div>

<?php
echo $this->partial('partials/who_liked_popup.phtml');
echo $this->partial('partials/comments_listing_popup.phtml');
echo $this->partial('partials/share_dashboard_popup.phtml');
echo $this->partial ( 'partials/who_shared_popup.phtml' );
echo $this->partial ( 'partials/report_abuse_options.phtml' );
//Adding partial for unlink popup
echo $this->partial ( 'partials/unlink-popup.phtml' );
echo $this->partial('partials/import_gmail_contacts_popup.phtml');
echo $this->partial('partials/yahoo_login_popup.phtml');
?>
<div id="dialog_success_share" title="Share Post" style = "display: none;">
  <p>
  	Post shared successfully.
  </p>
</div>
<div id="dialog_confirm_delete_wallpost" title="Delete Wallpost">
  <p>
  	Are you sure you want to delete your post?
  </p>
</div>

<!--  script for tracking dashboard page -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-64030551-2', 'auto');
  ga('send', 'pageview', '/dashboard');

</script>

