<?php
$this->headTitle()->prepend('Second Login');
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/login.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/admin/login.js");
?>

<form name="form2" action='/<?php echo PROJECT_NAME; ?>admin/authenticate/login-second' id="form2"  method="post"    >
	<div class="login-box-outer" >
		<div class="login-logo" >
			<img alt="iLook" src="<?php echo IMAGE_PATH;?>/logo.png">
	    </div>
		<div class="login-box">
	    	<div class="login-box-heading">ADMINISTRATOR LOGIN II</div>
	    	
<?php
		$messages = new Zend_Session_Namespace ('admin_messages');
		if($messages->errorMsg)
		{
		    echo "<div class='login-input error' id='error-msg' style = 'height : 14px; margin-top: 15px; color: #B94A48;'>";
	    	echo $messages->errorMsg;
	    	echo "</div>";
		}
		unset( $messages->errorMsg );
		
		if( $this->ask_digits )
		{
		    echo "<div class='login-input' id='msg' style = 'height : 14px; margin-top: 15px;'>";
	    	echo $this->ask_digits['sentence'];
	    	echo "</div>";
		}	
?>
	        <div class="input-prepend login-input1">
	          <span class="add-on"><i class="icon-lock"></i></span><input type="password"  maxlength="3" placeholder="General Password" name="pwd" id="pwd">
	        </div>
	        <div class="button-outer">
	        	<button type="submit" name="button" id="button" class="btn btn-large btn-default" title="Login">LOGIN</button>	
	        </div>
	    </div>
	</div>
</form>