<?php
$this->headTitle()->prepend('Password Recovery');
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/login.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/forgot_pswd.css" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/admin/login.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/admin/forgot_pswd.js");
?>

<form name="form_recover_pswd" id="form_recover_pswd" action="">
	<div class="login-box-outer" >
		<div class="login-logo" >
		<a style="cursor:pointer" href="<?php echo PROJECT_URL.'/'.PROJECT_NAME.'admin/index/index' ?>">
			<img alt="iLook" src="<?php echo IMAGE_PATH;?>/logo.png">
		</a>
	    </div>
		<div class="login-box">
	    	<div class="login-box-heading">Password Recovery <span style="font-weight:normal">(sub admin)</span> </div>
	    	<div id = "success_error_msg">
        	</div>
	        <div class="input-prepend login-input">
	          	<span class="add-on">
		          	<i class="icon-user">
		          	</i>
	          	</span>
	          	<input type="text" value="" id="email" name="email" placeholder="Email ID" maxlength="255">
		       	<div id = "emailExistsMsg">
	        	</div>
	        	  <span id="email_validate_image">
		        </span>
	        	<div class="button-outer send_email">
	        		<button id="forgot_email_submit" type="button" name="button" id="button" class="btn btn-large btn-default" title="send">send</button>	
		        </div>
		      
	        </div>
	    </div>
	</div>
</form>