<?php 
$this->headTitle()->prepend('Password Recovery');
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/reset_pswd.css" );
$messages = new Zend_Session_Namespace ('admin_messages');
if($messages->successMsg)
{
	echo "<div id='imbullwrap'>";
	
	echo "<div class='login-box-outer'>";
	echo "<div class='login-logo'>";
	echo "<img src='http://localhost/ilook/public/images/logo.png' alt='iLook'>";
	echo "</div>";
	echo "<div class='pswd_reset_success' id='success-msg' style = ''>";
	echo $messages->successMsg;
	echo "</div>";
	echo "</div>";
	echo "</div>";
   
}
unset( $messages->successMsg );
?>


