<?php
$this->headTitle()->prepend('Change Password');
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/sub_admins.css" );
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/sub_admins.js" );
$this->headScript()->appendFile(PUBLIC_PATH . "/js/admin/change_password.js");
?>

<form name="form_change_pswd" id="form_change_pswd">
	<div class="login-box-outer" >
		
		<div class="login-box">
	    	<div class="login-box-heading">Change Password <span style="font-weight:normal">(sub admin)</span> </div>
	    	<div class="change_pswd_successmsg"></div>
	    	<div class="change_pswd_errormsg"></div>
	    	<?php
			
			?>
	    	
	        <div class="input-prepend login-input">
	          	<span class="add-on"><i class="icon-lock"></i></span><input type="password" value="" id="password" name="cg_password" placeholder="Password" maxlength="255">
	        </div>
	        <div class="input-prepend login-input">
	          	<span class="add-on"><i class="icon-lock"></i></span><input type="password" value="" id="cpassword" name="cg_cpassword" placeholder="Confirm password" maxlength="255">
	        </div>
	        <div class="button-outer">
	        	<button id="change_password_button" type="button" name="button" class="btn btn-large btn-default" title="save">Save</button>	
	        </div>
	        <span id = "email_validate_image"></span>
	        <div id = "emailExistsMsg">
	        </div>
	    </div>
	</div>
</form>