<?php
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/sub_admins.js" );
/* Including CSS */
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/sub_admin.css" );
?>
<style>
.sub-admin-form{ width:96%; float:left; margin:0; padding:0 2%;}
.sub-admin-form-lt{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-rt{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-lt label{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-lt span{ width:50%; float:left; margin:0; padding:0; min-height:65px;}
.sub-admin-form-rt label{ width:50%; float:left; margin:0; padding:0;}
.sub-admin-form-rt span{ width:50%; float:left; margin:0; padding:0; min-height:65px;}
.sub-admin-btn-outer{ width:100%; float:left; text-align:center;}
.sub-admin-btn-outer input[type="button"]{ width:auto; padding:5px 10px;}

@media only screen and (min-device-width:768px) and (max-device-width:1024px) {	
.sub-admin-form-lt{ width:100%;}
.sub-admin-form-rt{ width:100%; }
.sub-admin-form-lt label{ width:100%; }
.sub-admin-form-lt span{ width:100%;}
.sub-admin-form-lt span input{width:75%;}
.sub-admin-form-rt span input{width:75%;}
.sub-admin-form-rt label{ width:100%;}
.sub-admin-form-rt span{ width:100%;}
}
</style>
<div id='heading'>
	<h2>Create Sub Admin</h2>
</div>

<form name="create-subadmin" id="create-subadmin" method="POST" action="/<?php echo PROJECT_NAME; ?>admin/sub-admins/create-sub-admin" > 
<div class="sub-admin-form">
	<div class="sub-admin-form-lt">
		<label>First Name</label>
		<span><input type="text" name="first_name"/></span>
		
		<label>Email ID</label>
		<span><input type="text" name="email_id" id="email_id"/></span>
		
		<!--  label>Password</label>
		<span><input type="password" name= "password"/></span-->
	</div>
	
	<div class="sub-admin-form-rt">
	
	    <label>Last Name</label>
		<span><input type="text" name="last_name"/></span>
		
		<label>Expiry Date</label>
		<span><input type="text" name="expiry_date" id="expiry_date" readonly="readonly"/></span>
		
		<!--  label>Confirm Password</label>
		<span><input type="password" name="confrm_password"/></span-->
	</div>
	
	<div class="sub-admin-btn-outer">
		<input value="Save" class="btn" type="submit"/>
		<input value="Cancel" class="btn" type="reset"/>
	</div>

</div>
</form>
