<?php
$this->headTitle()->prepend('Manage Sub-admins');
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/sub_admins.js" );
/* Including CSS */

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/sub_admins.css" );

?>

<div id='heading'>
	<h2>Sub admins</h2>
	
</div>
<script>




</script>


<div class="content">
	<div id="ilook_dt_wrapper" class="dataTables_wrapper">
		<div class="dataTables_length" id="jquery_dt_length">
			<label style = 'display:none'>Show <select name="jquery_dt_length" aria-controls="jquery_dt" class="">
					<option value="25">25</option>
				</select> entries
			</label>
			<span class = "buttons" style = 'margin-left:0;'>
				<span id = "delete_records"></span>
			</span>
			<span class = "buttons create-subadmin">
				<a href='<?php echo "/".PROJECT_NAME."admin/sub-admins/edit"?>'>
					<span title= "Create Subadmin" id = "add_records">
					</span>
				</a>
			</span>
			<span class = "buttons">
				<span id = "enable_records" title="click to enable selected records"></span>
			</span>
			<span class = "buttons">
				<span id = "disable_records" title="click to disable selected records"></span>
			</span>
			
		</div>

		<div id="jquery_dt_filter" class="dataTables_filter">
			<label>Search:<input type="search" class="" placeholder=""
				aria-controls="jquery_dt"></label>
		</div>

		<div id="jquery_dt_processing" class="dataTables_processing"
			style="display: none;">Processing...</div>

		<table id="jquery_dt" class="display dataTable" width="100%"
			cellspacing="0" cellpadding="0" border="0" role="grid"
			aria-describedby="jquery_dt_info" style="width: 100%;">
			<thead>
				
				<tr role="row">
<!-- 				----------------------------------------------------------------------------------------------------- -->
<!-- 				db_column attribute is set according to doctrine2 query requirement. Please see query in model class. -->
<!-- 				----------------------------------------------------------------------------------------------------- -->
					<th style="width: 2%; text-align:left; padding: 10px 9px;"><input type = "checkbox" name = "master_delete_checkbox" class = "master_delete_cb"></th>
					<th class="sorting sorting_asc active" tabindex="0"
						aria-controls="jquery_dt" rowspan="1" colspan="1"
						style="width: 3%;" aria-sort="ASC" 
						db_column="sub_admin.id" db_column_alias="idd" position = "2">#</th>
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" aria-sort="ASC"
						db_column='sub_admin.firstname' db_column_alias="sub_admin_first_name"  position = "3">First Name</th>
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" aria-sort="ASC"
						db_column='sub_admin.lastname' db_column_alias="sub_admin_last_name" position = "4">Last Name</th>
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style= aria-sort="ASC"
						db_column='sub_admin.email_id' db_column_alias="sub_admin_email_id" position = "5">Email</th>
						
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style= aria-sort="ASC"
						db_column='sub_admin.expiry_date' db_column_alias="sub_admin_expiry_date" position = "6">Expiry Date</th>
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style=" aria-sort="ASC"
						db_column='sub_admin.profile_picture' db_column_alias="sub_admin_profile_picture" position = "7">Profile Picture</th>
					<th class="sorting_disabled" rowspan="1" colspan="1"
						style=""  position = "8">Actions</th>
					
				</tr>
			</thead>
			<tbody>

			</tbody>
			<tfoot>
				<tr>
					<th rowspan="1" colspan="1"></th>
					<th rowspan="1" colspan="1"></th>
					<th rowspan="1" colspan="1">First Name</th>
					<th rowspan="1" colspan="1">Last Name</th>
					<th rowspan="1" colspan="1">Email</th>
					<th rowspan="1" colspan="1">Expiry Date</th>
					<th rowspan="1" colspan="1">Profile Picture</th>
					<th rowspan="1" colspan="1">Actions</th>
				</tr>
			</tfoot>
		</table>

		<div class="dataTables_info" id="jquery_dt_info" role="status"
			aria-live="polite"></div>

		<div class="dataTables_paginate paging_simple_numbers"
			id="jquery_dt_paginate" style = 'display:none;'>
			<a class="paginate_button previous disabled" aria-controls="jquery_dt"
				data-dt-idx="" tabindex="0" id="jquery_dt_previous">Previous</a>
				<span id = "page_buttons">
				</span>
			<a class="paginate_button next" aria-controls="jquery_dt" 
				data-dt-idx="" tabindex="0" id="jquery_dt_next">Next</a>
		</div>

	</div>
</div>
<div style="display:none;" id="dialog_confirm_delete_sub_admins" title="Delete sub-admin(s)">
	<p>
		Are you sure you want to delete selected record(s)?
	</p>
</div>

