<!-- Title -->
<?php
$this->headTitle ()->prepend ( 'Provide Reference' );
?>
<!--  Including js -->
<?php 
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/frontend/provide_reference.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/jQuery.bPopup.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/tokenInput/jquery.tokeninput.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/overlay/center.jquery.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH . "/js/overlay/jquery.overlay.js" );
?>
<!-- Including CSS -->
<?php
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/js/tokenInput/token-input-facebook.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH . "/css/frontend/provide_reference.css" );
echo $this->render ( "partials/add_contacts_popup.phtml" );
echo $this->partial ( 'partials/profile_menu.phtml' );
?>
<?php 
$links = Auth_UserAdapter::getIdentity()->getLink_list();
?>
<!-- Content Right Right Starts -->
<div class="content-right-right">
	<!-- Photo Album Starts -->
	<div class="photoalbum-outer">
		<div class="photoalbum-hdr">
			<h2>Provide Reference</h2>
		</div>
		<div class="feedback-hdr-bot"></div>
		<!-- Content -->
		<div class="mail-sendmsg-outer">
<?php 
		if( $links )
		{	
?>		
		<form name="provide_reference_form" id="provide_reference_form" action=""
		method="post">
		<input type="hidden" name="reference_req_id" value="<?php echo $this->reference_req_id;?>" />
			<!-- Col 2 Starts-->
			<div style="display: none;" id="reference_receiver_ids_holder"></div>
			<div class="mail-sendmsg-col2">
			<span>
				<select class="font-arial dropdown" name="provider_links" id="provider_links">
					<option value="">Select</option>
<?php
					//Logged in user i.e provider.
					$current_user = Auth_UserAdapter::getIdentity()->getId();
					$user_links = explode(",", $links);
					foreach( $user_links as $link )
					{
						//Converting id to object.
						$link_obj = \Extended\ilook_user::getRowObject( $link );
						if($link_obj)
						{
								echo"<option rel=".$link_obj->getId()." value=".$link_obj->getId().">".$link_obj->getFirstname()." ".$link_obj->getLastname()."</option>";
						}
					}
?>
				</select>

				</span> 
				<span>
				<select class="font-arial dropdown" name="requester_jobs" id="requester_jobs">
					<option value="">Select</option>
				</select>
				</span> 
					
			</div>
			<div class="mail-sendmsg-col2-content">
				<textarea class="font-arial" placeholder="I am happy to be your reference" rows="" cols="" style="width: 98%; border: 1px solid rey; min-height: 170px; margin-bottom: 20px; resize: none;" class="textarea" name="provider_msg" id="provider_msg">I am happy to be your Reference.</textarea>
			</div>
			<div class="mail-save-draft btm_btns">
				<div class="fr fr_cancel">
					<input type="button" title="Clear" value="Clear" class="btn-white" name="" id="cancel">
				</div>
				<div class="fr fr_btn">
					<input type="button" title="Provide Reference"
					value="Provide Reference" class="btn-dark-purple" name="send_reference" id="send_reference"/>
				</div>
			</div>
			<!-- Col 2 Ends-->
			</form>
<?php 
		}
		else
		{
			echo '<div class="no_messages">You have no links to provide reference.</div>';
		}	
?>			
		</div>
		<!-- Content -->
	</div>
	<!-- Photo Album Ends -->
</div>
<!-- Content Right Right Ends -->