<?php
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/short_profile.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/jquery.stylish-select.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/links_menu.js" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/group.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/links-common.css" );
$usr_groups=$this->usr_groups;
echo $this->partial ( 'partials/bookmark_menu.phtml' );
echo $this->partial ( 'partials/unlink-popup.phtml' );
$menu_size = Auth_UserAdapter::getIdentity()->getMain_menu_size();

$bookmarkGroupLinks = array();
if( $this->paginator->getTotalItemCount() )
{
	foreach ( $this->paginator as $v )
	{
		$bookmarkGroupLinks[] = $v;
	}
}
?>
<style type="text/css">
.botlinks .col2{
	margin: 5px 10px 0 0 !important;
    padding-top: 0 !important;
}
</style>
<!-- Content Right Right Starts -->
<div class="content-right-right">
<!-- Photo Album Starts -->
<div class="photoalbum-outer">
			<div class="photoalbum-hdr">
				<h2 style="width: auto;" class="text-grey2">
				
					<font class="text-purple2"></font> Bookmarked Profiles
					<!--  <div class="addnew-links">
						<a class="text-purple-link" href="javascript:;">Add New Bookmarked Groups</a>
						<img src="<?php echo IMAGE_PATH;?>/icon-connection-hover.png" width="16" height="15" align="absmiddle" />
					</div>-->
				</h2>
				
				<div class="photoalbum-addnew">
					<h3 class="text-purple2"><font class="text-grey3">View by Group </font><span title="<?php echo $this->group_title;?>"><?php if(strlen($this->group_title)>60){ echo substr($this->group_title,0,60)."...";} else {echo $this->group_title;} ?></span></h3>
				</div>
				
				<div class="bookmarks-hdr-text1" style="margin-top: 0px">
					
					<div class="bookmarks-hdr-text1" style="margin-top:0px">
                            <div class="fl text-grey3">
                           	 <br>
 <?php 
 if($this->paginator->getTotalItemCount()>0){
 ?>
 <style type="text/css">
.linkprofile-container{
	min-height:597px !important
}
</style>
&nbsp;<font class="text-purple"><a onclick="showManagePopup()" href="javascript:;" class="text-purple-link">Manage</a></font>&nbsp; <img width="16" height="13" align="absmiddle" src="<?php echo IMAGE_PATH;?>/folder-hover.png">
<?php 
 }
?>
                            </div>
                            <?php 
				            	if(count($this->links)>0 || isset($_REQUEST['bookmarkSearch'])) {
				            ?>
                            <div class="mail-hdr-search">
                            <form name="bookmark-frm" id="bookmark-frm" method="get" action="">
								<input type="hidden" name="grpID" id="grpID" value="<?php echo @$this->bookmarkGrpID;?>" />
								<a href="javascript:;" id="bksearch"  class="fr srchBtn" id="bksearch" style="float:right;">Search</a>
							<input type="text" name="bookmarkSearch" id="bookmarkSearch" value="<?php echo @$this->bookmarkSearchText;?>" placeholder="Search" style="float:right;">
							</form></div>	
                     <?php 
				            	}
                     ?>
                  </div>
				</div>
				
				<!-- Manage POPUP here -->
				<div class="manage-pop-outer" style="display:none;">
               	   <div class="manage-pop">
                              <!--  <div class="col1"><a style="text-decoration:none;float:right;margin-right:5px" href="javascript:;" onclick="showManagePopup();">X</a></div>-->
                               <div class="col1">
                                                   	      <img width="14" height="16" align="absmiddle" src="<?php echo IMAGE_PATH;?>/icon-trash-hover.png"><a id="remBookmark" onclick="removeBookmarkGroup()" class="text-grey2-link" href="javascript:;">Remove From Group</a></div>                    	      
                                <div class="col1">
                                                   	      <img width="16" height="13" align="absmiddle" style="margin-top:3px;" src="<?php echo IMAGE_PATH;?>/mail-hover.png"><a onclick="sngMsg()" class="text-grey2-link" href="javascript:;">Send Message</a></div>
                               
                               
                            <div class="msg-popup-outer" style="display:none;">
		                    	<div class="msg-popup-top"><img width="26" height="16" src="<?php echo IMAGE_PATH;?>/arrow-popup.png"></div>
		                        <div class="msg-popup-bot">
		                        	<h4>Send Message</h4>
		                            <textarea name="sndmultiple" id="sndmultiple" cols="" rows="8"></textarea>
		                            <div class="common-div">
		                            	<div class="fl"><a class="text-purple-link" onclick="sngMsg()" href="javascript:;">Cancel</a></div>
		                                <div class="fr"><a id="sndmsg" class="text-purple-link" href="javascript:;" onclick="sendMessage()">Send</a></div>
		                            </div>
		                        </div>
		                    </div>
                               
                               
                                                   	      
                               
                                                         
                                <div class="col1">
                                                   	     
<!-- Tag Popup Outer -->

<!-- Tag Popup Outer --> 
                                                         </div>
                                                         
                                        
                           
                   </div>
                 </div>
				<!-- Manage PoPUP end here -->
			</div>
		</div>
		
		<div class="bookmark-search-right">
		
				<!-- Col3 Starts -->
<?php 
				if( $this->paginator->getTotalItemCount() )
				{
?>				
				<div class="col3">
					<div class="fl text-grey3">
<?php 
						$query_str = "";
						foreach( $this->prms as $key=>$p )
						{
							if( $key == "controller" || $key == "action" || $key == "module" || $key == "list_len" )
							{
								continue;
							}
							$query_str .= $key."=".$p."&amp;";
						}
?>
						VIEWS <a class="text-grey3-link" style="margin-left: 5px"
							href="<?php echo "/".PROJECT_NAME."bookmarks/group?".$query_str."list_len=20";?>"><?php echo $this->prms["list_len"] == 20 ? "<b>20</b>" : '20'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/group?".$query_str."list_len=50";?>"><?php echo $this->prms["list_len"] == 50 ? "<b>50</b>" : '50'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/group?".$query_str."list_len=100";?>"><?php echo $this->prms["list_len"] == 100 ? "<b>100</b>" : '100'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/group?".$query_str."list_len=all";?>"><?php echo $this->prms["list_len"] == 'all' ? "<b>All</b>" : 'All'?></a>
					</div>
					<div class="fr  text-grey3">
<?php
						echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
?>							
					</div>
				</div>
<?php
				}
?>					
				<!-- Col3 Ends -->
                </div>
                
                
		<div class="linkprofile-container">
			<!-- Link Profile Outer Starts -->
			
			<form name="bookmark-form" id="bookmark-form" method="post" action="">
			<div class="linkprofile-outer">
<?php
				echo Helper_common::displayUsersGridView(Auth_UserAdapter::getIdentity ()->getId(), $bookmarkGroupLinks, 1, 1, 1, "You have not bookmarked any profile under this group.");
?>
				<!-- Col1 Starts -->

				
				<!-- Quick-View-Ends -->
			</div>
</form>
<!-- Content Right Right Ends -->
		</div>
	</div>
</div>