<?php
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/short_profile.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/jquery.stylish-select.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/links_menu.js" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/bookmark.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/links-common.css" );
$usr_groups=$this->usr_groups;
echo $this->partial ( 'partials/bookmark_menu.phtml' );
$menu_size = Auth_UserAdapter::getIdentity()->getMain_menu_size();

$bookmarkedUsers = array();
if( $this->paginator->getTotalItemCount() )
{
	foreach ( $this->paginator as $bookmarked )
	{
		$bookmarkedUsers[] = $bookmarked;
	}
}


?>
<style type="text/css">
.botlinks .col2{
	margin: 5px 10px 0 0 !important;
    padding-top: 0 !important;
}
</style>

<!-- Content Right Right Starts -->
<div class="content-right-right">
	<!-- Photo Album Starts -->
	<div class="photoalbum-outer">
		<div class="photoalbum-hdr">
			<h2 style="width: auto;" class="">
				<font class="text-purple2"></font> 
					Bookmarked Profiles
			</h2>
			<div class="bookmarks-hdr-text1" style="margin: 0px">
				<div class="bookmarks-hdr-text1" style="margin-top:0px">
					<div class="fl text-grey3">
						<br>
 <?php 
			 			if($this->paginator->getTotalItemCount()>0)
						{
 ?>

							&nbsp;<font class="text-purple"><a onclick="showManagePopup()" href="javascript:;" class="text-purple-link">Manage</a></font>&nbsp; 
							<img width="16" height="13" align="absmiddle" src="<?php echo IMAGE_PATH;?>/folder-hover.png">
 <?php 
						}
 ?>                       
					</div>
<?php 
	            	if((count($this->bookmarked)>0) || (isset($_REQUEST['bookmarkSearch']))) 
	            	{
?>
						<div class="mail-hdr-search">
							<form name="bookmark-frm" id="bookmark-frm" method="get" action="">
								<a href="javascript:;" class="fr srchBtn" id="bksearch" style="float:right;">Search</a>
								<input type="text" name="bookmarkSearch" id="bookmarkSearch" value="<?php echo @$this->bookmarkSearchText;?>" placeholder="Search" style="float:right;">
							</form>
						</div>	
<?php 
	            	}
?>
                  </div>
			</div>
				
			<!-- Manage POPUP here -->
			<div class="manage-pop-outer" style="display:none;">
				<div class="manage-pop">
					<div class="col1">
						<img width="14" height="16" align="absmiddle" src="<?php echo IMAGE_PATH;?>/icon-trash-hover.png"><a id="remBookmark" onclick="removeBookmark()" class="text-grey2-link" href="javascript:;">Remove From Bookmark</a></div>
							<div class="col1">
								<img width="16" height="13" align="absmiddle" style="margin-top:3px;" src="<?php echo IMAGE_PATH;?>/mail-hover.png"><a onclick="sngMsg()" class="text-grey2-link" href="javascript:;">Send Message</a></div>
                            <div class="msg-popup-outer" style="display:none;">
		                    	<div class="msg-popup-top"><img width="26" height="16" src="<?php echo IMAGE_PATH;?>/arrow-popup.png"></div>
	                        	<div class="msg-popup-bot">
		                        	<h4>Send Message</h4>
		                            <textarea name="sndmultiple" id="sndmultiple" cols="" rows="8"></textarea>
		                            <div class="common-div">
		                            	<div class="fl"><a class="text-purple-link" onclick="sngMsg()" href="javascript:;">Cancel</a></div>
		                                <div class="fr"><a id="sndmsg" class="text-purple-link" href="javascript:;" onclick="sendMessage()">Send</a></div>
		                            </div>
		                        </div>
		                    </div>
							<div class="col1">
								<img width="16" height="16" align="absmiddle" src="<?php echo IMAGE_PATH;?>/icon-pencil-hover.png"><a name="manageTags" class="text-grey2-link" href="javascript:;" id="<?php echo Auth_UserAdapter::getIdentity()->getId();?>" onclick="getManageGrps(this);">Edit Group</a>
								<!-- Tag Popup Outer -->
								<div id="tag-manage-outertags" class="tag-manage-outer" style="display:none;">
									<div class="tag-manage-arrow">
										<img width="26" height="16" src="<?php echo IMAGE_PATH;?>/arrow-popup.png">
									</div>
									<div class="tag-manage" id="tag-manage_<?php echo Auth_UserAdapter::getIdentity()->getId();?>">
										<a onclick="closeEditGroupPopup();" style="float: right;margin-right: -13px;margin-top: -36px;" href="javascript:;"> 
											<img src="<?php echo IMAGE_PATH;?>/cross-grey2.png" alt="Close" title="Close"  align="absmiddle" style="float: right;
											margin: -21px -5px;"/>
										</a>
									</div>
								</div>                                                   	     
								<!-- Tag Popup Outer --> 
							</div>
                                                         
							<div class="col1">
							</div>
						</div>
					</div>
					<!-- Manage PoPUP end here -->
				</div>
			</div>
			<div class="bookmark-search-right">
			<!-- Col3 Starts -->
<?php 
			if( $this->paginator->getTotalItemCount() )
			{
?>				
				<div class="col3">
					<div class="fl text-grey3">
<?php 
						$query_str = "";
						foreach( $this->prms as $key=>$p )
						{
							if( $key == "controller" || $key == "action" || $key == "module" || $key == "list_len" )
							{
								continue;
							}
							$query_str .= $key."=".$p."&amp;";
						}
?>
						VIEWS <a class="text-grey3-link" style="margin-left: 5px"
							href="<?php echo "/".PROJECT_NAME."bookmarks/index?".$query_str."list_len=20";?>"><?php echo $this->prms["list_len"] == 20 ? "<b>20</b>" : '20'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/index?".$query_str."list_len=50";?>"><?php echo $this->prms["list_len"] == 50 ? "<b>50</b>" : '50'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/index?".$query_str."list_len=100";?>"><?php echo $this->prms["list_len"] == 100 ? "<b>100</b>" : '100'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."bookmarks/index?".$query_str."list_len=all";?>"><?php echo $this->prms["list_len"] == 'all' ? "<b>All</b>" : 'All'?></a>
					</div>
					<div class="fr  text-grey3">
<?php
						echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
?>							
					</div>
				</div>
<?php
				}
?>					
				<!-- Col3 Ends -->
			</div>
			<div class="linkprofile-container">
			<!-- Link Profile Outer Starts -->
				<form name="bookmark-form" id="bookmark-form" method="post" action="">
					<div class="linkprofile-outer">
<?php
						echo Helper_common::displayUsersGridView(Auth_UserAdapter::getIdentity ()->getId(),$bookmarkedUsers,1,1,1,"You have not bookmarked any profile.");
?>
					</div>
				</form>
		</div>
		<!-- Content Right Right Ends -->
</div>
