<?php 
// 	$this->headScript()->appendFile( PUBLIC_PATH."/js/jquery-1.8.min.js" );
// 	$this->headScript()->appendFile( PUBLIC_PATH."/js/constants.js" );
// 	echo $this->headScript();
?>
<script type = 'text/javascript'>
/*$(document).ready(function(){
    var link = document.createElement('a');
    link.target = '_blank';
    link.href = '/'+PROJECT_NAME+'dashboard/index';
    link.id = 'profileLink';

    $('body').append(link);
    $('a#profileLink')[0].click();
    $('a#profileLink')[0].remove();
});*/
</script>

<!-- 
<h2>Redirecting you back to <span style = 'color:blue'><a href ='<?php //echo PROJECT_URL.'/'.PROJECT_NAME.'admin/manage-users'?>'><?php echo PROJECT_URL.'/'.PROJECT_NAME.'admin/manage-users' ?></a></span> in 10 seconds...</h2>
<meta http-equiv="refresh" content="10 ;URL='<?php //echo PROJECT_URL.'/'.PROJECT_NAME.'admin/manage-users'?>'">\
 -->