<?php
$this->headTitle()->prepend('Manage Users');
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/manage_users.js" );
/* Including CSS */
// $this->headLink()->appendStylesheet( "//cdn.datatables.net/1.10.7/css/jquery.dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/manage_users.css" );
?>
<div id='heading'>
	<h2>User Management
		<span style = 'float:right; margin-right: 5px;' title = 'Total Users according to current criteria' id = 'num_of_users'></span>
	</h2>
</div>

<div class="content">
	<div id="ilook_dt_wrapper" class="dataTables_wrapper">
		<div class="header_user_mgmt">
		<div class="dataTables_length" id="jquery_dt_length">
			<label>Show <select name="jquery_dt_length" aria-controls="jquery_dt" class="">
					<option value="50">50</option>
					<option value="100">100</option>
					<option value="250">250</option>
					<option value="500">500</option></select> entries
			</label>
			<span class = "buttons">
				<span title="Click to Delete selected users" id = "delete_records"></span>
			</span>
			<span class = "buttons">
				<span title="Click to Disable selected users" id = "disable_records"></span>
			</span>
			<span class = "buttons">
				<span title="Click to Enable selected users" id = "enable_records"></span>
			</span>
			<span class = "buttons">
				<a title="Log in as user" target= "_blank" href = '/<?php echo PROJECT_NAME; ?>admin/manage-users/login-as-user'>
				<span title="Log in as user" id = "login_as_user"></span>
				</a>
			</span>
			
			<span class = "buttons">
				<a title="Post to user wall" href = '/<?php echo PROJECT_NAME; ?>admin/manage-users/post-to-user-wall'>
				<span title="Post to user wall" id = "post_to_user_wall"></span>
				</a>
			</span>
			
		</div>
						
		<div id="jquery_dt_filter" class="dataTables_filter">
			<label>Search:<input type="search" class="" placeholder="" aria-controls="jquery_dt"></label>
		</div>

		<div id="jquery_dt_filter" class="dataTables_filter" style = 'margin-right:10px;'>
			<label>Country:
				<select name = 'country_filter' aria-controls="jquery_dt" style = 'width:150px;'>
				<option value = "">All</option>
<?php 
					$countries = \Extended\country_ref::getAllCountriesUsersRegisteredFrom();
					foreach ( $countries as $country )
					{
						echo "<option value = '".$country->getId()."'>".$country->getName()."</option>";
					}				
?>
					
				</select>
			</label>
		</div>
		
		
		<div id="jquery_dt_filter" class="dataTables_filter" style = 'margin-top:10px;'>
		<span id="user_signup">User Signup:</span>
			<label>
				<span>
					<input class ="date_filter_input user-signup-text" name="from_date" id="from_date" type="text" value="" readonly/>
				</span>
			</label>
			<label>
				<span>
					<input class ="date_filter_input user-signup-text" name="to_date" id="to_date" type="text" value="" readonly/>
					<!-- <input class ="" name="today_date" id="today_date" type="hidden" value="//<?php //date('Y-m-d')?>" readonly/>-->
				</span>
			</label>
			<label>Portal: 
			<select id="created_from_portal" name="jquery_dt_length" id="" aria-controls="jquery_dt" class="">
				<option value = "" selected >All</option>
				<option value =<?php echo \Extended\ilook_user::CREATED_FROM_WEB;?>>Web</option>
				<option value =<?php echo \Extended\ilook_user:: CREATED_FROM_ANDROID?>>Android</option>
				<option value =<?php echo \Extended\ilook_user::CREATED_FROM_IPHONE;?>>iphone</option>
			</select>
			</label>
		</div>
		
		</div>
		<div id="jquery_dt_processing" class="dataTables_processing"
			style="display: none; margin-top:40px;">Processing...</div>
			
		

		<table id="jquery_dt" class="display dataTable" width="100%"
			cellspacing="0" cellpadding="0" border="0" role="grid"
			aria-describedby="jquery_dt_info" style="width: 100%;">
			<thead>  
				<tr role="row">
<!-- 				----------------------------------------------------------------------------------------------------- -->
<!-- 				db_column attribute is set according to doctrine2 query requirement. Please see query in model class. -->
<!-- 				----------------------------------------------------------------------------------------------------- -->
					<th style="width: 2%; text-align:left; padding: 10px 9px;">
					<input type = "checkbox" name = "master_delete_checkbox" class = "master_delete_cb">
					</th>
					<th class="sorting sorting_desc active" tabindex="0"
						aria-controls="jquery_dt" rowspan="1" colspan="1"
						style="width: 3%;" aria-sort="DESC" 
						db_column="usr.id" db_column_alias="idd" position = "2">
						#
					</th>
					<!-- <th colspan ="2" style="width: 20%;">ilook user</th> -->
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width: 9%;" aria-sort="ASC"
						db_column='usr.firstname' db_column_alias="first_name"  position = "3">First Name</th>
					
					<th  class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width:9%;" aria-sort="ASC"
						db_column='usr.lastname' db_column_alias="last_name" position = "4">Last Name</th>
				
 					<th  class="sorting" tabindex="0" aria-controls="jquery_dt" 
						rowspan="1" colspan="1" style="width: 10%;" aria-sort="ASC"
						db_column='usr.email' db_column_alias="email" position = "5">Email</th> 
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width: 20%;" aria-sort="ASC"
						db_column='usr.created_at' db_column_alias="acc_created_at" position = "6">Signup Date</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width: 15%;" aria-sort="ASC"
						db_column='usr.username' db_column_alias="user_name" position = "7">Username</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style=" width: 15%;" aria-sort="ASC"
						db_column='usr.last_login' db_column_alias="last_login_time" position = "8">Last Login</th>
					
					<th class="sorting" tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width: 15%;" aria-sort="ASC"
						db_column='usr.deleted_at' db_column_alias="acc_deleted_at" position = "9">Closed On</th>
						
					<th  tabindex="0" aria-controls="jquery_dt"
						rowspan="1" colspan="1" style="width: 15%;" aria-sort="ASC"
						db_column='city.name' db_column_alias="user_city" position = "9">Country,City</th>
					
					<th class="sorting_disabled" rowspan="1" colspan="1"
						style="width: 10%;"  position = "10">Actions</th>
				</tr>
			</thead>
			<tbody>

			</tbody>
			<tfoot>
				<tr>
					<th rowspan="1" colspan="1"></th>
					<th rowspan="1" colspan="1">#</th>
					<th rowspan="1" colspan="1">First Name</th>
					<th rowspan="1" colspan="1">Last Name</th>
					<th rowspan="1" colspan="1">Email</th>
					<th rowspan="1" colspan="1">Account creation date</th>
					<th rowspan="1" colspan="1">Username</th>
					<th rowspan="1" colspan="1">Last login</th>
					<th rowspan="1" colspan="1">Account closed on</th>
					<th rowspan="1" colspan="1">Country,City</th>
					<th rowspan="1" colspan="1">Actions</th>
				</tr>
			</tfoot>
		</table>

		<div class="dataTables_info" id="jquery_dt_info" role="status"
			aria-live="polite"></div>

		<div class="dataTables_paginate paging_simple_numbers"
			id="jquery_dt_paginate">
			<a class="paginate_button previous disabled" aria-controls="jquery_dt"
				data-dt-idx="" tabindex="0" id="jquery_dt_previous">Previous</a>
				<span id = "page_buttons">
				</span>
			<a class="paginate_button next" aria-controls="jquery_dt" 
				data-dt-idx="" tabindex="0" id="jquery_dt_next">Next</a>
		</div>
	</div>
</div>
<!-- Dialog Box -->
<div style="display:none;" id="dialog_otp" title="OTP">
  <p> Enter OTP sent to you on your email
	<form id ="otp_delete_user_form">
	<input type="text" maxlength=6 name="otp_delete_user" id="otp_delete_user" value="" class="text ui-widget-content ui-corner-all">
	</form>
  </p>
</div>
<div style="display:none;" id="dialog_confirm_delete_users" title="Delete user(s)">
	<p>
		Are you sure you want to close account selected user(s)?
	</p>
</div>
