<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class message_user extends \Entities\message_user implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getMessage_usersMessage_folder()
    {
        $this->__load();
        return parent::getMessage_usersMessage_folder();
    }

    public function setMessage_usersMessage_folder($message_usersMessage_folder)
    {
        $this->__load();
        return parent::setMessage_usersMessage_folder($message_usersMessage_folder);
    }

    public function getMessage_usersSenderUser()
    {
        $this->__load();
        return parent::getMessage_usersSenderUser();
    }

    public function setMessage_usersSenderUser($message_usersSenderUser)
    {
        $this->__load();
        return parent::setMessage_usersSenderUser($message_usersSenderUser);
    }

    public function getMessage_usersRecieverUser()
    {
        $this->__load();
        return parent::getMessage_usersRecieverUser();
    }

    public function setMessage_usersRecieverUser($message_usersRecieverUser)
    {
        $this->__load();
        return parent::setMessage_usersRecieverUser($message_usersRecieverUser);
    }

    public function getMessage_usersMessage()
    {
        $this->__load();
        return parent::getMessage_usersMessage();
    }

    public function setMessage_usersMessage($message_usersMessage)
    {
        $this->__load();
        return parent::setMessage_usersMessage($message_usersMessage);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'message_usersMessage_folder', 'message_usersSenderUser', 'message_usersRecieverUser', 'message_usersMessage');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}