<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class likes extends \Entities\likes implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getIs_liked()
    {
        $this->__load();
        return parent::getIs_liked();
    }

    public function setIs_liked($is_liked)
    {
        $this->__load();
        return parent::setIs_liked($is_liked);
    }

    public function getType()
    {
        $this->__load();
        return parent::getType();
    }

    public function setType($type)
    {
        $this->__load();
        return parent::setType($type);
    }

    public function getLikesWall_post()
    {
        $this->__load();
        return parent::getLikesWall_post();
    }

    public function setLikesWall_post($likesWall_post)
    {
        $this->__load();
        return parent::setLikesWall_post($likesWall_post);
    }

    public function getLikesLiked_by()
    {
        $this->__load();
        return parent::getLikesLiked_by();
    }

    public function setLikesLiked_by($likesLiked_by)
    {
        $this->__load();
        return parent::setLikesLiked_by($likesLiked_by);
    }

    public function getLikesSocialise_album()
    {
        $this->__load();
        return parent::getLikesSocialise_album();
    }

    public function setLikesSocialise_album($likesSocialise_album)
    {
        $this->__load();
        return parent::setLikesSocialise_album($likesSocialise_album);
    }

    public function getLikesSocialise_photo()
    {
        $this->__load();
        return parent::getLikesSocialise_photo();
    }

    public function setLikesSocialise_photo($likesSocialise_photo)
    {
        $this->__load();
        return parent::setLikesSocialise_photo($likesSocialise_photo);
    }

    public function getBlogs()
    {
        $this->__load();
        return parent::getBlogs();
    }

    public function setBlogs($blogs)
    {
        $this->__load();
        return parent::setBlogs($blogs);
    }

    public function getPhotoGroup()
    {
        $this->__load();
        return parent::getPhotoGroup();
    }

    public function setPhotoGroup($photoGroup)
    {
        $this->__load();
        return parent::setPhotoGroup($photoGroup);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'is_liked', 'type', 'likesWall_post', 'likesLiked_by', 'likesSocialise_album', 'likesSocialise_photo', 'blogs', 'photoGroup');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}