<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class link_bookmark_groups extends \Entities\link_bookmark_groups implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLink_groupsCreatedbyUser()
    {
        $this->__load();
        return parent::getLink_groupsCreatedbyUser();
    }

    public function setLink_groupsCreatedbyUser($link_groupsCreatedbyUser)
    {
        $this->__load();
        return parent::setLink_groupsCreatedbyUser($link_groupsCreatedbyUser);
    }

    public function getLink_groupsAssignedUser()
    {
        $this->__load();
        return parent::getLink_groupsAssignedUser();
    }

    public function setLink_groupsAssignedUser($link_groupsAssignedUser)
    {
        $this->__load();
        return parent::setLink_groupsAssignedUser($link_groupsAssignedUser);
    }

    public function getLink_groupsUser_groups()
    {
        $this->__load();
        return parent::getLink_groupsUser_groups();
    }

    public function setLink_groupsUser_groups($link_groupsUser_groups)
    {
        $this->__load();
        return parent::setLink_groupsUser_groups($link_groupsUser_groups);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'link_groupsCreatedbyUser', 'link_groupsAssignedUser', 'link_groupsUser_groups');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}