<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class message extends \Entities\message implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getSubject()
    {
        $this->__load();
        return parent::getSubject();
    }

    public function setSubject($subject)
    {
        $this->__load();
        return parent::setSubject($subject);
    }

    public function getContents()
    {
        $this->__load();
        return parent::getContents();
    }

    public function setContents($contents)
    {
        $this->__load();
        return parent::setContents($contents);
    }

    public function getMsg_type()
    {
        $this->__load();
        return parent::getMsg_type();
    }

    public function setMsg_type($msg_type)
    {
        $this->__load();
        return parent::setMsg_type($msg_type);
    }

    public function getHide_reply_forward_opt()
    {
        $this->__load();
        return parent::getHide_reply_forward_opt();
    }

    public function setHide_reply_forward_opt($hide_reply_forward_opt)
    {
        $this->__load();
        return parent::setHide_reply_forward_opt($hide_reply_forward_opt);
    }

    public function getLink_req_id()
    {
        $this->__load();
        return parent::getLink_req_id();
    }

    public function setLink_req_id($link_req_id)
    {
        $this->__load();
        return parent::setLink_req_id($link_req_id);
    }

    public function getRef_req_id()
    {
        $this->__load();
        return parent::getRef_req_id();
    }

    public function setRef_req_id($ref_req_id)
    {
        $this->__load();
        return parent::setRef_req_id($ref_req_id);
    }

    public function getFeedbk_req_id()
    {
        $this->__load();
        return parent::getFeedbk_req_id();
    }

    public function setFeedbk_req_id($feedbk_req_id)
    {
        $this->__load();
        return parent::setFeedbk_req_id($feedbk_req_id);
    }

    public function getJob_id()
    {
        $this->__load();
        return parent::getJob_id();
    }

    public function setJob_id($job_id)
    {
        $this->__load();
        return parent::setJob_id($job_id);
    }

    public function getWallpost_id()
    {
        $this->__load();
        return parent::getWallpost_id();
    }

    public function setWallpost_id($wallpost_id)
    {
        $this->__load();
        return parent::setWallpost_id($wallpost_id);
    }

    public function getPhotoId()
    {
        $this->__load();
        return parent::getPhotoId();
    }

    public function setPhotoId($photo_id)
    {
        $this->__load();
        return parent::setPhotoId($photo_id);
    }

    public function getReported_abuse_wallpost_id()
    {
        $this->__load();
        return parent::getReported_abuse_wallpost_id();
    }

    public function setReported_abuse_wallpost_id($reported_abuse_wallpost_id)
    {
        $this->__load();
        return parent::setReported_abuse_wallpost_id($reported_abuse_wallpost_id);
    }

    public function getEnquiry_id()
    {
        $this->__load();
        return parent::getEnquiry_id();
    }

    public function setEnquiry_id($enquiry_id)
    {
        $this->__load();
        return parent::setEnquiry_id($enquiry_id);
    }

    public function getMessageMessage_attachment()
    {
        $this->__load();
        return parent::getMessageMessage_attachment();
    }

    public function setMessageMessage_attachment($messageMessage_attachment)
    {
        $this->__load();
        return parent::setMessageMessage_attachment($messageMessage_attachment);
    }

    public function getMessagesMessage_user()
    {
        $this->__load();
        return parent::getMessagesMessage_user();
    }

    public function setMessagesMessage_user($MessagesMessage_user)
    {
        $this->__load();
        return parent::setMessagesMessage_user($MessagesMessage_user);
    }

    public function getMessagesMessage_folder()
    {
        $this->__load();
        return parent::getMessagesMessage_folder();
    }

    public function setMessagesMessage_folder($MessagesMessage_folder)
    {
        $this->__load();
        return parent::setMessagesMessage_folder($MessagesMessage_folder);
    }

    public function getMessagesUser()
    {
        $this->__load();
        return parent::getMessagesUser();
    }

    public function setMessagesUser($messagesUser)
    {
        $this->__load();
        return parent::setMessagesUser($messagesUser);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }

    public function getContents_json()
    {
        $this->__load();
        return parent::getContents_json();
    }

    public function setContents_json($contents_json)
    {
        $this->__load();
        return parent::setContents_json($contents_json);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'subject', 'contents', 'msg_type', 'hide_reply_forward_opt', 'link_req_id', 'ref_req_id', 'feedbk_req_id', 'job_id', 'wallpost_id', 'photo_id', 'reported_abuse_wallpost_id', 'enquiry_id', 'contents_json', 'created_at', 'messageMessage_attachment', 'MessagesMessage_user', 'MessagesMessage_folder', 'messagesUser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}