<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class education_detail extends \Entities\education_detail implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getDuration_from()
    {
        $this->__load();
        return parent::getDuration_from();
    }

    public function setDuration_from($duration_from)
    {
        $this->__load();
        return parent::setDuration_from($duration_from);
    }

    public function getDuration_to()
    {
        $this->__load();
        return parent::getDuration_to();
    }

    public function setDuration_to($duration_to)
    {
        $this->__load();
        return parent::setDuration_to($duration_to);
    }

    public function getGrade()
    {
        $this->__load();
        return parent::getGrade();
    }

    public function setGrade($grade)
    {
        $this->__load();
        return parent::setGrade($grade);
    }

    public function getAcitivities()
    {
        $this->__load();
        return parent::getAcitivities();
    }

    public function setAcitivities($acitivities)
    {
        $this->__load();
        return parent::setAcitivities($acitivities);
    }

    public function getNotes()
    {
        $this->__load();
        return parent::getNotes();
    }

    public function setNotes($notes)
    {
        $this->__load();
        return parent::setNotes($notes);
    }

    public function getDegree()
    {
        $this->__load();
        return parent::getDegree();
    }

    public function setDegree($degree)
    {
        $this->__load();
        return parent::setDegree($degree);
    }

    public function getLocation()
    {
        $this->__load();
        return parent::getLocation();
    }

    public function setLocation($location)
    {
        $this->__load();
        return parent::setLocation($location);
    }

    public function getEducation_detailsDegree()
    {
        $this->__load();
        return parent::getEducation_detailsDegree();
    }

    public function setEducation_detailsDegree($education_detailsDegree)
    {
        $this->__load();
        return parent::setEducation_detailsDegree($education_detailsDegree);
    }

    public function getEducationsUser()
    {
        $this->__load();
        return parent::getEducationsUser();
    }

    public function setEducationsUser($educationsUser)
    {
        $this->__load();
        return parent::setEducationsUser($educationsUser);
    }

    public function getEducation_detailsField_of_study_ref()
    {
        $this->__load();
        return parent::getEducation_detailsField_of_study_ref();
    }

    public function setEducation_detailsField_of_study_ref($education_detailsField_of_study_ref)
    {
        $this->__load();
        return parent::setEducation_detailsField_of_study_ref($education_detailsField_of_study_ref);
    }

    public function getEducation_detailsSchool()
    {
        $this->__load();
        return parent::getEducation_detailsSchool();
    }

    public function setEducation_detailsSchool($education_detailsSchool)
    {
        $this->__load();
        return parent::setEducation_detailsSchool($education_detailsSchool);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'duration_from', 'duration_to', 'grade', 'acitivities', 'notes', 'degree', 'location', 'education_detailsDegree', 'educationsUser', 'education_detailsField_of_study_ref', 'education_detailsSchool');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}