<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class skill_ref extends \Entities\skill_ref implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getSkill()
    {
        $this->__load();
        return parent::getSkill();
    }

    public function setSkill($skill)
    {
        $this->__load();
        return parent::setSkill($skill);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getIlook_user_id()
    {
        $this->__load();
        return parent::getIlook_user_id();
    }

    public function setIlook_user_id($ilook_user_id)
    {
        $this->__load();
        return parent::setIlook_user_id($ilook_user_id);
    }

    public function getSkillsSupport_skill()
    {
        $this->__load();
        return parent::getSkillsSupport_skill();
    }

    public function setSkillsSupport_skill($skillsSupport_skill)
    {
        $this->__load();
        return parent::setSkillsSupport_skill($skillsSupport_skill);
    }

    public function getSkillsUser_skills()
    {
        $this->__load();
        return parent::getSkillsUser_skills();
    }

    public function setSkillsUser_skills($skillsUser_skills)
    {
        $this->__load();
        return parent::setSkillsUser_skills($skillsUser_skills);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }

    public function getUpdated_at()
    {
        $this->__load();
        return parent::getUpdated_at();
    }

    public function setUpdated_at($updated_at)
    {
        $this->__load();
        return parent::setUpdated_at($updated_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'skill', 'description', 'status', 'ilook_user_id', 'created_at', 'updated_at', 'skillsSupport_skill', 'skillsUser_skills');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}