<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class admin extends \Entities\admin implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getFirstname()
    {
        $this->__load();
        return parent::getFirstname();
    }

    public function setFirstname($firstname)
    {
        $this->__load();
        return parent::setFirstname($firstname);
    }

    public function getLastname()
    {
        $this->__load();
        return parent::getLastname();
    }

    public function setLastname($lastname)
    {
        $this->__load();
        return parent::setLastname($lastname);
    }

    public function getEmail_id()
    {
        $this->__load();
        return parent::getEmail_id();
    }

    public function setEmail_id($email_id)
    {
        $this->__load();
        return parent::setEmail_id($email_id);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getSix_digit_general_password()
    {
        $this->__load();
        return parent::getSix_digit_general_password();
    }

    public function setSix_digit_general_password($six_digit_general_password)
    {
        $this->__load();
        return parent::setSix_digit_general_password($six_digit_general_password);
    }

    public function getExpiry_date()
    {
        $this->__load();
        return parent::getExpiry_date();
    }

    public function setExpiry_date($expiry_date)
    {
        $this->__load();
        return parent::setExpiry_date($expiry_date);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getIs_first_time_login()
    {
        $this->__load();
        return parent::getIs_first_time_login();
    }

    public function setIs_first_time_login($is_first_time_login)
    {
        $this->__load();
        return parent::setIs_first_time_login($is_first_time_login);
    }

    public function getProfile_picture()
    {
        $this->__load();
        return parent::getProfile_picture();
    }

    public function setProfile_picture($profile_picture)
    {
        $this->__load();
        return parent::setProfile_picture($profile_picture);
    }

    public function getOtp()
    {
        $this->__load();
        return parent::getOtp();
    }

    public function setOtp($otp)
    {
        $this->__load();
        return parent::setOtp($otp);
    }

    public function getRole()
    {
        $this->__load();
        return parent::getRole();
    }

    public function setRole($role)
    {
        $this->__load();
        return parent::setRole($role);
    }

    public function getAdminActivityLog()
    {
        $this->__load();
        return parent::getAdminActivityLog();
    }

    public function setAdminActivityLog($adminActivityLog)
    {
        $this->__load();
        return parent::setAdminActivityLog($adminActivityLog);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'firstname', 'lastname', 'email_id', 'password', 'six_digit_general_password', 'expiry_date', 'status', 'is_first_time_login', 'profile_picture', 'otp', 'adminActivityLog', 'role');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}