<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class message_folder extends \Entities\message_folder implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getMark_read()
    {
        $this->__load();
        return parent::getMark_read();
    }

    public function setMark_read($mark_read)
    {
        $this->__load();
        return parent::setMark_read($mark_read);
    }

    public function getMark_seen()
    {
        $this->__load();
        return parent::getMark_seen();
    }

    public function setMark_seen($mark_seen)
    {
        $this->__load();
        return parent::setMark_seen($mark_seen);
    }

    public function getMessage_foldersUser_folder()
    {
        $this->__load();
        return parent::getMessage_foldersUser_folder();
    }

    public function setMessage_foldersUser_folder($message_foldersUser_folder)
    {
        $this->__load();
        return parent::setMessage_foldersUser_folder($message_foldersUser_folder);
    }

    public function getMessage_foldersMessage()
    {
        $this->__load();
        return parent::getMessage_foldersMessage();
    }

    public function setMessage_foldersMessage($message_foldersMessage)
    {
        $this->__load();
        return parent::setMessage_foldersMessage($message_foldersMessage);
    }

    public function getMessage_foldersMessage_user()
    {
        $this->__load();
        return parent::getMessage_foldersMessage_user();
    }

    public function setMessage_foldersMessage_user($message_foldersMessage_user)
    {
        $this->__load();
        return parent::setMessage_foldersMessage_user($message_foldersMessage_user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'mark_read', 'mark_seen', 'message_foldersUser_folder', 'message_foldersMessage', 'message_foldersMessage_user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}