<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class who_viewed_profiles extends \Entities\who_viewed_profiles implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getLast_viewed()
    {
        $this->__load();
        return parent::getLast_viewed();
    }

    public function setLast_viewed($last_viewed)
    {
        $this->__load();
        return parent::setLast_viewed($last_viewed);
    }

    public function getTotal_views()
    {
        $this->__load();
        return parent::getTotal_views();
    }

    public function setTotal_views($total_views)
    {
        $this->__load();
        return parent::setTotal_views($total_views);
    }

    public function getProfile_holdersIlook_user()
    {
        $this->__load();
        return parent::getProfile_holdersIlook_user();
    }

    public function setProfile_holdersIlook_user($profile_holdersIlook_user)
    {
        $this->__load();
        return parent::setProfile_holdersIlook_user($profile_holdersIlook_user);
    }

    public function getVisitorsIlook_user()
    {
        $this->__load();
        return parent::getVisitorsIlook_user();
    }

    public function setVisitorsIlook_user($visitorsIlook_user)
    {
        $this->__load();
        return parent::setVisitorsIlook_user($visitorsIlook_user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'last_viewed', 'total_views', 'profile_holdersIlook_user', 'visitorsIlook_user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}