<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class socialise_album extends \Entities\socialise_album implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getAlbum_name()
    {
        $this->__load();
        return parent::getAlbum_name();
    }

    public function setAlbum_name($album_name)
    {
        $this->__load();
        return parent::setAlbum_name($album_name);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getPhoto_count()
    {
        $this->__load();
        return parent::getPhoto_count();
    }

    public function setPhoto_count($photo_count)
    {
        $this->__load();
        return parent::setPhoto_count($photo_count);
    }

    public function getComment_count()
    {
        $this->__load();
        return parent::getComment_count();
    }

    public function setComment_count($comment_count)
    {
        $this->__load();
        return parent::setComment_count($comment_count);
    }

    public function getLike_count()
    {
        $this->__load();
        return parent::getLike_count();
    }

    public function setLike_count($like_count)
    {
        $this->__load();
        return parent::setLike_count($like_count);
    }

    public function getVisibility_criteria()
    {
        $this->__load();
        return parent::getVisibility_criteria();
    }

    public function setVisibility_criteria($visibility_criteria)
    {
        $this->__load();
        return parent::setVisibility_criteria($visibility_criteria);
    }

    public function getCreated_at_timestamp()
    {
        $this->__load();
        return parent::getCreated_at_timestamp();
    }

    public function setCreated_at_timestamp($created_at_timestamp)
    {
        $this->__load();
        return parent::setCreated_at_timestamp($created_at_timestamp);
    }

    public function getAlbum_display_name()
    {
        $this->__load();
        return parent::getAlbum_display_name();
    }

    public function setAlbum_display_name($album_display_name)
    {
        $this->__load();
        return parent::setAlbum_display_name($album_display_name);
    }

    public function getSocialise_albumsWall_post()
    {
        $this->__load();
        return parent::getSocialise_albumsWall_post();
    }

    public function setSocialise_albumsWall_post($socialise_albumsWall_post)
    {
        $this->__load();
        return parent::setSocialise_albumsWall_post($socialise_albumsWall_post);
    }

    public function getSocialise_albumsLike()
    {
        $this->__load();
        return parent::getSocialise_albumsLike();
    }

    public function setSocialise_albumsLike($socialise_albumsLike)
    {
        $this->__load();
        return parent::setSocialise_albumsLike($socialise_albumsLike);
    }

    public function getShare()
    {
        $this->__load();
        return parent::getShare();
    }

    public function setShare($share)
    {
        $this->__load();
        return parent::setShare($share);
    }

    public function getSocialise_albumsSocialise_photo()
    {
        $this->__load();
        return parent::getSocialise_albumsSocialise_photo();
    }

    public function setSocialise_albumsSocialise_photo($socialise_albumsSocialise_photo)
    {
        $this->__load();
        return parent::setSocialise_albumsSocialise_photo($socialise_albumsSocialise_photo);
    }

    public function getSocialise_albumsComment()
    {
        $this->__load();
        return parent::getSocialise_albumsComment();
    }

    public function setSocialise_albumsComment($socialise_albumsComment)
    {
        $this->__load();
        return parent::setSocialise_albumsComment($socialise_albumsComment);
    }

    public function getSocialiseAlbumCustomPrivacy()
    {
        $this->__load();
        return parent::getSocialiseAlbumCustomPrivacy();
    }

    public function setSocialiseAlbumCustomPrivacy($socialiseAlbumCustomPrivacy)
    {
        $this->__load();
        return parent::setSocialiseAlbumCustomPrivacy($socialiseAlbumCustomPrivacy);
    }

    public function getSocialise_albumIlook_user()
    {
        $this->__load();
        return parent::getSocialise_albumIlook_user();
    }

    public function setSocialise_albumIlook_user($socialise_albumIlook_user)
    {
        $this->__load();
        return parent::setSocialise_albumIlook_user($socialise_albumIlook_user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'album_name', 'description', 'photo_count', 'comment_count', 'like_count', 'visibility_criteria', 'created_at_timestamp', 'album_display_name', 'socialise_albumsWall_post', 'socialise_albumsLike', 'share', 'socialise_albumsSocialise_photo', 'socialise_albumsComment', 'socialiseAlbumCustomPrivacy', 'socialise_albumIlook_user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}