<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class wall_post extends \Entities\wall_post implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getPost_update_type()
    {
        $this->__load();
        return parent::getPost_update_type();
    }

    public function setPost_update_type($post_update_type)
    {
        $this->__load();
        return parent::setPost_update_type($post_update_type);
    }

    public function getWall_post_text()
    {
        $this->__load();
        return parent::getWall_post_text();
    }

    public function setWall_post_text($wall_post_text)
    {
        $this->__load();
        return parent::setWall_post_text($wall_post_text);
    }

    public function getWall_post_text_when_shared()
    {
        $this->__load();
        return parent::getWall_post_text_when_shared();
    }

    public function setWall_post_text_when_shared($wall_post_text_when_shared)
    {
        $this->__load();
        return parent::setWall_post_text_when_shared($wall_post_text_when_shared);
    }

    public function getVisibility_criteria()
    {
        $this->__load();
        return parent::getVisibility_criteria();
    }

    public function setVisibility_criteria($visibility_criteria)
    {
        $this->__load();
        return parent::setVisibility_criteria($visibility_criteria);
    }

    public function getComment_count()
    {
        $this->__load();
        return parent::getComment_count();
    }

    public function setComment_count($comment_count)
    {
        $this->__load();
        return parent::setComment_count($comment_count);
    }

    public function getLike_count()
    {
        $this->__load();
        return parent::getLike_count();
    }

    public function setLike_count($like_count)
    {
        $this->__load();
        return parent::setLike_count($like_count);
    }

    public function getPost_type()
    {
        $this->__load();
        return parent::getPost_type();
    }

    public function setPost_type($post_type)
    {
        $this->__load();
        return parent::setPost_type($post_type);
    }

    public function getGroup_id()
    {
        $this->__load();
        return parent::getGroup_id();
    }

    public function setGroup_id($group_id)
    {
        $this->__load();
        return parent::setGroup_id($group_id);
    }

    public function getJob_id()
    {
        $this->__load();
        return parent::getJob_id();
    }

    public function setJob_id($job_id)
    {
        $this->__load();
        return parent::setJob_id($job_id);
    }

    public function getCompany_id()
    {
        $this->__load();
        return parent::getCompany_id();
    }

    public function setCompany_id($company_id)
    {
        $this->__load();
        return parent::setCompany_id($company_id);
    }

    public function getWall_type()
    {
        $this->__load();
        return parent::getWall_type();
    }

    public function setWall_type($wall_type)
    {
        $this->__load();
        return parent::setWall_type($wall_type);
    }

    public function getShare_count()
    {
        $this->__load();
        return parent::getShare_count();
    }

    public function setShare_count($share_count)
    {
        $this->__load();
        return parent::setShare_count($share_count);
    }

    public function getLink_data()
    {
        $this->__load();
        return parent::getLink_data();
    }

    public function setLink_data($link_data)
    {
        $this->__load();
        return parent::setLink_data($link_data);
    }

    public function getPhotoGroup()
    {
        $this->__load();
        return parent::getPhotoGroup();
    }

    public function setPhotoGroup($photoGroup)
    {
        $this->__load();
        return parent::setPhotoGroup($photoGroup);
    }

    public function getSocialisePhoto()
    {
        $this->__load();
        return parent::getSocialisePhoto();
    }

    public function setSocialisePhoto($socialisePhoto)
    {
        $this->__load();
        return parent::setSocialisePhoto($socialisePhoto);
    }

    public function getWall_postsLikes()
    {
        $this->__load();
        return parent::getWall_postsLikes();
    }

    public function setWall_postsLikes($wall_postsLikes)
    {
        $this->__load();
        return parent::setWall_postsLikes($wall_postsLikes);
    }

    public function getWall_postsShare()
    {
        $this->__load();
        return parent::getWall_postsShare();
    }

    public function setWall_postsShare($wall_postsShare)
    {
        $this->__load();
        return parent::setWall_postsShare($wall_postsShare);
    }

    public function getWall_postsComment()
    {
        $this->__load();
        return parent::getWall_postsComment();
    }

    public function setWall_postsComment($wall_postsComment)
    {
        $this->__load();
        return parent::setWall_postsComment($wall_postsComment);
    }

    public function getShared_from_wallpost()
    {
        $this->__load();
        return parent::getShared_from_wallpost();
    }

    public function setShared_from_wallpost($shared_from_wallpost)
    {
        $this->__load();
        return parent::setShared_from_wallpost($shared_from_wallpost);
    }

    public function getWishes()
    {
        $this->__load();
        return parent::getWishes();
    }

    public function setWishes($wishes)
    {
        $this->__load();
        return parent::setWishes($wishes);
    }

    public function getReportAbusePost()
    {
        $this->__load();
        return parent::getReportAbusePost();
    }

    public function setReportAbusePost($reportAbusePost)
    {
        $this->__load();
        return parent::setReportAbusePost($reportAbusePost);
    }

    public function getWall_postsLink_request()
    {
        $this->__load();
        return parent::getWall_postsLink_request();
    }

    public function setWall_postsLink_request($wall_postsLink_request)
    {
        $this->__load();
        return parent::setWall_postsLink_request($wall_postsLink_request);
    }

    public function getWall_postsSocialise_album()
    {
        $this->__load();
        return parent::getWall_postsSocialise_album();
    }

    public function setWall_postsSocialise_album($wall_postsSocialise_album)
    {
        $this->__load();
        return parent::setWall_postsSocialise_album($wall_postsSocialise_album);
    }

    public function getWall_postsFrom_user()
    {
        $this->__load();
        return parent::getWall_postsFrom_user();
    }

    public function setWall_postsFrom_user($wall_postsFrom_user)
    {
        $this->__load();
        return parent::setWall_postsFrom_user($wall_postsFrom_user);
    }

    public function getWall_postsOriginal_user()
    {
        $this->__load();
        return parent::getWall_postsOriginal_user();
    }

    public function setWall_postsOriginal_user($wall_postsOriginal_user)
    {
        $this->__load();
        return parent::setWall_postsOriginal_user($wall_postsOriginal_user);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }

    public function getLast_activity_datetime()
    {
        $this->__load();
        return parent::getLast_activity_datetime();
    }

    public function setLast_activity_datetime($last_activity_datetime)
    {
        $this->__load();
        return parent::setLast_activity_datetime($last_activity_datetime);
    }

    public function getPostedTo()
    {
        $this->__load();
        return parent::getPostedTo();
    }

    public function setPostedTo($postedTo)
    {
        $this->__load();
        return parent::setPostedTo($postedTo);
    }

    public function getPostTags()
    {
        $this->__load();
        return parent::getPostTags();
    }

    public function setPostTags($postTags)
    {
        $this->__load();
        return parent::setPostTags($postTags);
    }

    public function getShared_wallpost()
    {
        $this->__load();
        return parent::getShared_wallpost();
    }

    public function setShared_wallpost($shared_wallpost)
    {
        $this->__load();
        return parent::setShared_wallpost($shared_wallpost);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'post_update_type', 'wall_post_text', 'wall_post_text_when_shared', 'visibility_criteria', 'comment_count', 'like_count', 'post_type', 'group_id', 'job_id', 'company_id', 'wall_type', 'share_count', 'link_data', 'created_at', 'last_activity_datetime', 'photoGroup', 'socialisePhoto', 'wall_postsLikes', 'wall_postsShare', 'wall_postsComment', 'wishes', 'reportAbusePost', 'wall_postsLink_request', 'wall_postsSocialise_album', 'wall_postsOriginal_user', 'wall_postsFrom_user', 'postedTo', 'postTags', 'shared_from_wallpost', 'shared_wallpost');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}