<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class support_skill extends \Entities\support_skill implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getSupport_or_block()
    {
        $this->__load();
        return parent::getSupport_or_block();
    }

    public function setSupport_or_block($support_or_block)
    {
        $this->__load();
        return parent::setSupport_or_block($support_or_block);
    }

    public function getSupport_skillsSkill()
    {
        $this->__load();
        return parent::getSupport_skillsSkill();
    }

    public function setSupport_skillsSkill($support_skillsSkill)
    {
        $this->__load();
        return parent::setSupport_skillsSkill($support_skillsSkill);
    }

    public function getSupport_skillsSupporter_user()
    {
        $this->__load();
        return parent::getSupport_skillsSupporter_user();
    }

    public function setSupport_skillsSupporter_user($support_skillsSupporter_user)
    {
        $this->__load();
        return parent::setSupport_skillsSupporter_user($support_skillsSupporter_user);
    }

    public function getSupport_skillsIlook_user()
    {
        $this->__load();
        return parent::getSupport_skillsIlook_user();
    }

    public function setSupport_skillsIlook_user($support_skillsIlook_user)
    {
        $this->__load();
        return parent::setSupport_skillsIlook_user($support_skillsIlook_user);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }

    public function getUpdated_at()
    {
        $this->__load();
        return parent::getUpdated_at();
    }

    public function setUpdated_at($updated_at)
    {
        $this->__load();
        return parent::setUpdated_at($updated_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'support_or_block', 'created_at', 'updated_at', 'support_skillsSkill', 'support_skillsSupporter_user', 'support_skillsIlook_user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}