<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class country_ref extends \Entities\country_ref implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function setStatus($status)
    {
        $this->__load();
        return parent::setStatus($status);
    }

    public function getCode()
    {
        $this->__load();
        return parent::getCode();
    }

    public function setCode($code)
    {
        $this->__load();
        return parent::setCode($code);
    }

    public function getHave_states()
    {
        $this->__load();
        return parent::getHave_states();
    }

    public function setHave_states($have_states)
    {
        $this->__load();
        return parent::setHave_states($have_states);
    }

    public function getCurrency_symbol()
    {
        $this->__load();
        return parent::getCurrency_symbol();
    }

    public function setCurrency_symbol($currency_symbol)
    {
        $this->__load();
        return parent::setCurrency_symbol($currency_symbol);
    }

    public function getCountrysUser()
    {
        $this->__load();
        return parent::getCountrysUser();
    }

    public function setCountrysUser($countrysUser)
    {
        $this->__load();
        return parent::setCountrysUser($countrysUser);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getState()
    {
        $this->__load();
        return parent::getState();
    }

    public function setState($state)
    {
        $this->__load();
        return parent::setState($state);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getSalaryRange()
    {
        $this->__load();
        return parent::getSalaryRange();
    }

    public function setSalaryRange($salaryRange)
    {
        $this->__load();
        return parent::setSalaryRange($salaryRange);
    }

    public function getSavedSearch()
    {
        $this->__load();
        return parent::getSavedSearch();
    }

    public function setSavedSearch($savedSearch)
    {
        $this->__load();
        return parent::setSavedSearch($savedSearch);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'status', 'code', 'have_states', 'currency_symbol', 'countrysUser', 'job', 'state', 'city', 'salaryRange', 'savedSearch');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}