<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class salary_range extends \Entities\salary_range implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getMin_salary()
    {
        $this->__load();
        return parent::getMin_salary();
    }

    public function setMin_salary($min_salary)
    {
        $this->__load();
        return parent::setMin_salary($min_salary);
    }

    public function getMax_salary()
    {
        $this->__load();
        return parent::getMax_salary();
    }

    public function setMax_salary($max_salary)
    {
        $this->__load();
        return parent::setMax_salary($max_salary);
    }

    public function getJob()
    {
        $this->__load();
        return parent::getJob();
    }

    public function setJob($job)
    {
        $this->__load();
        return parent::setJob($job);
    }

    public function getSavedSearch()
    {
        $this->__load();
        return parent::getSavedSearch();
    }

    public function setSavedSearch($savedSearch)
    {
        $this->__load();
        return parent::setSavedSearch($savedSearch);
    }

    public function getCountryRef()
    {
        $this->__load();
        return parent::getCountryRef();
    }

    public function setCountryRef($countryRef)
    {
        $this->__load();
        return parent::setCountryRef($countryRef);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'min_salary', 'max_salary', 'job', 'savedSearch', 'countryRef');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}