<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class user_tags extends \Entities\user_tags implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getTag_title()
    {
        $this->__load();
        return parent::getTag_title();
    }

    public function setTag_title($tag_title)
    {
        $this->__load();
        return parent::setTag_title($tag_title);
    }

    public function getUser_tagsLink_tags()
    {
        $this->__load();
        return parent::getUser_tagsLink_tags();
    }

    public function setUser_tagsLink_tags($user_tagsLink_tags)
    {
        $this->__load();
        return parent::setUser_tagsLink_tags($user_tagsLink_tags);
    }

    public function getUser_tagsUser()
    {
        $this->__load();
        return parent::getUser_tagsUser();
    }

    public function setUser_tagsUser($user_tagsUser)
    {
        $this->__load();
        return parent::setUser_tagsUser($user_tagsUser);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'tag_title', 'user_tagsLink_tags', 'user_tagsUser');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}