<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class feedback_requests extends \Entities\feedback_requests implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getProvider_msg()
    {
        $this->__load();
        return parent::getProvider_msg();
    }

    public function setProvider_msg($provider_msg)
    {
        $this->__load();
        return parent::setProvider_msg($provider_msg);
    }

    public function getIs_accepted()
    {
        $this->__load();
        return parent::getIs_accepted();
    }

    public function setIs_accepted($is_accepted)
    {
        $this->__load();
        return parent::setIs_accepted($is_accepted);
    }

    public function getVisibility_criteria()
    {
        $this->__load();
        return parent::getVisibility_criteria();
    }

    public function setVisibility_criteria($visibility_criteria)
    {
        $this->__load();
        return parent::setVisibility_criteria($visibility_criteria);
    }

    public function getRequester_msg()
    {
        $this->__load();
        return parent::getRequester_msg();
    }

    public function setRequester_msg($requester_msg)
    {
        $this->__load();
        return parent::setRequester_msg($requester_msg);
    }

    public function getRequest_for_the_position()
    {
        $this->__load();
        return parent::getRequest_for_the_position();
    }

    public function setRequest_for_the_position($request_for_the_position)
    {
        $this->__load();
        return parent::setRequest_for_the_position($request_for_the_position);
    }

    public function getProvide_for_the_position()
    {
        $this->__load();
        return parent::getProvide_for_the_position();
    }

    public function setProvide_for_the_position($provide_for_the_position)
    {
        $this->__load();
        return parent::setProvide_for_the_position($provide_for_the_position);
    }

    public function getRequested_as()
    {
        $this->__load();
        return parent::getRequested_as();
    }

    public function setRequested_as($requested_as)
    {
        $this->__load();
        return parent::setRequested_as($requested_as);
    }

    public function getProvided_as()
    {
        $this->__load();
        return parent::getProvided_as();
    }

    public function setProvided_as($provided_as)
    {
        $this->__load();
        return parent::setProvided_as($provided_as);
    }

    public function getProvided_at()
    {
        $this->__load();
        return parent::getProvided_at();
    }

    public function setProvided_at($provided_at)
    {
        $this->__load();
        return parent::setProvided_at($provided_at);
    }

    public function getFeedback_requestRequester_user()
    {
        $this->__load();
        return parent::getFeedback_requestRequester_user();
    }

    public function setFeedback_requestRequester_user($feedback_requestRequester_user)
    {
        $this->__load();
        return parent::setFeedback_requestRequester_user($feedback_requestRequester_user);
    }

    public function getFeedback_requestProvider_user()
    {
        $this->__load();
        return parent::getFeedback_requestProvider_user();
    }

    public function setFeedback_requestProvider_user($feedback_requestProvider_user)
    {
        $this->__load();
        return parent::setFeedback_requestProvider_user($feedback_requestProvider_user);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'provider_msg', 'is_accepted', 'visibility_criteria', 'requester_msg', 'request_for_the_position', 'provide_for_the_position', 'requested_as', 'provided_as', 'provided_at', 'created_at', 'feedback_requestRequester_user', 'feedback_requestProvider_user');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}