<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class socialise_photo extends \Entities\socialise_photo implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setId($id)
    {
        $this->__load();
        return parent::setId($id);
    }

    public function getImage_name()
    {
        $this->__load();
        return parent::getImage_name();
    }

    public function setImage_name($image_name)
    {
        $this->__load();
        return parent::setImage_name($image_name);
    }

    public function getDescription()
    {
        $this->__load();
        return parent::getDescription();
    }

    public function setDescription($description)
    {
        $this->__load();
        return parent::setDescription($description);
    }

    public function getComment_count()
    {
        $this->__load();
        return parent::getComment_count();
    }

    public function setComment_count($comment_count)
    {
        $this->__load();
        return parent::setComment_count($comment_count);
    }

    public function getLike_count()
    {
        $this->__load();
        return parent::getLike_count();
    }

    public function setLike_count($like_count)
    {
        $this->__load();
        return parent::setLike_count($like_count);
    }

    public function getShare_count()
    {
        $this->__load();
        return parent::getShare_count();
    }

    public function setShare_count($share_count)
    {
        $this->__load();
        return parent::setShare_count($share_count);
    }

    public function getMake_as_cover_photo()
    {
        $this->__load();
        return parent::getMake_as_cover_photo();
    }

    public function setMake_as_cover_photo($make_as_cover_photo)
    {
        $this->__load();
        return parent::setMake_as_cover_photo($make_as_cover_photo);
    }

    public function getWallPost()
    {
        $this->__load();
        return parent::getWallPost();
    }

    public function setWallPost($wallPost)
    {
        $this->__load();
        return parent::setWallPost($wallPost);
    }

    public function getSocialise_photo_custom_privacies()
    {
        $this->__load();
        return parent::getSocialise_photo_custom_privacies();
    }

    public function setSocialise_photo_custom_privacies($socialise_photo_custom_privacies)
    {
        $this->__load();
        return parent::setSocialise_photo_custom_privacies($socialise_photo_custom_privacies);
    }

    public function getSocialise_photosLike()
    {
        $this->__load();
        return parent::getSocialise_photosLike();
    }

    public function setSocialise_photosLike($socialise_photosLike)
    {
        $this->__load();
        return parent::setSocialise_photosLike($socialise_photosLike);
    }

    public function getSocialise_photosShare()
    {
        $this->__load();
        return parent::getSocialise_photosShare();
    }

    public function setSocialise_photosShare($socialise_photosShare)
    {
        $this->__load();
        return parent::setSocialise_photosShare($socialise_photosShare);
    }

    public function getSocialise_photosComment()
    {
        $this->__load();
        return parent::getSocialise_photosComment();
    }

    public function setSocialise_photosComment($socialise_photosComment)
    {
        $this->__load();
        return parent::setSocialise_photosComment($socialise_photosComment);
    }

    public function getSocialise_photosSocialise_album()
    {
        $this->__load();
        return parent::getSocialise_photosSocialise_album();
    }

    public function setSocialise_photosSocialise_album($socialise_photosSocialise_album)
    {
        $this->__load();
        return parent::setSocialise_photosSocialise_album($socialise_photosSocialise_album);
    }

    public function getSocialise_photosPosted_by()
    {
        $this->__load();
        return parent::getSocialise_photosPosted_by();
    }

    public function setSocialise_photosPosted_by($socialise_photosPosted_by)
    {
        $this->__load();
        return parent::setSocialise_photosPosted_by($socialise_photosPosted_by);
    }

    public function getPhotoGroup()
    {
        $this->__load();
        return parent::getPhotoGroup();
    }

    public function setPhotoGroup($photoGroup)
    {
        $this->__load();
        return parent::setPhotoGroup($photoGroup);
    }

    public function getCreated_at()
    {
        $this->__load();
        return parent::getCreated_at();
    }

    public function setCreated_at($created_at)
    {
        $this->__load();
        return parent::setCreated_at($created_at);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'image_name', 'description', 'comment_count', 'like_count', 'share_count', 'make_as_cover_photo', 'created_at', 'wallPost', 'socialise_photo_custom_privacies', 'socialise_photosLike', 'socialise_photosShare', 'socialise_photosComment', 'socialise_photosSocialise_album', 'socialise_photosPosted_by', 'photoGroup');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}