
<?php
/* Including JS */
$this->headScript()->appendFile( PUBLIC_PATH."/js/admin/profile.js" );


/* Including CSS */
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/dataTables.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/admin/profile.css" );
?>

<style>
.admin-form {
	width: 96%;
	float: left;
	margin: 0;
	padding: 0 2%;
}

.admin-form-lt {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
}

.admin-form-rt {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
}

.admin-form-lt label {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
}

.admin-form-lt span {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
	min-height: 60px;
}

.admin-form-rt label {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
}

.admin-form-rt span {
	width: 50%;
	float: left;
	margin: 0;
	padding: 0;
	min-height: 60px;
}

.admin-btn-outer {
	width: 100%;
	float: left;
	text-align: center;
}

.admin-btn-outer input[type="button"] {
	width: auto;
	padding: 5px 10px;
}

@media only screen and (min-device-width:768px) and
	(max-device-width:1024px) {
	.admin-form-lt {
		width: 100%;
	}
	.admin-form-rt {
		width: 100%;
	}
	.admin-form-lt label {
		width: 100%;
	}
	.admin-form-lt span {
		width: 100%;
	}
	.admin-form-lt span input {
		width: 75%;
	}
	.admin-form-rt span input {
		width: 75%;
	}
	.admin-form-rt label {
		width: 100%;
	}
	.admin-form-rt span {
		width: 100%;
	}
}
</style>
<?php 
	$admin_details = $this->admin_details;
	

?>
<div id='heading'>
	<h2>
		Profile
	</h2>

</div>
<?php
	if($admin_details)
	{
?>
		<form name="edit-admin" id="edit-admin" enctype="multipart/form-data" method="POST"
		action="/<?php echo PROJECT_NAME; ?>admin/profile/index/id/<?php echo $admin_details[0]->getId(); ?>">
<?php 
	}
?>

		<div class="admin-form">
			<div class="admin-form-lt">
				<label>First Name</label> 
				<span>
				<input type="text" tabindex="1" name="first_name" id="first_name"
				 value="<?php echo $admin_details[0]?$admin_details[0]->getFirstname():'';  ?>" />
				</span>

				<label>Email ID</label>
				<span>
				<input type="text" tabindex="3" name="email_id" id="email_id"
				value="<?php echo $admin_details[0]?$admin_details[0]->getEmail_id():''; ?>" /></span>

				<label>Upload Profile Pic</label>
				<span> 
				<input type="file" title="<?php echo $admin_details[0]?$admin_details[0]->getProfile_picture():'' ?>"
				name="profile_pic" id="profile_pic" value="<?php echo $admin_details[0]?$admin_details[0]->getProfile_picture():''; ?>" />
				<div class="image_text">Upload new image</div>
				</span> 
				
<?php 			if($admin_details[0] && $admin_details[0]->getProfile_picture())
				{
?>
					<span class="admin_profile_image" id="admin_profile_image">
						<img width="100px" height="100px" src='<?php echo IMAGE_PATH; ?>/admin_profile/<?php echo $admin_details[0]->getProfile_picture(); ?>'>
						<a href="javascript:;" class="cross_image_icon" onclick="removeAdminProfilePicture(<?php echo $admin_details[0]->getId() ?>);">
						<img width="12px" height="12px" src="<?php echo IMAGE_PATH; ?>/cross-white2.png">
						</a>
					</span>
<?php 
				}
				if($admin_details[0]->getRole()->getId() == 1)
				{
?>
				<label>General Password</label> 
				<span>
				<input type="text" tabindex="7" name="general_password" id="general_password"
				 value="<?php //echo $admin_details[0]?$admin_details[0]->getSix_digit_general_password():'';  ?>" />
				 <div class="pswd_text">only if changing</div>
				</span>
<?php			
				 }
?>
				<span>
				<input type="hidden" id="current_email_id" name="current_email_id"
				value="<?php echo  $admin_details[0]?$admin_details[0]->getEmail_id():''; ?>" /></span>
			</div>

			<div class="admin-form-rt">

				<label>Last Name</label> <span><input type="text" tabindex="2"
					name="last_name"
					value="<?php echo $admin_details[0]?$admin_details[0]->getLastname():''; ?>" /></span>

<?php 		if( $admin_details[0] )
			{
?>
			<label>Password</label> <span> <input type="password" tabindex="5"
					name="password" value="" id="password" />
					<div class="pswd_text">only if changing</div>
				</span> <label>Confirm Password</label> <span> <input
					type="password" tabindex="6" name="cpassword" value=""
					id="cpassword" />
					<div class="pswd_text">only if changing</div>
				</span>
<?php  
			}
?>
			
			
	  </div>

			<div class="admin-btn-outer">
				<input value="Save" class="btn btn-large" type="submit" /> 
				<a href="<?php echo PROJECT_URL."/".PROJECT_NAME."admin/profile/" ?>"></a>
			</div>

		</div>
	</form>