<style>
div#userNotExist
{
	margin: 20px auto;
	display: block;
	text-align: center;
}
.content
{
	background: none repeat scroll 0 0 white;
    border: 4px double silver;
    width: 935px;
}
.content-right
{
	margin:0 0 0 16px;
}
</style>

<div id = "userNotExist">
	<h3>
		<b>Sorry,</b> this page is not available.
	</h3>
	<p style="text-align:center;">
<?php 
		if( $this->message )
		{
			echo $this->message;
		}
		else
		{	
			echo "The link you followed may be broken, or the page may be removed.";
		} 
?>
	</p>
</div>