<?php
// Title
$this->headTitle ()->prepend ( 'Notes' );
//JS
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/notes.js" );
$this->headScript()->prependFile( PUBLIC_PATH."/js/frontend/jquery.stylish-select.js" );

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/links.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/notes.css" );


echo $this->partial('partials/profile_menu.phtml');
?>
<!-- Content Right Right Starts -->
<div class="content-right-right">
<!-- Photo Album Starts -->
	<div class="home-search-right">
		<div class="photoalbum-outer">
			<div class="photoalbum-hdr">
				<h2 style="width: auto;" class="text-purple2">
				All My Notes
				</h2>
<?php				
			if( $this->paginator )
			{	
				if( $this->paginator->getTotalItemCount() )
				{
?>
				<div style="margin-top: 0px" class="bookmarks-hdr-text1">
					<div class="mail-hdr-search">
						<form name="search-form" id="search-form" method="get" action="">
						<input style="color:#A0A0A0 !important; width: 199px !important; margin: 0 10px 0 -29px !important;" type="text" value="<?php echo $this->note_text;?>" name="note_search" id="note_search" placeholder="Search notes"> 
<!-- 						<a href="javascript:;" id="link_search" class="fr" onclick="searchUser()">
 							<img src="<?php echo IMAGE_PATH;?>/search-icon-purple.png" alt="Search" title="Search" width="25" height="25" align="absmiddle" />-->
							<input type ="submit" class="btn-dark-purple search_notes" value="Search"/>
<!-- 						</a> -->
						</form>
					</div>
<?php					
				}
			}
?>							
				</div>
				<div class="manage-pop-outer" style="display:none;">
               	   <div class="manage-pop">
						<div class="col1">
                     		<img width="14" height="16" align="absmiddle" src="<?php echo IMAGE_PATH;?>/icon-star-purple.png">
                     		<a id="addBookmark" onclick="addBookmark()" class="text-grey2-link" href="javascript:;">Add to Bookmarks</a>
                     	</div>
						<div class="col1">
							<img width="16" height="13" align="absmiddle" style="margin-top:3px;" src="<?php echo IMAGE_PATH;?>/mail-hover.png">
							<a onclick="sngMsg()" class="text-grey2-link" href="javascript:;">Send Message</a>
						</div>
						<div class="msg-popup-outer" style="display:none;">
							<div class="msg-popup-top"><img width="26" height="16" src="<?php echo IMAGE_PATH;?>/arrow-popup.png"></div>
							<div class="msg-popup-bot">
								<h4>Send Message</h4>
								<textarea name="sndmultiple" id="sndmultiple" cols="" rows="8"></textarea>
	                            <div class="common-div">
	                            	<div class="fl"><a class="text-purple-link" onclick="sngMsg()" href="javascript:;">Cancel</a></div>
	                                <div class="fr"><a id="sndmsg" class="text-purple-link" href="javascript:;" onclick="sendMessage()">Send</a></div>
	                            </div>
	                        </div>
						</div>
						<div class="col1">
							<img width="16" height="16" align="absmiddle" src="<?php echo IMAGE_PATH;?>/icon-pencil-hover.png"><a class="text-grey2-link" href="javascript:;" id="<?php echo Auth_UserAdapter::getIdentity()->getId();?>" onclick="getManageTags(this);">Edit Tags</a>
							<!-- Tag Popup Outer -->
							<div id="tag-manage-outertags" class="tag-manage-outer" style="display: none;">
								<div class="tag-manage-arrow">
									<img width="26" height="16" src="<?php echo IMAGE_PATH;?>/arrow-popup.png">
								</div>
								<div class="tag-manage" id="tag-manage_<?php echo Auth_UserAdapter::getIdentity()->getId();?>">
									<div id="loading_<?php echo Auth_UserAdapter::getIdentity()->getId();?>" style="display:table-cell;width:170px;text-align:center;vertical-align:middle;">
										<img src="<?php echo IMAGE_PATH;?>/loading_medium_purple.gif">
									</div>
								</div>
							</div>                                                   	     
						<!-- Tag Popup Outer --> 
						</div>
						<div class="col1">
						</div>
                   </div>
				</div>
				<!-- Manage Pop Outer Ends -->
			</div>
		</div>
		<div class="bookmark-search-right">
<?php 
			if( $this->paginator )
			{	
				if( $this->paginator->getTotalItemCount() )
				{
?>				
					<div class="col3">
						<div class="fl text-grey3">
<?php 
						$query_str = "";
						foreach( $this->prms as $key=>$p )
						{
						if( $key == "controller" || $key == "action" || $key == "module" || $key == "list_len" )
						{
							continue;
						}
						$query_str .= $key."=".$p."&amp;"; 
						}
?>
						VIEWS 
						<a class="text-grey3-link" style="margin-left: 5px"
							href="<?php echo "/".PROJECT_NAME."Profile/notes?".$query_str."list_len=10";?>"><?php echo $this->prms["list_len"] == 10 ? "<b>10</b>" : '10'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."Profile/notes?".$query_str."list_len=20";?>"><?php echo $this->prms["list_len"] == 20 ? "<b>20</b>" : '20'?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."Profile/notes?".$query_str."list_len=30";?>"><?php echo $this->prms["list_len"] == 30 ? "<b>30 </b>" : '30 '?></a> | <a class="text-grey3-link"
							href="<?php echo "/".PROJECT_NAME."Profile/notes?".$query_str."list_len=all";?>"><?php echo $this->prms["list_len"] == 'all' ? "<b>All</b>" : 'All'?></a>
						</div>
						<div class="fr  text-grey3">
<?php
							echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
?>							
						</div>
					</div>
					<div style="height:23px;" class="col3">
						<input style="float:left;" type="checkbox" value="" name="check_all_notes" id="check_all_notes">
						<!--  <span style="margin: 0 0 0 9px;">Select all</span> -->
						<span style="margin: 7px 0 0 5px !important;cursor:pointer;font-weight:bold;float:left; display:none;margin:0;color:#6C518F" id="delete_multiple_notes"  title="Delete" alt="Delete" name="delete_multiple_notes">
						Delete
						</span>
					</div>
<?php
				}
			}
?>					
			<!-- Col3 Ends -->
		</div>
		<div class="photo-slider">
<?php 
			if( $this->paginator )
			{					
				if( $this->paginator->getTotalItemCount() )
				{
					$i=0;
					foreach ( $this->paginator as $myNote )
					{
						$i++;
						$mod_clas=$i%3;
						if($mod_clas==1)
						{
							$arrow_class="arrow-first";
							$quickview_class="quickview-outer";
						}
						else if($mod_clas==2)
						{
							$arrow_class="arrow-second";
							$quickview_class="quickview-outer-second";
						}
						else if($mod_clas==0)
						{
							$arrow_class="arrow-third";
							$quickview_class="quickview-outer-third";
						}
		
                
			//mail-grey-hdr-col1 
			?>
			<div class="mail-grey-hdr-col1" id = "<?php echo $myNote->getId();?>">
			
			
				<div class="notes-listing-outer">
					<div class="notes-listing-left">
						<input type="checkbox" value="<?php echo $myNote->getId(); ?>" name="check_note" class="check_note" id = "check_note_<?php echo $myNote->getId(); ?>">
					</div>
					<div class="notes-listing-right">
						<div class="news-content-icon" >
							<div>
								<a style=" text-decoration: none;" href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>profile/iprofile/id/<?php echo $myNote->getUser_profileUser()->getId();?>">
									<img style="max-width:50px; max-height:50px" src="<?php echo Helper_common::getUserProfessionalPhoto($myNote->getUser_profileUser()->getId(), 3 );?>">
								</a>
							</div>
						</div>
						<div class="discussion-right" style="padding-bottom: 0px;">
							<h4 class="text-purple" style="font-family:arial !important;text-transform:capitalize !important;color: #551A8B !important;">
								<a style=" text-decoration: none;color: #551A8B;" href="<?php echo PROJECT_URL.'/'.PROJECT_NAME;?>profile/iprofile/id/<?php echo $myNote->getUser_profileUser()->getId();?>"><?php echo $myNote->getUser_profileUser()->getFirstname()." ".$myNote->getUser_profileUser()->getLastname();?></a>
							</h4>
<?php 
							$note_forUser_professionalInfo = \Helper_common::getUserProfessionalInfo($myNote->getUser_profileUser()->getId());
							if($note_forUser_professionalInfo)
							{
								$note_forUser_job = $note_forUser_professionalInfo[0];
								$note_forUser_company = $note_forUser_professionalInfo[1];
?>
							<h5 class="arial-grey" style="text-transform:capitalize !important; margin: 3px 0 0;" title=" <?php echo $note_forUser_professionalInfo[0]; ?> "><?php echo Helper_common::showCroppedText( $note_forUser_professionalInfo[0], 160); ?>
						
								<span style="float:left; margin:3px 0 0; width:100%;" title="<?php echo $note_forUser_professionalInfo[1] ;?>">
<?php 								
								echo Helper_common::showCroppedText( $note_forUser_professionalInfo[1], 55 ); 
?>
								</span>
							</h5>
<?php 
					}
							//$resource = stream_get_contents($myNote->getUser_note());
							$strip_tag_note = strip_tags($myNote->getUser_note()); 
							//Displaying notes as plain text
?>
							<div  id = "editor_div_<?php echo $myNote->getId();?>" class = "editor_div">
							</div>
							<div style=" position:absolute;top:50px;right:0px;margin: 0 10px 0 0;" class="fr">
								<form name="edit_notes_form" id = "edit_notes_form" method = "post">
									<div class ="edit_delete_note">
										<span  style="margin-right:6px;" class="text-purple edit_note" name="edit_note" rel ="<?php echo $myNote->getId();?>">Edit
										</span>
										<span  style="margin-right:6px;display:none;" class="text-purple save_note" name="save_note"  rel1="<?php echo $myNote->getUser_profileUser()->getId();?>" rel = "<?php echo $myNote->getId();?>">Save
										</span>
										|
										<span style="margin-left:6px;" class="text-purple delete_note" name="delete_note"  rel = "<?php echo $myNote->getId();?>">Delete
										</span>
									</div>
								</form>
							</div>
						</div>
<?php 
						if(strlen($strip_tag_note )<= 140)
						{
							//Fulll note in its formatted form that has to be shown when there is no need to show cropped note.
?>
						<div  title="full note" class="formatted_full_note1" id="formatted_full_note_1_<?php echo $myNote->getId();?>" rel="<?php echo $myNote->getId();?>">
						<?php echo $myNote->getUser_note() ;?>
						<!-- <span rel="'.$myNote->getId().'" id="show_less_"'.$myNote->getId().'" class="show_less">less</span>'; -->
						</div>
<?php 
				}
				else
				{
					//Formatted note that has to be shown after clicking on show more.
?>
					<div  title="full note" class="formatted_full_note" id="formatted_full_note_<?php echo $myNote->getId();?>" rel="<?php echo $myNote->getId();?>">
					<?php echo $myNote->getUser_note() ;?>
						<span title="show less" onclick="showLessNote(this);" rel="<?php echo $myNote->getId();?>" id="show_less_<?php echo $myNote->getId();?>" class="show_less">&lt;&lt;Less</span>
					</div>
					
					<div class="clickable_note" id="clickable_note_<?php echo $myNote->getId();?>" rel="<?php echo $myNote->getId();?>">
					<?php echo Helper_common::showCroppedText(strip_tags( $myNote->getUser_note() ),250 );?>
						<span title="show more" onclick="showMoreNote(this);" rel="<?php echo $myNote->getId();?>" id="show_more_<?php echo $myNote->getId();?>" class="show_more">More>></span>
					</div>
					<?php 
				}
				?>
				</div>

				</div>
			</div>
 			
<?php 
				
					}
				}
			}
			else
			{
				?>
				
				<div class="no_messages">
					<div class="no_messages-img"><img src="<?php echo PUBLIC_PATH;?>/images/empty-notes.png"></div>
					<div class="no_messages-data">Your Notes folder is empty</div>
				</div>
				<?php 
			}
?> 
				<!-- Photo Album Ends -->
		</div>  
	</div>
		<!-- Content Right Right Ends -->
</div>
<!-- Dialog Box -->
<div id="dialog_confirm" title="Delete Note">
  <p>
  	Are you sure you want to delete this note?
  </p>
</div>
<div id="dialog_confirm_delete_selected_notes" title="Delete selected notes">
  <p>
  	Are you sure you want to delete selected notes?
  </p>
</div>