<!-- Including JS -->
<?php
$this->headTitle()->prepend('Photo Detail');

$this->headScript()->appendFile( PUBLIC_PATH."/js/jQuery.bPopup.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/jquery.form.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/photo_detail.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/jquery-fullscreen-plugin-master/jquery.fullscreen-min.js" );

$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/photo_detail.css" );

$photoDetail=$this->photoDetail;

if( Auth_UserAdapter::getIdentity()->getId() == $photoDetail->getSocialise_photosPosted_by()->getId() )
{
	echo $this->partial ( 'partials/profile_menu.phtml' );
}
else
{
// 	Conditional CSS
?>
<style type="text/css">
	.content-right-right 
	{
		margin: 0 !important;
	}
	.pic-div
	{
		width:100%;
		margin:0;
		padding:0;
		float:left;
	}
	.pic-div img
	{
		width:100%;
		margin:0;
		padding:0;
		float:left;
	}
	
</style>
<?php 
}

if($photoDetail->getSocialise_photosSocialise_album()->getAlbum_name()=="DEFAULT")
{
	$albName=$photoDetail->getSocialise_photosSocialise_album()->getAlbum_name();
}
else
{
	$albName=$photoDetail->getSocialise_photosSocialise_album()->getAlbum_name().'_'.$photoDetail->getSocialise_photosSocialise_album()->getCreated_at_timestamp()->getTimeStamp();
}
$album_posted_by = $photoDetail->getSocialise_photosPosted_by()->getId();
$imgurl=IMAGE_PATH.'/albums/user_'.$album_posted_by.'/album_'.$albName.'/wall_thumbnails/thumbnail_'.$photoDetail->getImage_name();
$fullscreenImgurl=IMAGE_PATH.'/albums/user_'.$album_posted_by.'/album_'.$albName.'/original_photos/'.$photoDetail->getImage_name();


$imgId = $photoDetail->getId();

$getShareCount = $photoDetail->getShare_count();	
$photoDescription = $photoDetail->getDescription();
if($getShareCount == 0 || $getShareCount == "null")
{
	$getShareCount = 0 ;
}
$profilePic = Helper_common::getUserProfessionalPhoto( Auth_UserAdapter::getIdentity()->getId(), 3 ); 
$photo_created_at = Helper_common::nicetime( $photoDetail->getCreated_at()->format( "Y-m-d H:i:s" ));
?>
<script>
$(document).ready(function(){
	$("span.fullscreen_mode").click(function(){
		$("div#fullsize_photo").fullScreen(true);
	});

	$("input#change_image").click(function(){
		$("div#fullsize_photo img").attr("src", "http://localhost/ilook/public/images/albums/user_19/album_Photo-for-fullscreen_1407927050/original_photos/Chrysanthemum_1407927039.jpg");
	});
});
</script>
<!-- Content Right Right Starts -->
<div id = "fullsize_photo" style = "margin-top:-100000px; border: 1px solid red;">
	<img  src="<?php echo $fullscreenImgurl;?>"/>
	<input type = "button" id = "change_image" value = "change_image"/>
</div>
<div class="content-right-right">
	<!-- Jobs Header Starts -->
	<div class="job-hdr">
		<div class="job-hdr-top">
			<h2 class="text-grey2" style=" text-transform: none;">Photo Details</h2>
			<div class="need-help">&nbsp;<a href="javascript:;" onclick="goBack();" class=" text-purple2-link" id="back_to_photo_album">Back To Photos</a></div>
		</div>
	</div>
	<div class=" detailed-disc-hdr">
		<div class="pic-div">
			<span class = "fullscreen_mode" >Fullscreen</span>
			<img src="<?php echo $imgurl;?>"/>
		</div>
		<input type="hidden" id="imgUrl" name="imgUrl" value="<?php echo $imgurl;?>" />
	</div>
	<div class="group-about-content text-grey2">
		<div id="photo_description">
			<span>
				<?php if($photoDescription){ echo $photoDescription ; }?>
			</span>
		</div>
		<div class="discussion-right-links">
			<input type = "hidden" id = "my_user_id" value = "<?php echo Auth_UserAdapter::getIdentity()->getId();?>">
			<input type = "hidden" name = "offsettt_comm" value = "0" id = "offsettt_comm">
			<div style="position:relative;" class="fl">
				<div class="ok">  
					<div style="display:inline-block; float: left;" class="like_count" >
<?php 
					if( $this->did_i_liked_this )
					{
?>
						<a style = "" href="javascript:;" class = "not_ok" onclick = "notOkThePhotoAndWallpost( <?php echo $imgId .','.$album_posted_by ; ?>, this );" rel = "'<?php echo $imgId; ?>'" >
							<span>&nbsp;</span>Not Ok
						</a>
						<a style = "display:none;" href="javascript:;" class = "ok" onclick = "okThePhotoAndWallpost( <?php echo $imgId.','.$album_posted_by; ?>, this );" rel = "'<?php echo $imgId; ?>'" >
							<span>&nbsp;</span>Ok
						</a>
<?php 
					}
					else
					{ 
?>
						<a style = "" href="javascript:;" class = "ok" onclick = "okThePhotoAndWallpost( <?php echo $imgId.','.$album_posted_by; ?>, this );" rel = "'<?php echo $imgId ;?>'" >
							<span>&nbsp;</span>Ok
						</a>
						<a style = "display:none;" href="javascript:;" class = "not_ok" onclick = "notOkThePhotoAndWallpost( <?php echo $imgId.','.$album_posted_by; ?>, this );" rel = "'<?php echo $imgId; ?>'" >
							<span>&nbsp;</span>Not Ok
						</a>
<?php 
					}
?>
					</div>
					<div style="display:inline-block; float: left;" class="like_count">
						<a style="display:inline;" href="javascript:;" onclick="openWhoLikedPopup(<?php echo $imgId.','.$album_posted_by ; ?>)"><?php if($photoDetail->getLike_count()){ echo "(".$photoDetail->getLike_count().")"; }else{ echo " ";}?></a>
					</div>
				</div>
<!-- 					Comments -->
				<div class="comments">
					<a class="add_comment" href="javascript:;" onclick = "addCommentPhotoDetail( <?php echo $imgId.','.$album_posted_by ; ?>, this )">Comments</a> 
					<span id="comment_count_<?php echo $imgId ;?>"><?php if($photoDetail->getComment_count()){ echo "(".$photoDetail->getComment_count().")"; }else{ echo "";}?></span>
				</div>
				
				
<!-- 					Share -->
				<div class="share">
					<a onclick="shareThisPost(<?php echo $imgId.','.$album_posted_by.','.$getShareCount ; ?>, this);" href="javascript:;">
						<span>&nbsp;</span>
						SHARE 
					</a> 
			<!-- 	<a class="pl20 " href="javascript:;" onclick="shareThisPost(<?php // echo $imgId.','.$album_posted_by.','.$getShareCount ; ?>, this);">
							<span id="share_count"> <?php  //if($getShareCount != 0){echo " (".$getShareCount.")"; }else{ echo "";} ?></span> Share 
						</a>--> 
					
					<span style="width: auto;" id="share_count">
					<?php if($getShareCount != 0){ ?>
						<a   href="javascript:;"><?php echo " (".$getShareCount.")";?></a>
					<?php } ?>
					</span>
				</div>
				
				<!-- add comment popup start -->
				<div style="top: 20px; left:-68px; display: none;" class="commentbox-outer">
					<form id="comment_box_<?php echo $imgId ;?>">
						<input type="hidden" value="<?php echo $imgId ;?>" name="photo_id">
						<input type="hidden" value="<?php echo $album_posted_by ;?>" name="album_posted_by">
						<div style="margin: 0 277px;" class="commentbox-arrow">
							<img width="19" height="11" src="<?php echo IMAGE_PATH;?>/arrow-commentbox.png">
						</div>
						<div class="commentbox-content">
							<div style="float:left; width:auto;" class="commentbox-left">
								<div>
									<img width="" height="" src="<?php echo $profilePic ;?>">
								</div>
							</div>
							<div class="commentbox-right">
								<textarea name="comment" cols="" rows="5" maxlength="255"></textarea>
								<input type="button" name="add_comment" alt="Add Comment" title="Add Comment" class="btn-purple fr mt5" onclick="addComment( <?php echo $imgId ;?>, this )" value="Add Comment">
							</div>
						</div>
					</form>
				</div>
				<!-- add comment popup end -->
<?php 
				if($album_posted_by == Auth_UserAdapter::getIdentity()->getId())
				{ 
?>
				<div class="more">
					<a href="javascript:;">
						<span>&nbsp;</span>More
					</a>
				</div>
<?php 
				} 
?>
				<!-- More Pop -->
				<div class="more-pop-outer" style="left: 169px !important; margin: 14px 0 0 !important; z-index: 0;" >
					<div class="more-pop-arrow">
						<img width="24" height="16" src="<?php echo IMAGE_PATH;?>/arrow-up-purple.png">
					</div>
					<div style="width:160px;" class="more-pop-content">
						<a style="margin-top:3px;" href="javascript:;" onclick="editDescriptionOfPhoto(<?php echo $imgId; ?>);" class="text-purple-link">Edit Description</a>                            
					</div>
				</div>
				<!-- More Pop -->
			</div>  
			<div class="fr">
<?php 
			echo "Posted ".$photo_created_at;
?>
			</div>
		</div>
	</div>
	<!-- Comment box Starts -->
	<div id="updates_holder" class="comment-outer">
	<span id='massage_limit'><input type="hidden" name="msg_limit" id="msg_limit" value="5" /></span>
	
	</div>
	
             <div class="people-you-know-outer">  
        <div class="more-products mt-none">
             	<img width="14" height="9" align="absmiddle" src="<?php echo IMAGE_PATH;?>/arrow-down-purple.png"> <a class="text-purple-link" href="javascript:;">View More Comments </a>
             </div> 
            
             </div>
 </div>
<!-- Content Right Ends -->
<!-- Dialog Box -->
<div id="dialog_confirm_comment" title="Delete Comment" style = "display:none">
	<p>
  		Are you sure you want to delete this comment?
  	</p>
</div>
<div id="dialog_success_share" title="Share Photo" style = "display:none">
  	<p>
  		Photo shared successfully.
  	</p>
</div>
<?php 
	echo $this->partial('partials/who_liked_popup_photo_detail.phtml');
	echo $this->partial('partials/share_photo_detail_popup.phtml');
	echo $this->partial('partials/who_shared_photo_detail.phtml');
	echo $this->partial('partials/edit_description_popup.phtml');
?>