<!-- Title -->
<?php
$this->headTitle()->prepend('Projects');
?>
<!-- Including JS -->
<?php
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/projects.js" );
?>
<!-- Including CSS -->
<?php 
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/projects.css" );
?>
<style>
	a{
		text-decoration: none;
	}
</style>


<?php if ( !$this->myProj )
{
?>

<style>
	input[name=add]
	{	
 		display : none;
	}
	.add_or_edit
	{
		display: block;
	}
	span.delete_span
	{
		display: none;	
	}
	input[name=cancel]
	{
		display: none;	
	}
</style>
<?php
}
else 
{
?>
<style>
.add_or_edit
	{
		display: none;
	}
</style>	
<?php	
}		
	echo $this->partial('partials/profile_menu.phtml');
?>       
        <!-- Content Right Right Starts -->
        	<div class="content-right-right">
            	<!-- Summary Outer Starts -->
           	  <div class="summary-outer">
                	 <!-- Summary Edit Starts -->
                	  <div class="summary-edit text-grey3">
                      <h3 class="text-purple2">projects</h3>
                       <input name="add" type="button" class="btn-purple" alt="Add New Project" title="Add New Project" value="+ Add New Project" />
   	    	   </div>
                     <!-- Summary Edit Ends -->
                
                
                <!-- Contact Details Starts -->
                <form id = "project_form" action="">
               		<div class="contact-details add_or_edit">
						<input type = "hidden" name = "identity" value = "" id = "identity"/>
						<div class="contact-label-span2">
		               	<label>Name</label>
		                <span>
		                <input type="text" name="project_name" class="search-one-textbox "  maxlength="200" >
		                </span>
		                </div>
		                <div class="contact-label-span2">
		                <label>Occupation</label>
		                <span>
		                 <input type="text" name="occupation" class="search-one-textbox "  maxlength="200" >
		                </span>
		                </div>
		                <div class="contact-label-span2">
		                <label>Date</label>
						<span class="text-grey2" style = "width: 250px;">
							<label>
								From
							</label>
							<span>
								<input name="from_date" type="text" value="" readonly/>
							</span>
							<br />
							<label>
								To
							</label>
							<span>
								<input name="to_date" type="text" value="" readonly/>
							</span>
						</span>
						</div>
						<div class="contact-label-span2">
		                
		                 <label>Project URL</label>
		                <span>
		                 <input type="text" name="project_url" class="search-one-textbox "  maxlength="200" >
		                <sub style="float: left; margin: 3px 0;"><strong>Tip:</strong>There should be http:// before url</sub>
		                </span>
		                </div>
		                <div class="contact-label-span2">
		                 <label>Description</label>
		                
		                <span style="min-height:115px; margin-bottom:10px;">
		                 <textarea name="project_desc" class="textarea2"  cols="10" rows="5"  maxlength="250"></textarea>
		                </span>
		                </div>
	           
               		</div>
               <!-- Contact Details Ends -->
                     <div class=" summary-btn-outer bdr-grey2 add_or_edit">
						<span class = "delete_span">
							<a class="text-purple-link fl delete" href="javascript:;">Remove this Project</a>
						</span>
						<input name="save" type="button"  alt="Save" title="Save"  class="new-save-btn" value="Save" />
						<a href="javascript:;" id="cancel" class="new-cancel-btn">Cancel</a>
					</div>
                       </form>
                       
                       
                          <!-- Un Editable Outer Starts -->
                    <div id = "un-editable-outer-wrapper">
<?php
			if( $this->myProj )
			{	
				foreach ( $this->myProj as $proj )
				{
					
?>    
	                     <div class="un-editable-outer" id= "<?php echo $proj->getId(); ?>">
		                	<h3>
<?php 
							echo "<span class = 'proj_name'>".$proj->getName()."</span>";
?>		                	
							<a href="javascript:;" onclick="editClick(this)" class = "edit_exp" id = "<?php echo $proj->getId(); ?>">
								<img class="edit-new-icon" src="<?php echo IMAGE_PATH;?>/edit-pencil.png"/>
							</a>
		                	</h3>
		                    <p class= 'proj_occu' >
		                    <?php echo $proj->getOccupation(); ?>
		                    </p>
		                    
		                    <p class= 'proj_dates' >
<?php				
							echo $proj->getFrom_datee()->format('F-Y')." - ".$proj->getTo_datee()->format('F-Y');
							
							$days = intVal( $proj->getFrom_datee()->diff($proj->getTo_datee())->d );
							
							$months = intVal( $proj->getFrom_datee()->diff($proj->getTo_datee())->m );
							
							$year = intVal( $proj->getFrom_datee()->diff($proj->getTo_datee())->y );
							
							
							// for months and days
							if($months == 0 && $year == 0 && $days >= 1)  
								$diff = $days. ' day(s)';
							elseif($months == 0 && $year >= 1 && $days == 0)  
								$diff = $year.' year(s)';
							elseif($months == 0 && $year >= 1 && $days >= 1)
								$diff = $year.' year(s) '. $days.' day(s)';
							elseif($months >= 1 && $year == 0 && $days == 0)
								$diff = $months.' month(s)';
							elseif($months >= 1 && $year == 0 && $days >= 1)
								$diff = $months.' month(s) '.$days.' day(s)';
							elseif($months >= 1 && $year >= 1 && $days == 0)
								$diff = $year. ' year(s) '.$months.' month(s) ';
							elseif($months >= 1 && $year >= 1 && $days >= 1)
								$diff = $year.' year(s) '.$months.' month(s) '.$days.' day(s)';
							else
							{	
								$diff = $year.' year(s) '.$months.' month(s) ';
							}
							echo ' (' . $diff . ')';
?>
		                    </p>
		                    
		                    <p class= 'proj_url'>
		                    	<?php echo $proj->geturl(); ?>
		                    </p>
<!-- 		                    <p class ='proj_team' > -->
<!-- 		                    	<strong>Team Members</strong> : Jay, Tom, Steve -->
<!-- 		                    </p> -->
		                    <p class= 'proj_descrip' >
		                    	Description : <?php echo $proj->getDescprition(); ?>
		                    </p>
	                	</div>
<?php 
				}
			}
?>	                	                	
	                </div>
                     <!-- Un Editable Outer Ends -->
                   
              </div>
                <!-- Summary Outer Ends -->
          </div>
        <!-- Content Right Right Ends -->
