<div id="add_education_popup" class = "popup transparent_border" style = "display: none;">
	<div class="add_education_outer" style="width: 490px;">
		<!-- Forgot Password Header -->
		<div class="add_education_hdr_inner">
			<div id="add_education_hdr_inner_2" class="left text-white">
				<h2>Add Education</h2>
				<img class="close_bpopup closs-edu-bpopup" src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close" title="Close" width="21" height="20" />
			</div>
		</div>
			<!-- Forgot Password Header -->
			<!-- Forgot Password Content -->
			<div id = "add_education_box" class="add_education_box">
			</div>
			<!-- Forgot Password Content -->
	</div>
</div>