<div id="comments_listing_popup" class = "popup transparent_border" style = "display: none; ">
	<div class="forgot-password-outer_1" style="width:395px;">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr_1">
			<div id="forgot-password" class="left text-white">
				<h2>Comments</h2>
				<img class="close_bpopup"
						src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
						title="Close" width="21" height="20" />
			</div>
		</div>
		<!-- Forgot Password Header -->
			<!-- Forgot Password Content -->
			<div id = "list_of_comments" class="forgot-password-content_1">
			</div>
			<!-- Forgot Password Content -->
	</div>
</div>