<div id="edit_description_popup" class = "popup transparent_border" style = "display: none;">
	<div class="forgot-password-outer_1">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr_1">
			<div id="forgot-password_2" class="left text-white">
				<h2 style="width:250px !important;">Description of Photo</h2>
				<img class="close_bpopup"
						src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
						title="Close" width="21" height="20" />
			</div>

		</div>
		<!-- Forgot Password Header -->
			<!-- Forgot Password Content -->
			<div id = "share_box" class="forgot-password-content_1" style="min-height:150px;">
			
			</div>
			<!-- Forgot Password Content -->
	</div>
</div>