<?php
/**
 * purpose: To create the forgot password popup content
 * @version 1.0 
 * @author Devi Lal Vermma
 */	
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/forgot_password_popup.css" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/forgot_password_popup.js" );

?>
<!-- Forgot password popup phtml -->
<div id="forgotpopup">
	<div class="forgot-password-outer">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr">
			<div id="forgot-password" class="left text-white">
				<h2>Forgot Password</h2>
			</div>
			<div  id="close_bpopup" class="right">
				<img
					src="<?php echo IMAGE_PATH; ?>/cross2.png"
					alt="Close" title="Close" width="21" height="20" />
			</div>
		</div>
		<!-- end Forgot Password Header -->
		<form id="forgotPwd" name="forgotPwd" action="" method="post">
		<!-- Forgot Password Content -->
		<div class="forgot-password-content" style="overflow-y: hidden !important;">
			
<?php 		if((isset($this->message)))
			{
?>
				<div id="errmsg" class="errmsg text-white">
				<h1>
					<span>
<?php 						
						echo $this->message[0];
?>
					</span>
				</h1>
			</div>
<?php
			}
?>
		
			<div id = "innerContainer" style = "height: 75px;">
				<label for="emailForgot">Email Address:</label> 
				<span> 
					<input id="emailForgot" name="emailForgot" type="text" value="" />
				</span> 
				<label>&nbsp;</label> 
				<span id="forgot-suggestion">
					Please enter your email address to update password
				</span> 
			</div>
			
			<span id="forgot_email_span" class="fr"> <input name="forgot_email_submit"
				id="forgot_email_submit" alt="Submit" title="Submit" type="button" 
				value="SUBMIT" />
			</span>
		</div>
		<!-- Forgot Password Content -->
		</form>
	</div>
</div>

