<div class="popup-wrapper" style="display:none;">
	<div class="popup-left">
	<input type="hidden" id="limit_who_liked_photo" name="limit_who_liked_photo" value="2" />
	<input type="hidden" id="offset_who_liked_photo" name="offset_who_liked_photo" value="0" />
	<input type="hidden" id="limit_who_shared_photo" name="limit_who_shared_photo" value="2" />
	<input type="hidden" id="offset_who_shared_photo" name="offset_who_shared_photo" value="0" />
		<div class="popup-lt-mid">
		
			<div class="popup-arrow-lt">
			</div>
			<div class="popup-arrow-rt">
			</div>
			<input type = "hidden" name = "is_fullscreen_mode" value = "0" id = "is_fullscreen_mode" />
			<div class="popup-lt-mid-inner" id="realImage">
				<!-- image show here... -->
			</div>
		</div>
		
	</div>
	<div class="popup-right">
	</div>  
</div>
<div class="fullscreen-popup">
</div>