<?php 
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/send_report_abuse_mail_popup.css" );
?>
<div id="report_abuse_post" class = "popup transparent_border" style = "display: none;">
	<div class="forgot-password-outer_1" style="width: 490px;">
		<div class="forgot-password-hdr_1">
			<div id="forgot-password_2" class="left text-white">
				<h2>Send Report Abuse Mail</h2>
				<img class="close_bpopup"
						src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
						title="Close" width="20" height="18" />
			</div>
		</div>
			<!-- Send Report abuse mail -  Content -->
			<div id = "send_report_abuse_mail_box" class="forgot-password-content_1">
				
			</div>
			<!-- Send Report abuse mail - content ends -->
	</div>
</div>