<!-- Including CSS -->
<div id="gmail_popup" class = "popup transparent_border" style = "display: none;">
	<div class="forgot-password-outer">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr">
			<div id="forgot-password" class="left text-white">
				<h2>Contact list</h2>
			</div>

			<div class="right">
				<img class="close_bpopup"
					src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
					title="Close" width="21" height="20" />
			</div>

		</div>
		<!-- Forgot Password Header -->
		<form id="email_contacts_form">
			<!-- Forgot Password Content -->
			<div class="forgot-password-content">
				<div class="contact-list" id="modal_contacts">
				</div>
				<span id="gmail_import" class="fr" style="display:none;">
					<input id="share_job_with" type="button" value="Share" name="share_job_with">
				</span>
			</div>
			<!-- Forgot Password Content -->
		</form>
	</div>
</div>