<div id="share_photo_detail_popup" class = "popup transparent_border" style = "display: none;">
	<div class="forgot-password-outer_1" style="width:500px !important;">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr_1" style="width:92% !important;">
			<div id="forgot-password_2" class="left text-white">
				<h2>Share Photo Detail</h2>
				<img class="close_bpopup"
						src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
						title="Close" width="21" height="20" />
			</div>

		</div>
		<!-- Forgot Password Header -->
			<!-- Forgot Password Content -->
			<div id = "share_box" class="forgot-password-content_1">
				<div id  = "upper_container">
					<div id = "photo_thumbnail">
					</div>
					<div id = "privacy">
					</div>					
				</div>
				<div id  = "lower_container">
					<div id = "photo_text">
					</div>				
					<div id = "share_btn">
					</div>				
				</div>
			</div>
			<!-- Forgot Password Content -->
	</div>
</div>