<div id="share_dashboard_post_popup" class = "popup transparent_border" style = "display: none;">
	<div class="forgot-password-outer_1" style="width: 490px;">
		<!-- Forgot Password Header -->
		<div class="forgot-password-hdr_1">
			<div id="forgot-password_2" class="left text-white">
				<h2>Share Wall Post</h2>
				<img class="close_bpopup"
						src="<?php echo PUBLIC_PATH;?>./images/cross2.png" alt="Close"
						title="Close" width="20" height="18" />
			</div>
		</div>
		<!-- Forgot Password Header -->
			<!-- Forgot Password Content -->
			<div id = "share_box" class="forgot-password-content_1">
				
			</div>
			<!-- Forgot Password Content -->
	</div>
</div>