<!-- Title -->
<?php
$this->headTitle()->prepend( 'Trash' );
?>
<!-- Including JS -->
<?php
$this->headScript()->appendFile( PUBLIC_PATH."/js/jQuery.bPopup.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/mails.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/frontend/mail_trash.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/center.jquery.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/overlay/jquery.overlay.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/tokenInput/jquery.tokeninput.js" );
$this->headScript ()->appendFile ( PUBLIC_PATH ."/js/nailthumb.1.1/nailthumb/jquery.nailthumb.1.1.js" );
?>
<!-- Including CSS -->
<?php
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/wallpost_email_template.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/mail.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/easy_pagination_jquery_ajax.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/js/tokenInput/token-input-facebook.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/css/frontend/import_gmail_contacts_popup.css" );
$this->headLink ()->appendStylesheet ( PUBLIC_PATH ."/js/nailthumb.1.1/nailthumb/jquery.nailthumb.1.1.css" );


//==========================================
// Start Blueimp jQuery-File-Upload includes
//==========================================

//$this->headLink()->appendStylesheet( PUBLIC_PATH."/temp/blueimp-gallery.min.css" );
$this->headLink()->appendStylesheet( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload.css" );
//$this->headLink()->appendStylesheet( PUBLIC_PATH."/temp/jquery.fileupload-ui.css" );

$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/tmpl.min.js" );

$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload-process.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload-image.js" );

$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload-validate.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload-ui.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/jquery.fileupload-jquery-ui.js" );
$this->headScript()->appendFile( PUBLIC_PATH."/js/Blueimp-jQuery-File-Upload/main.js" );

//========================================
// End Blueimp jQuery-File-Upload includes
echo $this->partial('partials/mail_menu.phtml');
echo $this->render("partials/add_contacts_popup.phtml");
?>
<style>
.mid p{
	word-wrap: break-word;
}
</style>

<!-- ========  Listing message ======== -->
	<!-- Content Right Right Starts -->
	<div class="content-right-right" id = "msg_listing" >
	
		<!-- Bookmarks Header Starts -->
		<div class="mail-hdr">
			<h2>
<!-- 				<font class="text-purple2 inbox_email_uread_count"></font> unread messages -->
			</h2>
			<h2>
 				Trash Messages
			</h2>
			
			<div class="bookmarks-add-new">
				<div class="fl">
					<h4 class="text-purple2">Trash</h4>
				</div>
				<div class="fr">
					<a class="text-purple-link" href="<?php echo "/".PROJECT_NAME."mail/compose"; ?>">Compose Mail</a>&nbsp;<img
						src="<?php echo IMAGE_PATH; ?>/mail-icon-mobile.png" width="16" height="19"
						align="absmiddle" />
				</div>

			</div>

			<div class="bookmarks-hdr-text1 controls">
				<div class="manage"><a href="javascript:;" class="text-purple-link" id = "manage_mails">Manage</a>&nbsp; 
				<!-- <img width="16" height="13" align="absmiddle" src="<?php echo IMAGE_PATH;?>/folder-hover.png"> -->
                      
						   <!-- Manage Pop 2 Outer Starts -->
					<div class="manage-pop-outer" style="margin-top:5px;">
						<div class="manage-pop2" id = "manage_pop_1" style = "display:none;">
						<div class="col1"></div>
							<ul>
								<!-- <li><a style="text-decoration:none;float:right;margin-right:5px" href="javascript:;" onclick="showManagePopup();">x</a></li> -->
								<li><a href="javascript:;" class = "multi_inbox" id = "multi_inbox" >Move to Inbox</a></li>
								<li><a href="javascript:;" class = "multi_inbox_trash" id = "multi_trash_inbox">Delete</a></li>
							</ul>
						</div>
					</div>
					<!-- Manage Pop 2 Outer Ends -->
					</div>
	                <div class="mail-hdr-search">
                        <input name="trash_mails_search" id="trash_mails_search" type="text" placeholder="Search" /> 
                        <a id ="search_trash_items"href="javascript:;"><img src="<?php echo IMAGE_PATH;?>/search-icon.png" alt="Search"  title="Search" width="25" height="25" align="absmiddle" /></a>
                    </div>
			</div>

			<!-- Manage Pop 2 Outer Starts -->
			<div class="manage-pop2-outer controls">
				<div class="manage-pop2" id = "manage_pop2" style = "display:none;">
					<div class="link2">
						<ul>
							<li><a href="#"><img width="16" height="13" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/folder-hover.png">Inbox</a></li>
						</ul>
					</div>
					<div class="link1">
						<ul>
							<li><a href="#"><img width="16" height="10" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/icon-eye-purple.png">Mark Unread</a></li>
							<li><a href="#"><img width="16" height="15" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/icon-read-purple.png">Mark as Read</a></li>
						</ul>
					</div>

					<div class="link1">
						<ul>
							<li><a href="#"><img width="16" height="16" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/icon-star-purple.png">Bookmarks</a></li>
						</ul>
					</div>

					<div class="link1">
						<ul>
							<li><a href="#"><img width="14" height="16" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/icon-fire-purple.png">Report as Spam</a></li>

						</ul>
					</div>

					<div class="link1">
						<ul>
							<li><a href="#"><img width="14" height="16" align="absmiddle"
									src="<?php echo IMAGE_PATH; ?>/icon-trash-hover.png">Delete</a></li>
						</ul>
					</div>

				</div>
			</div>
			<!-- Manage Pop 2 Outer Ends -->
		</div>
		<!-- Bookmarks Header Ends -->



		<!-- Mail All Starts -->
		<div class="mail-all-hdr controls">
			<div class="fl">
				<a class="text-purple-link" href="javascript:;">All</a>&nbsp;&nbsp;
				<a class="text-grey3-link" href="javascript:;">UNREAD</a>
	
			</div>
			<div class="fr ">
				<div class="col1">
					<a class="text-purple-link" href="javascript:;">BY DATE</a><img
						src="<?php echo IMAGE_PATH; ?>/arrow-double.png" width="15" height="15"
						align="absmiddle" />
				</div>
				<div class="col1">
					<a class="text-purple-link" href="javascript:;">NEWEST</a> <img
						src="<?php echo IMAGE_PATH; ?>/arrow-double.png" width="15" height="15"
						align="absmiddle" />
				</div>
			</div>
		</div>
		<!-- Mail All Ends -->
		
		<!-- Mail All Starts -->
		<div class = "pagination_nav controls">
		</div>
		<!-- Mail All Ends -->
		
		<!-- Mail Header Starts -->
		<!-- Mail Header Ends -->
		<div id = "mail_holder">
<?php 
?>
		</div>
		<!-- Mail All Starts -->
		<div class = "pagination_nav controls">
		</div>
		<!-- Mail All Ends -->
	</div>
	<!-- Content Right Right Ends -->
	
<!-- ========  Detailed message ======== -->
        <!-- Content Right Right Starts -->
        <input type="hidden" name="is_forward" id="is_forward" >
        <input type="hidden" name="is_reply" id="is_reply" >
        	<div class="content-right-right" id = "detailed_msg" style = "display: none;">
            
            	<!-- Bookmarks Header Starts -->
			 		 <div class="mail-hdr">
                    	<h2 id="mail_detail_subject">Subject</h2>
                        
                        <div class="bookmarks-add-new">
                        <div class="fl">
                          <h4 class="text-purple2">
                          	<a id = "back_to_mail_list" class="text-purple-link" href="javascript:;">
                          		<img src="<?php echo IMAGE_PATH; ?>/back-arrow.png" width="16" height="17" align="absmiddle" />
                          	</a>
                          Trash</h4>
                        </div>
                        <div class="fr"><a class="text-purple-link" href="<?php echo "/".PROJECT_NAME."mail/compose"; ?>">Compose Mail</a>&nbsp;<img src="<?php echo IMAGE_PATH; ?>/mail-icon-mobile.png" width="16" height="19" align="absmiddle" /></div>
                   	   
                       </div>
                       
                    </div>
                <!-- Bookmarks Header Ends -->
					<div id = "detial_msg_holder">
				<!--Mail detail contents append here with jQuery ajax.   -->
					</div>	
					
					<div id="reply_attachment" style="display:none;">
					<form id="fileattach_reply" action="" method="POST" enctype="multipart/form-data">
	    			<!-- Redirect browsers with JavaScript disabled to the origin page -->
	    			<noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
	    			<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
		    		<div class="fileupload-buttonbar">
				        <div class="fileupload-buttons">
				            <!-- The fileinput-button span is used to style the file input field as button -->
				            <span class="fileinput-button">
				                <span>Attach files...</span>
				                <input type="file" name="files[]" multiple id = "add_attachment" title="Add attachment">
				            </span>
				          
				            <!-- The global file processing state -->
				            <span class="fileupload-process"></span>
				        </div>
			       		<!-- The global progress state -->
				        <div class="fileupload-progress fade" style="display:none">
				            <!-- The global progress bar -->
				            <div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
				            <!-- The extended global progress state -->
				            <div class="progress-extended">&nbsp;</div>
				        </div>
		    		</div>
	   
	   			 <!-- The table listing the files available for upload/download -->
				    <div class="presentation-outer">
				   		 <table style="width:100%;" role="presentation">
				   		 	<tbody class="files"></tbody>
				   		 </table>
				    </div>
					</form>
	
				<!-- The template to display files available for upload -->
				  <script id="template-upload" type="text/x-tmpl">

	              </script>
				<!-- The template to display files available for download -->
				 <script id="template-download" type="text/x-tmpl">
    			{% for (var i=0, file; file=o.files[i]; i++) { %}
       			 <div class="template-download fade">
					{% if(file.name) { %}
	 				<label class="attachment-lalbel">{%=file.name%}</label>
					{% } %}

				<button class="delete remove_thumb" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}><img src="<?php echo IMAGE_PATH; ?>/cross-white2.png" alt="X" title="Remove"  width="10px" height="10px" /></button>
				<span class="file_attachments" ts_file_size="{%=file.size%}" ts_file_name="{%=file.name%}"></span>
            	{% if (file.error) { %}
                	<div><span class="error">Error</span> {%=file.error%}</div>
            	{% } %}
             
				</div>
   				{% } %}

				</script>
				</div>

			<div id="forward_attachment" style="display:none;">
			<form id="fileattach_forward" action="" method="POST" enctype="multipart/form-data">
	    			<!-- Redirect browsers with JavaScript disabled to the origin page -->
	    			<noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
	    			<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
		    		<div class="fileupload-buttonbar">
				        <div class="fileupload-buttons">
				            <!-- The fileinput-button span is used to style the file input field as button -->
				            <span class="fileinput-button">
				                <span>Attach files...</span>
				                <input type="file" name="files[]" multiple id = "add_attachment" title="Add attachment">
				            </span>
				          
				            <!-- The global file processing state -->
				            <span class="fileupload-process"></span>
				        </div>
			       		<!-- The global progress state -->
				        <div class="fileupload-progress fade" style="display:none">
				            <!-- The global progress bar -->
				            <div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
				            <!-- The extended global progress state -->
				            <div class="progress-extended">&nbsp;</div>
				        </div>
		    		</div>
	   
	   			 <!-- The table listing the files available for upload/download -->
				    <div class="presentation-outer">
				   		 <table style="width:100%;" role="presentation">
				   		 	<tbody class="files"></tbody>
				   		 </table>
				    </div>
					</form>

				<!-- Form to upload existing files --->
				<form id="fileupload" action="" method="POST" enctype="multipart/form-data">

					<!-- Redirect browsers with JavaScript disabled to the origin page -->
					<noscript><input type="hidden" name="redirect" value="https://blueimp.github.io/jQuery-File-Upload/"></noscript>
					<!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
					<div class="fileupload-buttonbar">
						<div class="fileupload-buttons">
							<!-- The global file processing state -->
							<span class="fileupload-process"></span>
						</div>
						<!-- The global progress state -->
						<div class="fileupload-progress fade" style="display:none">
							<!-- The global progress bar -->
							<div class="progress" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>
							<!-- The extended global progress state -->
							<div class="progress-extended">&nbsp;</div>
						</div>
					</div>
					<!-- The table listing the files available for upload/download -->
					<div class="presentation-outer">
						<table style="width:100%;" role="presentation">
							<tbody class="files"></tbody>
						</table>
					</div>
				</form>
	
	
				<!-- The template to display files available for upload -->
				  <script id="template-upload" type="text/x-tmpl">

	              </script>
				<!-- The template to display files available for download -->
				 <script id="template-download" type="text/x-tmpl">
    			{% for (var i=0, file; file=o.files[i]; i++) { %}
       			 <div class="template-download fade">
					{% if(file.name) { %}
	 				<input type="text" value="{%=file.name%}">
					{% } %}

				<button class="delete remove_thumb" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}><img src="<?php echo IMAGE_PATH; ?>/cross-white2.png" alt="X" title="Remove"  width="10px" height="10px" /></button>
				<span class="file_attachments" ts_file_size="{%=file.size%}" ts_file_name="{%=file.name%}"></span>
            	{% if (file.error) { %}
                	<div><span class="error">Error</span> {%=file.error%}</div>
            	{% } %}
             
				</div>
   				{% } %}

				</script>
				</div>
          	</div>
        <!-- Content Right Right Ends -->
        <!-- Dialog Box -->
<div id="dialog_confirm" title="Delete Mail">
  <p>
  	Are you sure you want to delete this mail?
  </p>
</div>
<div id="dialog_confirm_multiple" title="Delete Mails">
  <p>
  	Are you sure you want to delete selected mails?
  </p>
</div>