<?php
//Js
$this->headScript()->appendFile(PUBLIC_PATH . "/js/overlay/center.jquery.js");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/overlay/jquery.overlay.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/short_profile.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/notes.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/jquery.stylish-select.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/links_menu.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/import_contacts.js");
$this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/links.js");

//CSS
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/links.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/links-common.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/import_contacts.css");


$menu_size = Auth_UserAdapter::getIdentity()->getMain_menu_size();

//Partials
echo $this->partial('partials/link_menu.phtml');
echo $this->partial('partials/unlink-popup.phtml');


echo $this->partial('partials/import_gmail_contacts_popup.phtml');
echo $this->partial('partials/yahoo_login_popup.phtml');

$listArr = array();
if ($this->paginator) {
    if ($this->paginator->getTotalItemCount()) {
        foreach ($this->paginator as $v) {
            $listArr[] = $v->getId();
        }
    }
}

if ($listArr) {
    ?>
    <style>
        .linkprofile-outer {
            min-height: 571px !important;
        }
    </style>
    <?php
}
$checkboxStatus = 0;
$enableGridViewID = 0;
if ($this->userViewState == "enable") {
    $checkboxStatus = 1;
    $enableGridViewID = 1;
}
?>
<!-- Content Right Right Starts -->
<div class="content-right-right">
    <!-- WORK IN PROGRESS -->
    <!-- <div id="wip" style="background: none repeat scroll 0 0 #FFFEFF;border: 4px outset #D3B700;display: block;margin: 0 auto;">
	<img src= "<?php //echo IMAGE_PATH; ?>/WIP.jpg"/><p style="color: #FF0000;display: inline-block;float: right;font-size: 20px;margin-right: 280px;margin-top: 35px;">WORK IN PROGRESS!</p>
</div> -->
    <!-- Photo Album Starts -->
    <div class="photoalbum-outer">
        <div class="photoalbum-hdr">
            <h2 style="width: auto;" class="text-grey2">
                <font class="text-purple2">
					<span style="font-weight:normal;" class="my-links">
						<?php echo $this->allLinksCount; ?>
					</span>
                </font> Links
                <?php
                if ($this->userViewState == "enable") {
                    ?>
                    <div class="addnew-links">
                        <a class="text-purple-link" href="/<?php echo PROJECT_NAME ?>links/import">
                            Add New Links
                        </a>
                        <img src="<?php echo IMAGE_PATH; ?>/icon-connection-hover.png" align="absmiddle"/>
                    </div>
                    <?php
                }
                ?>
            </h2>
            <div style="margin-top: 0px" class="bookmarks-hdr-text1">
                <?php
                if ($this->userViewState == "enable") {
                    ?>
                    <div class="fl text-grey3">
                        <br>
                        <?php
                        if ($this->paginator) {
                            ?>
                            &nbsp;
                            <font class="text-grey3">
                                <a onclick="showManagePopup();" href="javascript:;" class="text-grey3">
                                    Manage
                                </a>
                            </font>
                            &nbsp;
                            <img width="16" height="13" align="absmiddle" src="<?php echo IMAGE_PATH; ?>/folder.png">
                            <?php
                        }
                        ?>
                    </div>
                    <?php
                }
                ?>
                <?php
                if (count($this->links) > 0 || isset($_REQUEST['linkSearch'])) {
                    ?>
                    <div class="mail-hdr-search">
                        <form name="links_search_form1" id="links_search_form1" method="get"
                              action="/<?php echo PROJECT_NAME; ?>links/index">
                            <a href="javascript:;" id="search_links_btn" class="fr srchBtn" style="float:right;">
                                Search
                            </a>
                            <input type="text" name="linkSearch" id="linkSearch"
                                   value="<?php echo @$this->linkSearchText; ?>" placeholder="Search"
                                   style="float:right;">
                        </form>
                    </div>
                    <?php
                }
                ?>
            </div>
            <!-- Manage Pop Outer Starts -->
            <!-- Manage POPUP here -->
            <div class="manage-pop-outer" style="display:none;">
                <div class="manage-pop">
                    <div class="col1">
                        <img width="14" height="16" align="absmiddle"
                             src="<?php echo IMAGE_PATH; ?>/icon-star-purple.png">
                        <a id="addBookmark" onclick="addBookmark()" class="text-grey2-link" href="javascript:;">
                            Add to Bookmarks
                        </a>
                    </div>
                    <div class="col1">
                        <img width="16" height="13" align="absmiddle" style="margin-top:3px;"
                             src="<?php echo IMAGE_PATH; ?>/mail-hover.png">
                        <a onclick="sngMsg()" class="text-grey2-link" href="javascript:;">
                            Send Message
                        </a>
                    </div>
                    <div class="msg-popup-outer" style="display:none;">
                        <div class="msg-popup-top">
                            <img width="26" height="16" src="<?php echo IMAGE_PATH; ?>/arrow-popup.png">
                        </div>
                        <div class="msg-popup-bot">
                            <h4>
                                Send Message
                            </h4>
                            <textarea name="sndmultiple" id="sndmultiple" cols="" rows="8"></textarea>
                            <div class="common-div">
                                <div class="fl">
                                    <a class="text-purple-link" onclick="sngMsg()" href="javascript:;">
                                        Cancel
                                    </a>
                                </div>
                                <div class="fr">
                                    <a id="sndmsg" class="text-purple-link" href="javascript:;" onclick="sendMessage()">
                                        Send
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col1">
                        <img width="16" height="16" align="absmiddle"
                             src="<?php echo IMAGE_PATH; ?>/icon-pencil-hover.png">
                        <a name="manageETag" class="text-grey2-link" href="javascript:;"
                           id="<?php echo Auth_UserAdapter::getIdentity()->getId(); ?>" onclick="getManageTags(this);">
                            Edit Tags
                        </a>
                        <!-- Tag Popup Outer -->
                        <div id="tag-manage-outertags" class="tag-manage-outer" style="display: none;">
                            <div class="tag-manage-arrow">
                                <img width="26" height="16" src="<?php echo IMAGE_PATH; ?>/arrow-popup.png">
                            </div>
                            <div class="tag-manage"
                                 id="tag-manage_<?php echo Auth_UserAdapter::getIdentity()->getId(); ?>">
                                <a onclick="closeEditGroupPopup();"
                                   style="float: right;margin-right: -13px;margin-top: -36px;" href="javascript:;">
                                    <img src="<?php echo IMAGE_PATH; ?>/cross-grey2.png" alt="Close" title="Close"
                                         align="absmiddle" style="float: right; margin: -21px -5px;"/>
                                </a>
                                <div id="loading_<?php echo Auth_UserAdapter::getIdentity()->getId(); ?>"
                                     style="display:table-cell;width:170px;text-align:center;vertical-align:middle;">
                                    <img src="<?php echo IMAGE_PATH; ?>/loading_medium_purple.gif">
                                </div>
                            </div>
                        </div>
                        <!-- Tag Popup Outer -->
                    </div>
                    <div class="col1">
                    </div>
                </div>
            </div>
            <!-- Manage Pop Outer Ends -->
        </div>
    </div>
    <div class="bookmark-search-right">
        <!-- Col3 Starts -->
        <?php
        if ($this->paginator) {
            if ($this->paginator->getTotalItemCount()) {
                ?>
                <div class="col3">
                    <div class="fl text-grey3">
                        <?php
                        $query_str = "";
                        foreach ($this->prms as $key => $p) {
                            if ($key == "controller" || $key == "action" || $key == "module" || $key == "list_len") {
                                continue;
                            }
                            $query_str .= $key . "=" . $p . "&amp;";
                        }
                        ?>
                        VIEWS
                        <a class="text-grey3-link" style="margin-left: 5px"
                           href="<?php echo "/" . PROJECT_NAME . "links/index?" . $query_str . "list_len=20"; ?>">
                            <?php echo $this->prms["list_len"] == 20 ? "<b>20</b>" : '20' ?>
                        </a> |
                        <a class="text-grey3-link"
                           href="<?php echo "/" . PROJECT_NAME . "links/index?" . $query_str . "list_len=50"; ?>">
                            <?php echo $this->prms["list_len"] == 50 ? "<b>50</b>" : '50' ?>
                        </a> |
                        <a class="text-grey3-link"
                           href="<?php echo "/" . PROJECT_NAME . "links/index?" . $query_str . "list_len=100"; ?>">
                            <?php echo $this->prms["list_len"] == 100 ? "<b>100</b>" : '100' ?>
                        </a> |
                        <a class="text-grey3-link"
                           href="<?php echo "/" . PROJECT_NAME . "links/index?" . $query_str . "list_len=all"; ?>">
                            <?php echo $this->prms["list_len"] == 'all' ? "<b>All</b>" : 'All' ?>
                        </a>
                    </div>
                    <div class="fr  text-grey3">
                        <?php
                        echo $this->paginationControl($this->paginator, 'Sliding', 'partials/pagination.phtml');
                        ?>
                    </div>
                </div>
                <?php
            }
        }
        ?>
        <!-- Col3 Ends -->
    </div>

    <!-- Link Profile Outer Starts -->
    <form name="link-form" id="link-form" method="post" action="">

        <?php

        if (!$this->linkSearchText) {
            $text = '<span class="no_links_img"><img src="' . IMAGE_PATH . '/invitation-icon.png" width="25" height="20"/></span>You do not have any links.';
        } else {
            $text = '<span class="no_links_img"><img src="' . IMAGE_PATH . '/invitation-icon.png" width="25" height="20"/></span>No matching results found.';
        }
        echo Helper_common::displayUsersGridView(Auth_UserAdapter::getIdentity()->getId(), $listArr, $checkboxStatus, $enableGridViewID, null, $text);
        ?>
    </form>
    <?php
    if (!$listArr) {
        ?>
        <div class="add-new-event">
            <div class="link-invite-connect">
                <h3>Invite your contacts to iLook and increase your network
                </h3>
                <div class="box1" id="gmail">
                    <div class="box1-img">
                        <img src="<?php echo IMAGE_PATH; ?>/gmail-icon.png" width="65" height="47"/>
                    </div>
                    <p>
                        <a class="text-purple2-link" href="javascript:;">Gmail</a>
                    </p>
                </div>
                <!--div class="box1">
					<div class="box1-img">
						<img style="opacity :0.2" src="<?php echo IMAGE_PATH; ?>/hotmail-icon.png" width="76" height="53" />
					</div>
					<p>
						<a class="text-purple2-link" href="javascript:;">Hotmail</a>
					</p>
				</div>
				<div class="box1" id = "yahoo">
					<div class="box1-img">
						<img src="<?php echo IMAGE_PATH; ?>/yahoo-icon.png" width="54" height="54" />
					</div>
					<p>
						<a class="text-purple2-link" href="javascript:;">Yahoo!</a>
					</p>
				</div-->
                <!--div class="box1 mr-none">
					<div class="box1-img">
						<img style="opacity :0.2" src="<?php echo IMAGE_PATH; ?>/outlook-icon.png" width="52" height="56" />
					</div>
					<p>
						<a class="text-purple2-link" href="javascript:;">Outlook</a>
					</p>
				</div-->
                <!-- Col1 Starts -->

                <div class="col1">
                    <h3>More ways to Connect</h3>
                    <div class="col1-bot">
                        <p>Invite by individual email</p>
                        <p>
                        <form action="" id="more_ways_to_connect_frm" onsubmit="return false">
                            <div class="more-ways-textbox">
                                <input id="more_ways_to_connect" name="more_ways_to_connect" type="text" value=""
                                       placeholder="Type email addresses, separated by semi-colons.."
                                       style="font-weight: bold;"/>
                            </div>
                            <div class="more-ways-btn">
                                <input name="more_ways_to_connect_btn" id="more_ways_to_connect_btn" type="button"
                                       class="btn-purple" value="Send Invitations" alt="Send Invitations"
                                       title="Send Invitations" style="float:left;"/>
                            </div>
                        </form>
                        </p>
                    </div>
                </div>
                <!-- Col1 Ends -->
            </div>
        </div>
        <?php
    }
    ?>


</div>